#HTML convert Bottom pos to Top pos

In [ ]:
import re

def convert_bottom_to_top(width: int, height: int, convertedtext: str) -> str:
    # Verwenden Sie regex, um alle 'bottom'-Eigenschaften und ihre Werte zu finden
    def replace_bottom_to_top(match):
        bottom_value = float(match.group(1))
        top_value = height - bottom_value
        return f"top:{str(round(top_value))}px"

    # Ersetzen Sie 'bottom' durch den berechneten 'top'-Wert
    updated_text = re.sub(r'bottom:(\d+\.?\d*)px', replace_bottom_to_top, convertedtext)
    return updated_text

# Beispiel-Nutzung
width = 1210
height = 825
convertedtext = """<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta charset="utf-8" />
</head>

<body style="margin: 0;">

<div id="p1" style="overflow: hidden; position: relative; background-color: white; width: 1210px; height: 825px;">

    <!-- Begin shared CSS values -->
    <style class="shared-css" type="text/css" >
        .t {
            transform-origin: bottom left;
            z-index: 2;
            position: absolute;
            white-space: pre;
            overflow: visible;
            line-height: 1.5;
        }
        .text-container {
            white-space: pre;
        }
        @supports (-webkit-touch-callout: none) {
            .text-container {
                white-space: normal;
            }
        }
    </style>
    <!-- End shared CSS values -->


    <!-- Begin inline CSS -->
    <style type="text/css" >

        #t1_1{left:18px;bottom:804px;letter-spacing:0.14px;}
        #t2_1{left:128px;bottom:804px;}
        #t3_1{left:165px;bottom:804px;letter-spacing:0.15px;}
        #t4_1{left:266px;bottom:804px;letter-spacing:0.15px;}
        #t5_1{left:394px;bottom:804px;letter-spacing:0.17px;}
        #t6_1{left:18px;bottom:804px;letter-spacing:0.14px;}
        #t7_1{left:128px;bottom:804px;}
        #t8_1{left:165px;bottom:804px;letter-spacing:0.15px;}
        #t9_1{left:266px;bottom:804px;letter-spacing:0.15px;}
        #ta_1{left:394px;bottom:804px;letter-spacing:0.16px;}
        #tb_1{left:110px;bottom:804px;}
        #tc_1{left:156px;bottom:804px;}
        #td_1{left:101px;bottom:777px;}
        #te_1{left:697px;bottom:777px;letter-spacing:0.17px;}
        #tf_1{left:18px;bottom:777px;letter-spacing:0.17px;}
        #tg_1{left:119px;bottom:777px;letter-spacing:0.17px;}
        #th_1{left:770px;bottom:777px;letter-spacing:0.17px;}
        #ti_1{left:770px;bottom:777px;letter-spacing:0.17px;}
        #tj_1{left:862px;bottom:777px;}
        #tk_1{left:862px;bottom:777px;letter-spacing:9.39px;word-spacing:-9.17px;}
        #tl_1{left:889px;bottom:777px;}
        #tm_1{left:953px;bottom:777px;letter-spacing:0.17px;}
        #tn_1{left:953px;bottom:777px;letter-spacing:0.17px;}
        #to_1{left:990px;bottom:777px;letter-spacing:0.17px;}
        #tp_1{left:770px;bottom:763px;letter-spacing:0.16px;}
        #tq_1{left:953px;bottom:763px;letter-spacing:0.11px;}
        #tr_1{left:990px;bottom:763px;letter-spacing:0.17px;}
        #ts_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tt_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tu_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tv_1{left:358px;bottom:749px;letter-spacing:0.17px;}
        #tw_1{left:358px;bottom:749px;letter-spacing:0.17px;}
        #tx_1{left:431px;bottom:749px;letter-spacing:0.17px;}
        #ty_1{left:431px;bottom:749px;letter-spacing:3.26px;word-spacing:-3.06px;}
        #tz_1{left:468px;bottom:749px;letter-spacing:0.17px;}
        #t10_1{left:477px;bottom:749px;}
        #t11_1{left:422px;bottom:749px;}
        #t12_1{left:422px;bottom:749px;}
        #t13_1{left:422px;bottom:749px;}
        #t14_1{left:788px;bottom:708px;letter-spacing:0.17px;}
        #t15_1{left:18px;bottom:694px;letter-spacing:0.15px;}
        #t16_1{left:413px;bottom:694px;letter-spacing:0.17px;}
        #t17_1{left:165px;bottom:694px;letter-spacing:0.17px;}
        #t18_1{left:165px;bottom:694px;letter-spacing:0.15px;}
        #t19_1{left:413px;bottom:681px;letter-spacing:0.17px;}
        #t1a_1{left:18px;bottom:681px;letter-spacing:0.17px;}
        #t1b_1{left:541px;bottom:681px;letter-spacing:0.17px;}
        #t1c_1{left:413px;bottom:667px;letter-spacing:0.14px;}
        #t1d_1{left:523px;bottom:667px;}
        #t1e_1{left:18px;bottom:667px;}
        #t1f_1{left:541px;bottom:667px;letter-spacing:0.17px;}
        #t1g_1{left:413px;bottom:653px;letter-spacing:0.14px;}
        #t1h_1{left:523px;bottom:653px;}
        #t1i_1{left:18px;bottom:653px;letter-spacing:0.17px;}
        #t1j_1{left:541px;bottom:653px;letter-spacing:0.17px;}
        #t1k_1{left:413px;bottom:639px;letter-spacing:0.15px;}
        #t1l_1{left:523px;bottom:639px;}
        #t1m_1{left:413px;bottom:626px;letter-spacing:0.17px;}
        #t1n_1{left:18px;bottom:626px;letter-spacing:0.17px;}
        #t1o_1{left:18px;bottom:626px;letter-spacing:0.16px;}
        #t1p_1{left:541px;bottom:626px;letter-spacing:0.17px;}
        #t1q_1{left:18px;bottom:612px;letter-spacing:0.17px;}
        #t1r_1{left:165px;bottom:612px;letter-spacing:0.14px;}
        #t1s_1{left:18px;bottom:598px;letter-spacing:0.17px;}
        #t1t_1{left:110px;bottom:598px;letter-spacing:0.17px;}
        #t1u_1{left:147px;bottom:598px;letter-spacing:0.17px;}
        #t1v_1{left:202px;bottom:598px;letter-spacing:0.16px;}
        #t1w_1{left:633px;bottom:584px;letter-spacing:0.17px;}
        #t1x_1{left:18px;bottom:584px;letter-spacing:0.17px;}
        #t1y_1{left:770px;bottom:584px;letter-spacing:0.17px;}
        #t1z_1{left:770px;bottom:584px;letter-spacing:0.17px;}
        #t20_1{left:18px;bottom:571px;letter-spacing:0.15px;}
        #t21_1{left:633px;bottom:571px;letter-spacing:0.17px;}
        #t22_1{left:147px;bottom:571px;letter-spacing:0.17px;}
        #t23_1{left:147px;bottom:571px;letter-spacing:0.17px;}
        #t24_1{left:770px;bottom:571px;letter-spacing:0.17px;}
        #t25_1{left:18px;bottom:557px;letter-spacing:0.15px;}
        #t26_1{left:128px;bottom:557px;}
        #t27_1{left:633px;bottom:557px;letter-spacing:0.17px;}
        #t28_1{left:147px;bottom:557px;letter-spacing:0.17px;}
        #t29_1{left:770px;bottom:557px;letter-spacing:0.17px;}
        #t2a_1{left:18px;bottom:543px;letter-spacing:0.15px;}
        #t2b_1{left:633px;bottom:543px;letter-spacing:0.17px;}
        #t2c_1{left:193px;bottom:543px;letter-spacing:0.17px;}
        #t2d_1{left:770px;bottom:543px;letter-spacing:0.17px;}
        #t2e_1{left:9px;bottom:502px;letter-spacing:0.17px;}
        #t2f_1{left:9px;bottom:502px;letter-spacing:0.17px;}
        #t2g_1{left:9px;bottom:488px;}
        #t2h_1{left:183px;bottom:488px;letter-spacing:1.93px;word-spacing:-1.74px;}
        #t2i_1{left:9px;bottom:474px;}
        #t2j_1{left:183px;bottom:474px;letter-spacing:1.72px;word-spacing:-1.53px;}
        #t2k_1{left:9px;bottom:461px;letter-spacing:0.17px;}
        #t2l_1{left:9px;bottom:461px;letter-spacing:0.17px;}
        #t2m_1{left:9px;bottom:419px;letter-spacing:0.17px;}
        #t2n_1{left:275px;bottom:419px;}
        #t2o_1{left:339px;bottom:419px;}
        #t2p_1{left:403px;bottom:419px;}
        #t2q_1{left:468px;bottom:419px;}
        #t2r_1{left:532px;bottom:419px;}
        #t2s_1{left:596px;bottom:419px;}
        #t2t_1{left:660px;bottom:419px;}
        #t2u_1{left:724px;bottom:419px;}
        #t2v_1{left:788px;bottom:419px;}
        #t2w_1{left:853px;bottom:419px;}
        #t2x_1{left:917px;bottom:419px;}
        #t2y_1{left:981px;bottom:419px;}
        #t2z_1{left:1045px;bottom:419px;}
        #t30_1{left:1109px;bottom:419px;}
        #t31_1{left:1173px;bottom:419px;}
        #t32_1{left:28px;bottom:406px;letter-spacing:0.17px;}
        #t33_1{left:238px;bottom:406px;letter-spacing:0.17px;}
        #t34_1{left:9px;bottom:392px;letter-spacing:0.17px;}
        #t35_1{left:211px;bottom:392px;}
        #t36_1{left:275px;bottom:392px;}
        #t37_1{left:339px;bottom:392px;}
        #t38_1{left:403px;bottom:392px;}
        #t39_1{left:28px;bottom:378px;letter-spacing:0.17px;}
        #t3a_1{left:174px;bottom:378px;letter-spacing:0.17px;}
        #t3b_1{left:816px;bottom:364px;letter-spacing:0.17px;}
        #t3c_1{left:1027px;bottom:364px;letter-spacing:0.17px;}
        #t3d_1{left:1027px;bottom:364px;letter-spacing:0.19px;word-spacing:9.17px;}

        .s0{font-size:15px;font-family:Courier;color:#000;}
    </style>
    <!-- End inline CSS -->

    <!-- Begin page background -->
    <div id="pg1Overlay" style="width:100%; height:100%; position:absolute; z-index:1; background-color:rgba(0,0,0,0); -webkit-user-select: none;"></div>
    <div id="pg1" style="-webkit-user-select: none;"><object width="1210" height="825" data="1/1.svg" type="image/svg+xml" id="pdf1" style="width:1210px; height:825px; -moz-transform:scale(1); z-index: 0;"></object></div>
    <!-- End page background -->


    <!-- Begin text definitions (Positioned/styled in CSS) -->
    <div class="text-container"><span id="t1_1" class="t s0">Seite: </span><span id="t2_1" class="t s0">( </span><span id="t3_1" class="t s0">) *Kopie* </span><span id="t4_1" class="t s0">LIEFERSCHEIN </span><span id="t5_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="t6_1" class="t s0">Seite: </span><span id="t7_1" class="t s0">( </span><span id="t8_1" class="t s0">) *Kopie* </span><span id="t9_1" class="t s0">LIEFERSCHEIN </span><span id="ta_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="tb_1" class="t s0">1 </span><span id="tc_1" class="t s0">1 </span>
        <span id="td_1" class="t s0">/ </span><span id="te_1" class="t s0">Nummer: </span><span id="tf_1" class="t s0">28.09.23 </span><span id="tg_1" class="t s0">15:22 </span><span id="th_1" class="t s0">3034948 </span><span id="ti_1" class="t s0">3034948 </span><span id="tj_1" class="t s0">1 </span><span id="tk_1" class="t s0">1 1 </span><span id="tl_1" class="t s0">1 </span><span id="tm_1" class="t s0">120 </span><span id="tn_1" class="t s0">120 31 </span><span id="to_1" class="t s0">31 </span>
        <span id="tp_1" class="t s0">Auftrag Ind SF </span><span id="tq_1" class="t s0">LO </span><span id="tr_1" class="t s0">Bt </span>
        <span id="ts_1" class="t s0">Liefernr. </span><span id="tt_1" class="t s0">_________ </span><span id="tu_1" class="t s0">Liefernr. 3034948 </span><span id="tv_1" class="t s0">_______ </span><span id="tw_1" class="t s0">3034948 001 </span><span id="tx_1" class="t s0">___ </span><span id="ty_1" class="t s0">001 1 </span><span id="tz_1" class="t s0">__ </span><span id="t10_1" class="t s0">1 </span><span id="t11_1" class="t s0">/ </span><span id="t12_1" class="t s0">_ </span><span id="t13_1" class="t s0">/ </span>
        <span id="t14_1" class="t s0">30349480010112031 </span>
        <span id="t15_1" class="t s0">Kundennummer: </span><span id="t16_1" class="t s0">Streutermin : </span><span id="t17_1" class="t s0">28260001 </span><span id="t18_1" class="t s0">28260001 </span>
        <span id="t19_1" class="t s0">Auftragsdat.: </span><span id="t1a_1" class="t s0">Young Fashion Behrendt </span><span id="t1b_1" class="t s0">28.09.23 </span>
        <span id="t1c_1" class="t s0">Marke </span><span id="t1d_1" class="t s0">: </span><span id="t1e_1" class="t s0">. </span><span id="t1f_1" class="t s0">50 ***Mc Percy </span>
        <span id="t1g_1" class="t s0">Thema </span><span id="t1h_1" class="t s0">: </span><span id="t1i_1" class="t s0">Holmpassage, Holm 39 </span><span id="t1j_1" class="t s0">KATAGABRUF Katag Abrufe </span>
        <span id="t1k_1" class="t s0">Prospekt </span><span id="t1l_1" class="t s0">: </span>
        <span id="t1m_1" class="t s0">Auftragstyp : </span><span id="t1n_1" class="t s0">D-24937 Flensburg </span><span id="t1o_1" class="t s0">D-24937 Flensburg </span><span id="t1p_1" class="t s0">291 Katag Lagerauftrag Anschlusshaus </span>
        <span id="t1q_1" class="t s0">Verdichtung...: VERSA </span><span id="t1r_1" class="t s0">VERSA </span>
        <span id="t1s_1" class="t s0">Versandart</span><span id="t1t_1" class="t s0">....</span><span id="t1u_1" class="t s0">: 200 Hängend: DKS / Liegend: DPD-unfr. </span><span id="t1v_1" class="t s0">Hängend: DKS / Liegend: DPD-unfr. </span>
        <span id="t1w_1" class="t s0">Kundentermin : </span><span id="t1x_1" class="t s0">Denim Jeans </span><span id="t1y_1" class="t s0">28.09.23 </span><span id="t1z_1" class="t s0">28.09.23 </span>
        <span id="t20_1" class="t s0">Modellnummer: </span><span id="t21_1" class="t s0">Kundenauftrag: </span><span id="t22_1" class="t s0">210000943 </span><span id="t23_1" class="t s0">210000943 </span><span id="t24_1" class="t s0">3034948 </span>
        <span id="t25_1" class="t s0">Lagerplatz </span><span id="t26_1" class="t s0">: </span><span id="t27_1" class="t s0">Art.Nr. Lief.: </span><span id="t28_1" class="t s0">P10 </span><span id="t29_1" class="t s0">700 NOS </span>
        <span id="t2a_1" class="t s0">Bereich: </span><span id="t2b_1" class="t s0">Art.Bez.Lief.: </span><span id="t2c_1" class="t s0">2100 Katag, HAKA I / Hosen </span><span id="t2d_1" class="t s0">605 5 P. Regular </span>
        <span id="t2e_1" class="t s0">================================================================================================================================== </span><span id="t2f_1" class="t s0">================================================================================================================================== </span>
        <span id="t2g_1" class="t s0">A </span><span id="t2h_1" class="t s0">31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 </span>
        <span id="t2i_1" class="t s0">B </span><span id="t2j_1" class="t s0">33/34 34/34 36/34 38/34 40/34 </span>
        <span id="t2k_1" class="t s0">================================================================================================================================== </span><span id="t2l_1" class="t s0">================================================================================================================================== </span>
        <span id="t2m_1" class="t s0">A BLUE STONE </span><span id="t2n_1" class="t s0">1 </span><span id="t2o_1" class="t s0">1 </span><span id="t2p_1" class="t s0">1 </span><span id="t2q_1" class="t s0">1 </span><span id="t2r_1" class="t s0">1 </span><span id="t2s_1" class="t s0">1 </span><span id="t2t_1" class="t s0">1 </span><span id="t2u_1" class="t s0">1 </span><span id="t2v_1" class="t s0">1 </span><span id="t2w_1" class="t s0">1 </span><span id="t2x_1" class="t s0">1 </span><span id="t2y_1" class="t s0">1 </span><span id="t2z_1" class="t s0">1 </span><span id="t30_1" class="t s0">1 </span><span id="t31_1" class="t s0">1 </span>
        <span id="t32_1" class="t s0">600 </span><span id="t33_1" class="t s0">______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ </span>
        <span id="t34_1" class="t s0">B BLUE STONE </span><span id="t35_1" class="t s0">1 </span><span id="t36_1" class="t s0">1 </span><span id="t37_1" class="t s0">1 </span><span id="t38_1" class="t s0">1 </span>
        <span id="t39_1" class="t s0">600 </span><span id="t3a_1" class="t s0">______ ______ ______ ______ </span>
        <span id="t3b_1" class="t s0">Stück gesamt : </span><span id="t3c_1" class="t s0">19 </span><span id="t3d_1" class="t s0">19 STK </span></div>
    <!-- End text definitions -->


</div>
</body>
</html>
"""

result = convert_bottom_to_top(width, height, convertedtext)
print(result)

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta charset="utf-8" />
</head>

<body style="margin: 0;">

<div id="p1" style="overflow: hidden; position: relative; background-color: white; width: 1210px; height: 825px;">

    <!-- Begin shared CSS values -->
    <style class="shared-css" type="text/css" >
        .t {
            transform-origin: bottom left;
            z-index: 2;
            position: absolute;
            white-space: pre;
            overflow: visible;
            line-height: 1.5;
        }
        .text-container {
            white-space: pre;
        }
        @supports (-webkit-touch-callout: none) {
            .text-container {
                white-space: normal;
            }
        }
    </style>
    <!-- End shared CSS values -->


    <!-- Begin inline CSS -->
    <style type="text/css" >

        #t1_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t2_1{left:128px;top:21px;}
        #t3_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t4_1{left:266px;top:21px;letter-spacing:0.15px;}
        #t5_1{left:394px;top:21px;letter-spacing:0.17px;}
        #t6_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t7_1{left:128px;top:21px;}
        #t8_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t9_1{left:266px;top:21px;letter-spacing:0.15px;}
        #ta_1{left:394px;top:21px;letter-spacing:0.16px;}
        #tb_1{left:110px;top:21px;}
        #tc_1{left:156px;top:21px;}
        #td_1{left:101px;top:48px;}
        #te_1{left:697px;top:48px;letter-spacing:0.17px;}
        #tf_1{left:18px;top:48px;letter-spacing:0.17px;}
        #tg_1{left:119px;top:48px;letter-spacing:0.17px;}
        #th_1{left:770px;top:48px;letter-spacing:0.17px;}
        #ti_1{left:770px;top:48px;letter-spacing:0.17px;}
        #tj_1{left:862px;top:48px;}
        #tk_1{left:862px;top:48px;letter-spacing:9.39px;word-spacing:-9.17px;}
        #tl_1{left:889px;top:48px;}
        #tm_1{left:953px;top:48px;letter-spacing:0.17px;}
        #tn_1{left:953px;top:48px;letter-spacing:0.17px;}
        #to_1{left:990px;top:48px;letter-spacing:0.17px;}
        #tp_1{left:770px;top:62px;letter-spacing:0.16px;}
        #tq_1{left:953px;top:62px;letter-spacing:0.11px;}
        #tr_1{left:990px;top:62px;letter-spacing:0.17px;}
        #ts_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tt_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tu_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tv_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tw_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tx_1{left:431px;top:76px;letter-spacing:0.17px;}
        #ty_1{left:431px;top:76px;letter-spacing:3.26px;word-spacing:-3.06px;}
        #tz_1{left:468px;top:76px;letter-spacing:0.17px;}
        #t10_1{left:477px;top:76px;}
        #t11_1{left:422px;top:76px;}
        #t12_1{left:422px;top:76px;}
        #t13_1{left:422px;top:76px;}
        #t14_1{left:788px;top:117px;letter-spacing:0.17px;}
        #t15_1{left:18px;top:131px;letter-spacing:0.15px;}
        #t16_1{left:413px;top:131px;letter-spacing:0.17px;}
        #t17_1{left:165px;top:131px;letter-spacing:0.17px;}
        #t18_1{left:165px;top:131px;letter-spacing:0.15px;}
        #t19_1{left:413px;top:144px;letter-spacing:0.17px;}
        #t1a_1{left:18px;top:144px;letter-spacing:0.17px;}
        #t1b_1{left:541px;top:144px;letter-spacing:0.17px;}
        #t1c_1{left:413px;top:158px;letter-spacing:0.14px;}
        #t1d_1{left:523px;top:158px;}
        #t1e_1{left:18px;top:158px;}
        #t1f_1{left:541px;top:158px;letter-spacing:0.17px;}
        #t1g_1{left:413px;top:172px;letter-spacing:0.14px;}
        #t1h_1{left:523px;top:172px;}
        #t1i_1{left:18px;top:172px;letter-spacing:0.17px;}
        #t1j_1{left:541px;top:172px;letter-spacing:0.17px;}
        #t1k_1{left:413px;top:186px;letter-spacing:0.15px;}
        #t1l_1{left:523px;top:186px;}
        #t1m_1{left:413px;top:199px;letter-spacing:0.17px;}
        #t1n_1{left:18px;top:199px;letter-spacing:0.17px;}
        #t1o_1{left:18px;top:199px;letter-spacing:0.16px;}
        #t1p_1{left:541px;top:199px;letter-spacing:0.17px;}
        #t1q_1{left:18px;top:213px;letter-spacing:0.17px;}
        #t1r_1{left:165px;top:213px;letter-spacing:0.14px;}
        #t1s_1{left:18px;top:227px;letter-spacing:0.17px;}
        #t1t_1{left:110px;top:227px;letter-spacing:0.17px;}
        #t1u_1{left:147px;top:227px;letter-spacing:0.17px;}
        #t1v_1{left:202px;top:227px;letter-spacing:0.16px;}
        #t1w_1{left:633px;top:241px;letter-spacing:0.17px;}
        #t1x_1{left:18px;top:241px;letter-spacing:0.17px;}
        #t1y_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t1z_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t20_1{left:18px;top:254px;letter-spacing:0.15px;}
        #t21_1{left:633px;top:254px;letter-spacing:0.17px;}
        #t22_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t23_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t24_1{left:770px;top:254px;letter-spacing:0.17px;}
        #t25_1{left:18px;top:268px;letter-spacing:0.15px;}
        #t26_1{left:128px;top:268px;}
        #t27_1{left:633px;top:268px;letter-spacing:0.17px;}
        #t28_1{left:147px;top:268px;letter-spacing:0.17px;}
        #t29_1{left:770px;top:268px;letter-spacing:0.17px;}
        #t2a_1{left:18px;top:282px;letter-spacing:0.15px;}
        #t2b_1{left:633px;top:282px;letter-spacing:0.17px;}
        #t2c_1{left:193px;top:282px;letter-spacing:0.17px;}
        #t2d_1{left:770px;top:282px;letter-spacing:0.17px;}
        #t2e_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2f_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2g_1{left:9px;top:337px;}
        #t2h_1{left:183px;top:337px;letter-spacing:1.93px;word-spacing:-1.74px;}
        #t2i_1{left:9px;top:351px;}
        #t2j_1{left:183px;top:351px;letter-spacing:1.72px;word-spacing:-1.53px;}
        #t2k_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2l_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2m_1{left:9px;top:406px;letter-spacing:0.17px;}
        #t2n_1{left:275px;top:406px;}
        #t2o_1{left:339px;top:406px;}
        #t2p_1{left:403px;top:406px;}
        #t2q_1{left:468px;top:406px;}
        #t2r_1{left:532px;top:406px;}
        #t2s_1{left:596px;top:406px;}
        #t2t_1{left:660px;top:406px;}
        #t2u_1{left:724px;top:406px;}
        #t2v_1{left:788px;top:406px;}
        #t2w_1{left:853px;top:406px;}
        #t2x_1{left:917px;top:406px;}
        #t2y_1{left:981px;top:406px;}
        #t2z_1{left:1045px;top:406px;}
        #t30_1{left:1109px;top:406px;}
        #t31_1{left:1173px;top:406px;}
        #t32_1{left:28px;top:419px;letter-spacing:0.17px;}
        #t33_1{left:238px;top:419px;letter-spacing:0.17px;}
        #t34_1{left:9px;top:433px;letter-spacing:0.17px;}
        #t35_1{left:211px;top:433px;}
        #t36_1{left:275px;top:433px;}
        #t37_1{left:339px;top:433px;}
        #t38_1{left:403px;top:433px;}
        #t39_1{left:28px;top:447px;letter-spacing:0.17px;}
        #t3a_1{left:174px;top:447px;letter-spacing:0.17px;}
        #t3b_1{left:816px;top:461px;letter-spacing:0.17px;}
        #t3c_1{left:1027px;top:461px;letter-spacing:0.17px;}
        #t3d_1{left:1027px;top:461px;letter-spacing:0.19px;word-spacing:9.17px;}

        .s0{font-size:15px;font-family:Courier;color:#000;}
    </style>
    <!-- End inline CSS -->

    <!-- Begin page background -->
    <div id="pg1Overlay" style="width:100%; height:100%; position:absolute; z-index:1; background-color:rgba(0,0,0,0); -webkit-user-select: none;"></div>
    <div id="pg1" style="-webkit-user-select: none;"><object width="1210" height="825" data="1/1.svg" type="image/svg+xml" id="pdf1" style="width:1210px; height:825px; -moz-transform:scale(1); z-index: 0;"></object></div>
    <!-- End page background -->


    <!-- Begin text definitions (Positioned/styled in CSS) -->
    <div class="text-container"><span id="t1_1" class="t s0">Seite: </span><span id="t2_1" class="t s0">( </span><span id="t3_1" class="t s0">) *Kopie* </span><span id="t4_1" class="t s0">LIEFERSCHEIN </span><span id="t5_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="t6_1" class="t s0">Seite: </span><span id="t7_1" class="t s0">( </span><span id="t8_1" class="t s0">) *Kopie* </span><span id="t9_1" class="t s0">LIEFERSCHEIN </span><span id="ta_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="tb_1" class="t s0">1 </span><span id="tc_1" class="t s0">1 </span>
        <span id="td_1" class="t s0">/ </span><span id="te_1" class="t s0">Nummer: </span><span id="tf_1" class="t s0">28.09.23 </span><span id="tg_1" class="t s0">15:22 </span><span id="th_1" class="t s0">3034948 </span><span id="ti_1" class="t s0">3034948 </span><span id="tj_1" class="t s0">1 </span><span id="tk_1" class="t s0">1 1 </span><span id="tl_1" class="t s0">1 </span><span id="tm_1" class="t s0">120 </span><span id="tn_1" class="t s0">120 31 </span><span id="to_1" class="t s0">31 </span>
        <span id="tp_1" class="t s0">Auftrag Ind SF </span><span id="tq_1" class="t s0">LO </span><span id="tr_1" class="t s0">Bt </span>
        <span id="ts_1" class="t s0">Liefernr. </span><span id="tt_1" class="t s0">_________ </span><span id="tu_1" class="t s0">Liefernr. 3034948 </span><span id="tv_1" class="t s0">_______ </span><span id="tw_1" class="t s0">3034948 001 </span><span id="tx_1" class="t s0">___ </span><span id="ty_1" class="t s0">001 1 </span><span id="tz_1" class="t s0">__ </span><span id="t10_1" class="t s0">1 </span><span id="t11_1" class="t s0">/ </span><span id="t12_1" class="t s0">_ </span><span id="t13_1" class="t s0">/ </span>
        <span id="t14_1" class="t s0">30349480010112031 </span>
        <span id="t15_1" class="t s0">Kundennummer: </span><span id="t16_1" class="t s0">Streutermin : </span><span id="t17_1" class="t s0">28260001 </span><span id="t18_1" class="t s0">28260001 </span>
        <span id="t19_1" class="t s0">Auftragsdat.: </span><span id="t1a_1" class="t s0">Young Fashion Behrendt </span><span id="t1b_1" class="t s0">28.09.23 </span>
        <span id="t1c_1" class="t s0">Marke </span><span id="t1d_1" class="t s0">: </span><span id="t1e_1" class="t s0">. </span><span id="t1f_1" class="t s0">50 ***Mc Percy </span>
        <span id="t1g_1" class="t s0">Thema </span><span id="t1h_1" class="t s0">: </span><span id="t1i_1" class="t s0">Holmpassage, Holm 39 </span><span id="t1j_1" class="t s0">KATAGABRUF Katag Abrufe </span>
        <span id="t1k_1" class="t s0">Prospekt </span><span id="t1l_1" class="t s0">: </span>
        <span id="t1m_1" class="t s0">Auftragstyp : </span><span id="t1n_1" class="t s0">D-24937 Flensburg </span><span id="t1o_1" class="t s0">D-24937 Flensburg </span><span id="t1p_1" class="t s0">291 Katag Lagerauftrag Anschlusshaus </span>
        <span id="t1q_1" class="t s0">Verdichtung...: VERSA </span><span id="t1r_1" class="t s0">VERSA </span>
        <span id="t1s_1" class="t s0">Versandart</span><span id="t1t_1" class="t s0">....</span><span id="t1u_1" class="t s0">: 200 Hängend: DKS / Liegend: DPD-unfr. </span><span id="t1v_1" class="t s0">Hängend: DKS / Liegend: DPD-unfr. </span>
        <span id="t1w_1" class="t s0">Kundentermin : </span><span id="t1x_1" class="t s0">Denim Jeans </span><span id="t1y_1" class="t s0">28.09.23 </span><span id="t1z_1" class="t s0">28.09.23 </span>
        <span id="t20_1" class="t s0">Modellnummer: </span><span id="t21_1" class="t s0">Kundenauftrag: </span><span id="t22_1" class="t s0">210000943 </span><span id="t23_1" class="t s0">210000943 </span><span id="t24_1" class="t s0">3034948 </span>
        <span id="t25_1" class="t s0">Lagerplatz </span><span id="t26_1" class="t s0">: </span><span id="t27_1" class="t s0">Art.Nr. Lief.: </span><span id="t28_1" class="t s0">P10 </span><span id="t29_1" class="t s0">700 NOS </span>
        <span id="t2a_1" class="t s0">Bereich: </span><span id="t2b_1" class="t s0">Art.Bez.Lief.: </span><span id="t2c_1" class="t s0">2100 Katag, HAKA I / Hosen </span><span id="t2d_1" class="t s0">605 5 P. Regular </span>
        <span id="t2e_1" class="t s0">================================================================================================================================== </span><span id="t2f_1" class="t s0">================================================================================================================================== </span>
        <span id="t2g_1" class="t s0">A </span><span id="t2h_1" class="t s0">31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 </span>
        <span id="t2i_1" class="t s0">B </span><span id="t2j_1" class="t s0">33/34 34/34 36/34 38/34 40/34 </span>
        <span id="t2k_1" class="t s0">================================================================================================================================== </span><span id="t2l_1" class="t s0">================================================================================================================================== </span>
        <span id="t2m_1" class="t s0">A BLUE STONE </span><span id="t2n_1" class="t s0">1 </span><span id="t2o_1" class="t s0">1 </span><span id="t2p_1" class="t s0">1 </span><span id="t2q_1" class="t s0">1 </span><span id="t2r_1" class="t s0">1 </span><span id="t2s_1" class="t s0">1 </span><span id="t2t_1" class="t s0">1 </span><span id="t2u_1" class="t s0">1 </span><span id="t2v_1" class="t s0">1 </span><span id="t2w_1" class="t s0">1 </span><span id="t2x_1" class="t s0">1 </span><span id="t2y_1" class="t s0">1 </span><span id="t2z_1" class="t s0">1 </span><span id="t30_1" class="t s0">1 </span><span id="t31_1" class="t s0">1 </span>
        <span id="t32_1" class="t s0">600 </span><span id="t33_1" class="t s0">______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ </span>
        <span id="t34_1" class="t s0">B BLUE STONE </span><span id="t35_1" class="t s0">1 </span><span id="t36_1" class="t s0">1 </span><span id="t37_1" class="t s0">1 </span><span id="t38_1" class="t s0">1 </span>
        <span id="t39_1" class="t s0">600 </span><span id="t3a_1" class="t s0">______ ______ ______ ______ </span>
        <span id="t3b_1" class="t s0">Stück gesamt : </span><span id="t3c_1" class="t s0">19 </span><span id="t3d_1" class="t s0">19 STK </span></div>
    <!-- End text definitions -->


</div>
</body>
</html>

# Convert HTML <span> to Jesper Report <text> Elements

In [ ]:
from bs4 import BeautifulSoup
import re

def generate_jasper_textfields_from_html_multi_style(converthtml: str) -> str:
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(converthtml, 'html.parser')

    # Extract all styles from all style tags
    styles = {}
    for style_content in soup.select('style'):
        if style_content.string:  # Check if style content is not None
            for style_definition in style_content.string.split('}'):
                if '{' in style_definition:
                    parts = style_definition.split('{')
                    if len(parts) == 2:
                        selector, properties = parts
                        selector = selector.strip()
                        properties = properties.strip()
                        styles[selector] = properties

    # Process each span to extract the text and associated styles
    jasper_textfields = ""
    for span in soup.select('span.t'):
        span_id = span.attrs.get('id', '')
        span_text = span.string
        span_class = " ".join(span.attrs.get('class', []))

        # Extract style associated with this span using its id
        style_definition = styles.get(f"#{span_id}", '')
        x_match = re.search(r'left:(\d+)px', style_definition)
        y_match = re.search(r'top:(\d+)px', style_definition)
        x_pos = x_match.group(1) if x_match else print(x_match.group(1))
        y_pos = y_match.group(1) if y_match else print(y_match.group(1))

        # Generate the JasperReport XML for this text span
        jasper_textfields += f"""
            <textField>
                <reportElement style="{span_class}" x="{x_pos}" y="{y_pos}" width="{10 * len(span_text)}" height="30" />
                <textFieldExpression><![CDATA["{span_text}"]]></textFieldExpression>
            </textField>
        """

    return jasper_textfields

htmlToConvert = """<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta charset="utf-8" />
</head>

<body style="margin: 0;">

<div id="p1" style="overflow: hidden; position: relative; background-color: white; width: 1210px; height: 825px;">

    <!-- Begin shared CSS values -->
    <style class="shared-css" type="text/css" >
        .t {
            transform-origin: bottom left;
            z-index: 2;
            position: absolute;
            white-space: pre;
            overflow: visible;
            line-height: 1.5;
        }
        .text-container {
            white-space: pre;
        }
        @supports (-webkit-touch-callout: none) {
            .text-container {
                white-space: normal;
            }
        }
    </style>
    <!-- End shared CSS values -->


    <!-- Begin inline CSS -->
    <style type="text/css" >

        #t1_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t2_1{left:128px;top:21px;}
        #t3_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t4_1{left:266px;top:21px;letter-spacing:0.15px;}
        #t5_1{left:394px;top:21px;letter-spacing:0.17px;}
        #t6_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t7_1{left:128px;top:21px;}
        #t8_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t9_1{left:266px;top:21px;letter-spacing:0.15px;}
        #ta_1{left:394px;top:21px;letter-spacing:0.16px;}
        #tb_1{left:110px;top:21px;}
        #tc_1{left:156px;top:21px;}
        #td_1{left:101px;top:48px;}
        #te_1{left:697px;top:48px;letter-spacing:0.17px;}
        #tf_1{left:18px;top:48px;letter-spacing:0.17px;}
        #tg_1{left:119px;top:48px;letter-spacing:0.17px;}
        #th_1{left:770px;top:48px;letter-spacing:0.17px;}
        #ti_1{left:770px;top:48px;letter-spacing:0.17px;}
        #tj_1{left:862px;top:48px;}
        #tk_1{left:862px;top:48px;letter-spacing:9.39px;word-spacing:-9.17px;}
        #tl_1{left:889px;top:48px;}
        #tm_1{left:953px;top:48px;letter-spacing:0.17px;}
        #tn_1{left:953px;top:48px;letter-spacing:0.17px;}
        #to_1{left:990px;top:48px;letter-spacing:0.17px;}
        #tp_1{left:770px;top:62px;letter-spacing:0.16px;}
        #tq_1{left:953px;top:62px;letter-spacing:0.11px;}
        #tr_1{left:990px;top:62px;letter-spacing:0.17px;}
        #ts_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tt_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tu_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tv_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tw_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tx_1{left:431px;top:76px;letter-spacing:0.17px;}
        #ty_1{left:431px;top:76px;letter-spacing:3.26px;word-spacing:-3.06px;}
        #tz_1{left:468px;top:76px;letter-spacing:0.17px;}
        #t10_1{left:477px;top:76px;}
        #t11_1{left:422px;top:76px;}
        #t12_1{left:422px;top:76px;}
        #t13_1{left:422px;top:76px;}
        #t14_1{left:788px;top:117px;letter-spacing:0.17px;}
        #t15_1{left:18px;top:131px;letter-spacing:0.15px;}
        #t16_1{left:413px;top:131px;letter-spacing:0.17px;}
        #t17_1{left:165px;top:131px;letter-spacing:0.17px;}
        #t18_1{left:165px;top:131px;letter-spacing:0.15px;}
        #t19_1{left:413px;top:144px;letter-spacing:0.17px;}
        #t1a_1{left:18px;top:144px;letter-spacing:0.17px;}
        #t1b_1{left:541px;top:144px;letter-spacing:0.17px;}
        #t1c_1{left:413px;top:158px;letter-spacing:0.14px;}
        #t1d_1{left:523px;top:158px;}
        #t1e_1{left:18px;top:158px;}
        #t1f_1{left:541px;top:158px;letter-spacing:0.17px;}
        #t1g_1{left:413px;top:172px;letter-spacing:0.14px;}
        #t1h_1{left:523px;top:172px;}
        #t1i_1{left:18px;top:172px;letter-spacing:0.17px;}
        #t1j_1{left:541px;top:172px;letter-spacing:0.17px;}
        #t1k_1{left:413px;top:186px;letter-spacing:0.15px;}
        #t1l_1{left:523px;top:186px;}
        #t1m_1{left:413px;top:199px;letter-spacing:0.17px;}
        #t1n_1{left:18px;top:199px;letter-spacing:0.17px;}
        #t1o_1{left:18px;top:199px;letter-spacing:0.16px;}
        #t1p_1{left:541px;top:199px;letter-spacing:0.17px;}
        #t1q_1{left:18px;top:213px;letter-spacing:0.17px;}
        #t1r_1{left:165px;top:213px;letter-spacing:0.14px;}
        #t1s_1{left:18px;top:227px;letter-spacing:0.17px;}
        #t1t_1{left:110px;top:227px;letter-spacing:0.17px;}
        #t1u_1{left:147px;top:227px;letter-spacing:0.17px;}
        #t1v_1{left:202px;top:227px;letter-spacing:0.16px;}
        #t1w_1{left:633px;top:241px;letter-spacing:0.17px;}
        #t1x_1{left:18px;top:241px;letter-spacing:0.17px;}
        #t1y_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t1z_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t20_1{left:18px;top:254px;letter-spacing:0.15px;}
        #t21_1{left:633px;top:254px;letter-spacing:0.17px;}
        #t22_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t23_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t24_1{left:770px;top:254px;letter-spacing:0.17px;}
        #t25_1{left:18px;top:268px;letter-spacing:0.15px;}
        #t26_1{left:128px;top:268px;}
        #t27_1{left:633px;top:268px;letter-spacing:0.17px;}
        #t28_1{left:147px;top:268px;letter-spacing:0.17px;}
        #t29_1{left:770px;top:268px;letter-spacing:0.17px;}
        #t2a_1{left:18px;top:282px;letter-spacing:0.15px;}
        #t2b_1{left:633px;top:282px;letter-spacing:0.17px;}
        #t2c_1{left:193px;top:282px;letter-spacing:0.17px;}
        #t2d_1{left:770px;top:282px;letter-spacing:0.17px;}
        #t2e_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2f_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2g_1{left:9px;top:337px;}
        #t2h_1{left:183px;top:337px;letter-spacing:1.93px;word-spacing:-1.74px;}
        #t2i_1{left:9px;top:351px;}
        #t2j_1{left:183px;top:351px;letter-spacing:1.72px;word-spacing:-1.53px;}
        #t2k_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2l_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2m_1{left:9px;top:406px;letter-spacing:0.17px;}
        #t2n_1{left:275px;top:406px;}
        #t2o_1{left:339px;top:406px;}
        #t2p_1{left:403px;top:406px;}
        #t2q_1{left:468px;top:406px;}
        #t2r_1{left:532px;top:406px;}
        #t2s_1{left:596px;top:406px;}
        #t2t_1{left:660px;top:406px;}
        #t2u_1{left:724px;top:406px;}
        #t2v_1{left:788px;top:406px;}
        #t2w_1{left:853px;top:406px;}
        #t2x_1{left:917px;top:406px;}
        #t2y_1{left:981px;top:406px;}
        #t2z_1{left:1045px;top:406px;}
        #t30_1{left:1109px;top:406px;}
        #t31_1{left:1173px;top:406px;}
        #t32_1{left:28px;top:419px;letter-spacing:0.17px;}
        #t33_1{left:238px;top:419px;letter-spacing:0.17px;}
        #t34_1{left:9px;top:433px;letter-spacing:0.17px;}
        #t35_1{left:211px;top:433px;}
        #t36_1{left:275px;top:433px;}
        #t37_1{left:339px;top:433px;}
        #t38_1{left:403px;top:433px;}
        #t39_1{left:28px;top:447px;letter-spacing:0.17px;}
        #t3a_1{left:174px;top:447px;letter-spacing:0.17px;}
        #t3b_1{left:816px;top:461px;letter-spacing:0.17px;}
        #t3c_1{left:1027px;top:461px;letter-spacing:0.17px;}
        #t3d_1{left:1027px;top:461px;letter-spacing:0.19px;word-spacing:9.17px;}

        .s0{font-size:15px;font-family:Courier;color:#000;}
    </style>
    <!-- End inline CSS -->

    <!-- Begin page background -->
    <div id="pg1Overlay" style="width:100%; height:100%; position:absolute; z-index:1; background-color:rgba(0,0,0,0); -webkit-user-select: none;"></div>
    <div id="pg1" style="-webkit-user-select: none;"><object width="1210" height="825" data="1/1.svg" type="image/svg+xml" id="pdf1" style="width:1210px; height:825px; -moz-transform:scale(1); z-index: 0;"></object></div>
    <!-- End page background -->


    <!-- Begin text definitions (Positioned/styled in CSS) -->
    <div class="text-container"><span id="t1_1" class="t s0">Seite: </span><span id="t2_1" class="t s0">( </span><span id="t3_1" class="t s0">) *Kopie* </span><span id="t4_1" class="t s0">LIEFERSCHEIN </span><span id="t5_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="t6_1" class="t s0">Seite: </span><span id="t7_1" class="t s0">( </span><span id="t8_1" class="t s0">) *Kopie* </span><span id="t9_1" class="t s0">LIEFERSCHEIN </span><span id="ta_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="tb_1" class="t s0">1 </span><span id="tc_1" class="t s0">1 </span>
        <span id="td_1" class="t s0">/ </span><span id="te_1" class="t s0">Nummer: </span><span id="tf_1" class="t s0">28.09.23 </span><span id="tg_1" class="t s0">15:22 </span><span id="th_1" class="t s0">3034948 </span><span id="ti_1" class="t s0">3034948 </span><span id="tj_1" class="t s0">1 </span><span id="tk_1" class="t s0">1 1 </span><span id="tl_1" class="t s0">1 </span><span id="tm_1" class="t s0">120 </span><span id="tn_1" class="t s0">120 31 </span><span id="to_1" class="t s0">31 </span>
        <span id="tp_1" class="t s0">Auftrag Ind SF </span><span id="tq_1" class="t s0">LO </span><span id="tr_1" class="t s0">Bt </span>
        <span id="ts_1" class="t s0">Liefernr. </span><span id="tt_1" class="t s0">_________ </span><span id="tu_1" class="t s0">Liefernr. 3034948 </span><span id="tv_1" class="t s0">_______ </span><span id="tw_1" class="t s0">3034948 001 </span><span id="tx_1" class="t s0">___ </span><span id="ty_1" class="t s0">001 1 </span><span id="tz_1" class="t s0">__ </span><span id="t10_1" class="t s0">1 </span><span id="t11_1" class="t s0">/ </span><span id="t12_1" class="t s0">_ </span><span id="t13_1" class="t s0">/ </span>
        <span id="t14_1" class="t s0">30349480010112031 </span>
        <span id="t15_1" class="t s0">Kundennummer: </span><span id="t16_1" class="t s0">Streutermin : </span><span id="t17_1" class="t s0">28260001 </span><span id="t18_1" class="t s0">28260001 </span>
        <span id="t19_1" class="t s0">Auftragsdat.: </span><span id="t1a_1" class="t s0">Young Fashion Behrendt </span><span id="t1b_1" class="t s0">28.09.23 </span>
        <span id="t1c_1" class="t s0">Marke </span><span id="t1d_1" class="t s0">: </span><span id="t1e_1" class="t s0">. </span><span id="t1f_1" class="t s0">50 ***Mc Percy </span>
        <span id="t1g_1" class="t s0">Thema </span><span id="t1h_1" class="t s0">: </span><span id="t1i_1" class="t s0">Holmpassage, Holm 39 </span><span id="t1j_1" class="t s0">KATAGABRUF Katag Abrufe </span>
        <span id="t1k_1" class="t s0">Prospekt </span><span id="t1l_1" class="t s0">: </span>
        <span id="t1m_1" class="t s0">Auftragstyp : </span><span id="t1n_1" class="t s0">D-24937 Flensburg </span><span id="t1o_1" class="t s0">D-24937 Flensburg </span><span id="t1p_1" class="t s0">291 Katag Lagerauftrag Anschlusshaus </span>
        <span id="t1q_1" class="t s0">Verdichtung...: VERSA </span><span id="t1r_1" class="t s0">VERSA </span>
        <span id="t1s_1" class="t s0">Versandart</span><span id="t1t_1" class="t s0">....</span><span id="t1u_1" class="t s0">: 200 Hängend: DKS / Liegend: DPD-unfr. </span><span id="t1v_1" class="t s0">Hängend: DKS / Liegend: DPD-unfr. </span>
        <span id="t1w_1" class="t s0">Kundentermin : </span><span id="t1x_1" class="t s0">Denim Jeans </span><span id="t1y_1" class="t s0">28.09.23 </span><span id="t1z_1" class="t s0">28.09.23 </span>
        <span id="t20_1" class="t s0">Modellnummer: </span><span id="t21_1" class="t s0">Kundenauftrag: </span><span id="t22_1" class="t s0">210000943 </span><span id="t23_1" class="t s0">210000943 </span><span id="t24_1" class="t s0">3034948 </span>
        <span id="t25_1" class="t s0">Lagerplatz </span><span id="t26_1" class="t s0">: </span><span id="t27_1" class="t s0">Art.Nr. Lief.: </span><span id="t28_1" class="t s0">P10 </span><span id="t29_1" class="t s0">700 NOS </span>
        <span id="t2a_1" class="t s0">Bereich: </span><span id="t2b_1" class="t s0">Art.Bez.Lief.: </span><span id="t2c_1" class="t s0">2100 Katag, HAKA I / Hosen </span><span id="t2d_1" class="t s0">605 5 P. Regular </span>
        <span id="t2e_1" class="t s0">================================================================================================================================== </span><span id="t2f_1" class="t s0">================================================================================================================================== </span>
        <span id="t2g_1" class="t s0">A </span><span id="t2h_1" class="t s0">31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 </span>
        <span id="t2i_1" class="t s0">B </span><span id="t2j_1" class="t s0">33/34 34/34 36/34 38/34 40/34 </span>
        <span id="t2k_1" class="t s0">================================================================================================================================== </span><span id="t2l_1" class="t s0">================================================================================================================================== </span>
        <span id="t2m_1" class="t s0">A BLUE STONE </span><span id="t2n_1" class="t s0">1 </span><span id="t2o_1" class="t s0">1 </span><span id="t2p_1" class="t s0">1 </span><span id="t2q_1" class="t s0">1 </span><span id="t2r_1" class="t s0">1 </span><span id="t2s_1" class="t s0">1 </span><span id="t2t_1" class="t s0">1 </span><span id="t2u_1" class="t s0">1 </span><span id="t2v_1" class="t s0">1 </span><span id="t2w_1" class="t s0">1 </span><span id="t2x_1" class="t s0">1 </span><span id="t2y_1" class="t s0">1 </span><span id="t2z_1" class="t s0">1 </span><span id="t30_1" class="t s0">1 </span><span id="t31_1" class="t s0">1 </span>
        <span id="t32_1" class="t s0">600 </span><span id="t33_1" class="t s0">______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ </span>
        <span id="t34_1" class="t s0">B BLUE STONE </span><span id="t35_1" class="t s0">1 </span><span id="t36_1" class="t s0">1 </span><span id="t37_1" class="t s0">1 </span><span id="t38_1" class="t s0">1 </span>
        <span id="t39_1" class="t s0">600 </span><span id="t3a_1" class="t s0">______ ______ ______ ______ </span>
        <span id="t3b_1" class="t s0">Stück gesamt : </span><span id="t3c_1" class="t s0">19 </span><span id="t3d_1" class="t s0">19 STK </span></div>
    <!-- End text definitions -->


</div>
</body>
</html>

"""
print(generate_jasper_textfields_from_html_multi_style(htmlToConvert))

            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="110" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="156" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="101" y="48" width="20" height="30" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="697" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="48" width="90" height="30" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="119" y="48" width="60" height="30" />
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="862" y="48" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="862" y="48" width="40" height="30" />
                <textFieldExpression><![CDATA["1 1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="889" y="48" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="953" y="48" width="40" height="30" />
                <textFieldExpression><![CDATA["120 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="953" y="48" width="70" height="30" />
                <textFieldExpression><![CDATA["120 31 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="990" y="48" width="30" height="30" />
                <textFieldExpression><![CDATA["31 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="62" width="150" height="30" />
                <textFieldExpression><![CDATA["Auftrag Ind SF "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="953" y="62" width="30" height="30" />
                <textFieldExpression><![CDATA["LO "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="990" y="62" width="30" height="30" />
                <textFieldExpression><![CDATA["Bt "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="76" width="100" height="30" />
                <textFieldExpression><![CDATA["Liefernr. "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="76" width="100" height="30" />
                <textFieldExpression><![CDATA["_________ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="76" width="180" height="30" />
                <textFieldExpression><![CDATA["Liefernr. 3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="358" y="76" width="80" height="30" />
                <textFieldExpression><![CDATA["_______ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="358" y="76" width="120" height="30" />
                <textFieldExpression><![CDATA["3034948 001 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="431" y="76" width="40" height="30" />
                <textFieldExpression><![CDATA["___ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="431" y="76" width="60" height="30" />
                <textFieldExpression><![CDATA["001 1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="468" y="76" width="30" height="30" />
                <textFieldExpression><![CDATA["__ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="477" y="76" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30" />
                <textFieldExpression><![CDATA["_ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="788" y="117" width="180" height="30" />
                <textFieldExpression><![CDATA["30349480010112031 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="131" width="140" height="30" />
                <textFieldExpression><![CDATA["Kundennummer: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="131" width="140" height="30" />
                <textFieldExpression><![CDATA["Streutermin : "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="131" width="90" height="30" />
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="131" width="90" height="30" />
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="144" width="140" height="30" />
                <textFieldExpression><![CDATA["Auftragsdat.: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="144" width="230" height="30" />
                <textFieldExpression><![CDATA["Young Fashion Behrendt "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="541" y="144" width="90" height="30" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="158" width="60" height="30" />
                <textFieldExpression><![CDATA["Marke "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="523" y="158" width="20" height="30" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="158" width="20" height="30" />
                <textFieldExpression><![CDATA[". "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="541" y="158" width="150" height="30" />
                <textFieldExpression><![CDATA["50 ***Mc Percy "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="172" width="60" height="30" />
                <textFieldExpression><![CDATA["Thema "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="523" y="172" width="20" height="30" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="172" width="210" height="30" />
                <textFieldExpression><![CDATA["Holmpassage, Holm 39 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="541" y="172" width="240" height="30" />
                <textFieldExpression><![CDATA["KATAGABRUF Katag Abrufe "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="186" width="90" height="30" />
                <textFieldExpression><![CDATA["Prospekt "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="523" y="186" width="20" height="30" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="413" y="199" width="140" height="30" />
                <textFieldExpression><![CDATA["Auftragstyp : "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="199" width="180" height="30" />
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="199" width="180" height="30" />
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="541" y="199" width="370" height="30" />
                <textFieldExpression><![CDATA["291 Katag Lagerauftrag Anschlusshaus "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="213" width="220" height="30" />
                <textFieldExpression><![CDATA["Verdichtung...: VERSA "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="213" width="60" height="30" />
                <textFieldExpression><![CDATA["VERSA "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="227" width="100" height="30" />
                <textFieldExpression><![CDATA["Versandart"]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="110" y="227" width="40" height="30" />
                <textFieldExpression><![CDATA["...."]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="147" y="227" width="400" height="30" />
                <textFieldExpression><![CDATA[": 200 Hängend: DKS / Liegend: DPD-unfr. "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="202" y="227" width="340" height="30" />
                <textFieldExpression><![CDATA["Hängend: DKS / Liegend: DPD-unfr. "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="633" y="241" width="150" height="30" />
                <textFieldExpression><![CDATA["Kundentermin : "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="241" width="120" height="30" />
                <textFieldExpression><![CDATA["Denim Jeans "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="241" width="90" height="30" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="241" width="90" height="30" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="254" width="140" height="30" />
                <textFieldExpression><![CDATA["Modellnummer: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="633" y="254" width="150" height="30" />
                <textFieldExpression><![CDATA["Kundenauftrag: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="147" y="254" width="100" height="30" />
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="147" y="254" width="100" height="30" />
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="254" width="80" height="30" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="268" width="110" height="30" />
                <textFieldExpression><![CDATA["Lagerplatz "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="128" y="268" width="20" height="30" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="633" y="268" width="150" height="30" />
                <textFieldExpression><![CDATA["Art.Nr. Lief.: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="147" y="268" width="40" height="30" />
                <textFieldExpression><![CDATA["P10 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="268" width="80" height="30" />
                <textFieldExpression><![CDATA["700 NOS "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="282" width="90" height="30" />
                <textFieldExpression><![CDATA["Bereich: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="633" y="282" width="150" height="30" />
                <textFieldExpression><![CDATA["Art.Bez.Lief.: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="193" y="282" width="270" height="30" />
                <textFieldExpression><![CDATA["2100 Katag, HAKA I / Hosen "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="282" width="170" height="30" />
                <textFieldExpression><![CDATA["605 5 P. Regular "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="9" y="323" width="1310" height="30" />
                <textFieldExpression><![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="9" y="323" width="1310" height="30" />
                <textFieldExpression><![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="9" y="337" width="20" height="30" />
                <textFieldExpression><![CDATA["A "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="183" y="337" width="960" height="30" />
                <textFieldExpression><![CDATA["31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 "]]></textFieldExpression>
            </textField>

            <textField>

# Convert HTML FONT to Jesper syle font

In [ ]:
import re

def extract_jasper_styles_from_html_styles(html_styles: str) -> str:
    # Regular expression patterns for extracting font family and font size
    font_family_pattern = re.compile(r'font-family:([^;]+)')
    font_size_pattern = re.compile(r'font-size:(\d+)px')

    jasper_styles = ""

    # Split the styles by "}" to get individual style definitions
    for style_definition in html_styles.split('}'):
        # Check if style definition is not empty
        if style_definition.strip():
            # Extract class name (e.g., s0, s1, etc.)
            class_name = style_definition.split('{')[0].strip().replace('.', '')

            # Extract font family and font size
            font_family = font_family_pattern.search(style_definition)
            font_size = font_size_pattern.search(style_definition)

            if font_family and font_size:
                jasper_styles += f'<style name="t {class_name}" fontName="{font_family.group(1).strip()}" fontSize="{font_size.group(1)}"/>\n'

    return jasper_styles

html_styles_input=""".s0{font-size:15px;font-family:Courier;color:#000;}
"""
# Test
jasper_styles_output = extract_jasper_styles_from_html_styles(html_styles_input)
print(jasper_styles_output)

<style name="t s0" fontName="Courier" fontSize="15"/>

#Sort By Y Koordinate

In [ ]:
import xml.etree.ElementTree as ET

# Re-defining the improved function
def sort_textfields_by_y_etree_v3(xml_content: str) -> str:
    # Placeholder for CDATA
    placeholder = "PLACEHOLDER_FOR_CDATA"

    # Convert CDATA sections to placeholder
    xml_content = xml_content.replace("<![CDATA[", placeholder + "[")
    xml_content = xml_content.replace("]]>", "]" + placeholder)

    # Define namespace
    ns = {'jr': 'http://jasperreports.sourceforge.net/jasperreports'}
    ET.register_namespace('', ns['jr'])

    # Parse the XML content with the namespace
    root = ET.fromstring(xml_content)

    # For each parent in the XML
    for parent in root.findall(".//*"):
        # Extract textField elements and their y coordinates
        textfields = [(elem, int(elem.find(".//jr:reportElement", ns).attrib['y']))
                      for elem in parent.findall("jr:textField", ns)]

        # If there are no textFields, continue to the next parent
        if not textfields:
            continue

        # Sort the textFields based on y coordinate
        textfields.sort(key=lambda x: x[1])

        # Remove the original textFields from parent
        for tf, _ in textfields:
            parent.remove(tf)

        # Add sorted textField elements back to parent
        for tf, _ in textfields:
            parent.append(tf)

    # Convert the root element back to string and restore CDATA sections
    output = ET.tostring(root, encoding='unicode')
    output = output.replace(placeholder + "[", "<![CDATA[")
    output = output.replace("]" + placeholder, "]]>")

    return output




test_data="""<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.20.6.final using JasperReports Library version 6.20.6-5c96b6aa8a39ac1dc6b6bea4b81168e16dd39231  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
              name="Blank_A4_Landscape_1" pageWidth="842" pageHeight="595" orientation="Landscape" columnWidth="802"
              leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20"
              uuid="5257a660-2fb9-4b86-a461-988c272a56b2">
    <style name="t s0" fontName="Courier" fontSize="10"/>
    <queryString>
        <![CDATA[]]>
    </queryString>
    <background>
        <band splitType="Stretch"/>
    </background>
    <title>
        <band height="370" splitType="Stretch">
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30"
                               uuid="d5c3fdc3-c70e-4f53-beca-0fc574367d2c"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30"
                               uuid="8c8fa432-7b6f-4b50-ac53-636aa149182c"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30"
                               uuid="ada4bef8-9ee6-4385-a209-a69527e035cd"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30"
                               uuid="5529a32d-8219-427a-b3e1-4c311cbd42ae"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30"
                               uuid="931130b9-140a-4803-8ecd-5b5c78a61f2f"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30"
                               uuid="380626e2-1842-4a2f-854e-b2e3d4654210"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30"
                               uuid="b9710825-801c-4232-aad3-93df902904c5"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30"
                               uuid="f2c75650-e46a-4470-8d3b-19cf04663732"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30"
                               uuid="e129e798-ec34-4a9e-9227-2b6c2ff713f2"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30"
                               uuid="2bc4a69c-761b-4140-bd2a-a36ab4624da3"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="15" width="14" height="30"
                               uuid="674d2a95-641a-4d70-87c1-1af2e6361b18"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="109" y="15" width="14" height="30"
                               uuid="dad8e3ca-1ada-4c0a-be11-f2529292dc0c"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="70" y="35" width="14" height="30"
                               uuid="4c299d51-1e81-4207-b66e-27ed1d53398e"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="485" y="35" width="56" height="30"
                               uuid="2df0b13b-ec14-4454-a796-5ff755ebd910"/>
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="35" width="63" height="30"
                               uuid="4e7ad477-f4f4-4643-b954-76d0b3416c8e"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="83" y="35" width="42" height="30"
                               uuid="0da17093-15d4-4d16-97b0-b213a26df606"/>
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="56" height="30"
                               uuid="1ae78e77-9be2-461d-a151-c0c490a0a2bb"/>
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="63" height="30"
                               uuid="920be72f-23a9-4eb8-ba18-c3e7e4f1b1ae"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="14" height="30"
                               uuid="1ecd4211-71b0-44ce-abc2-622b253e675d"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="28" height="30"
                               uuid="c9997927-b754-494a-93a6-70b8a9499fe3"/>
                <textFieldExpression><![CDATA["1"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="619" y="35" width="14" height="30"
                               uuid="f37d057b-726a-46fd-8f2c-4457e06481ad"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="28" height="30"
                               uuid="0e2deb51-35d6-4b71-b894-8aab86ee1cac"/>
                <textFieldExpression><![CDATA["120 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="49" height="30"
                               uuid="075b7bb7-f71f-4af9-ac76-497e269d4614"/>
                <textFieldExpression><![CDATA["120"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="35" width="21" height="30"
                               uuid="92ef6690-0e69-4f61-babc-90ca8d352f97"/>
                <textFieldExpression><![CDATA["31"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="45" width="104" height="30"
                               uuid="ee17a1ce-a8c6-47e0-be59-5f8fac3d9232"/>
                <textFieldExpression><![CDATA["Auftrag Ind SF "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="45" width="21" height="30"
                               uuid="9090c500-d27f-4b56-822b-afabed7345f2"/>
                <textFieldExpression><![CDATA["LO "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="45" width="21" height="30"
                               uuid="e14a262b-e2f3-4ff6-98d2-2bcc4d823aff"/>
                <textFieldExpression><![CDATA["Bt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30"
                               uuid="809e0909-dc78-4667-9744-1dba1b364797"/>
                <textFieldExpression><![CDATA["Liefernr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30"
                               uuid="5ef07b09-c8d3-4afa-b620-1e5909f53b83"/>
                <textFieldExpression><![CDATA["_________ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="125" height="30"
                               uuid="3a8c364d-91ff-4796-a8d6-309fa14743cf"/>
                <textFieldExpression><![CDATA["Liefernr."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="56" height="30"
                               uuid="05520c4b-bf6c-4b49-9a39-84bb8cc32c54"/>
                <textFieldExpression><![CDATA["_______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="84" height="30"
                               uuid="a7cfb74d-253b-472a-8099-93524091eabb"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="28" height="30"
                               uuid="7146a89e-db79-40de-9b18-b8ed7243ee36"/>
                <textFieldExpression><![CDATA["___ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="42" height="30"
                               uuid="1b6869bf-372f-439c-aa7b-2cdf5ebed1b9"/>
                <textFieldExpression><![CDATA["001 1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="326" y="55" width="21" height="30"
                               uuid="85cf340e-b032-4895-a680-d6fb07e59b94"/>
                <textFieldExpression><![CDATA["__ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="97839690-bced-440f-904a-391bc85a5716"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="fe0cc6c1-6d40-452b-a80f-94a3dd6b116b"/>
                <textFieldExpression><![CDATA["_ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="e423269c-63e2-432d-8126-256be9635232"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="548" y="84" width="148" height="30"
                               uuid="44aeb00c-b43a-4e48-adb2-d44cb4f7eecf"/>
                <textFieldExpression><![CDATA["30349480010112031"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="94" width="97" height="30"
                               uuid="fa93e888-50d1-4570-a5ed-73c94f8278dd"/>
                <textFieldExpression><![CDATA["Kundennummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="94" width="97" height="30"
                               uuid="299be608-994c-4e60-9665-7f572650ed4a"/>
                <textFieldExpression><![CDATA["Streutermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="63" height="30"
                               uuid="34a368fe-a36f-442f-80b0-4968434b9e29"/>
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="70" height="30"
                               uuid="7bf8f426-2ee2-4783-9d04-1f1eafbab0ad"/>
                <textFieldExpression><![CDATA["28260001"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="104" width="97" height="30"
                               uuid="d252009e-5c81-4658-9635-48ad17bd941d"/>
                <textFieldExpression><![CDATA["Auftragsdat.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="104" width="160" height="30"
                               uuid="fc4aaf3f-f9cc-41cf-9aec-5ee2b265cfe7"/>
                <textFieldExpression><![CDATA["Young Fashion Behrendt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="104" width="63" height="30"
                               uuid="fa0f2619-392d-4481-bca6-5060e03f9f06"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="114" width="42" height="30"
                               uuid="a60ea765-2b12-4bb0-94af-62dacffbe049"/>
                <textFieldExpression><![CDATA["Marke "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="114" width="14" height="30"
                               uuid="26b968ad-36d2-47dd-a45b-e90afe71e8ec"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="114" width="14" height="30"
                               uuid="083bfabf-bd80-4bcd-b3d2-9da44c88149b"/>
                <textFieldExpression><![CDATA[". "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="114" width="104" height="30"
                               uuid="aed18c17-a171-43b4-b195-6df4b2b36f53"/>
                <textFieldExpression><![CDATA["50 ***Mc Percy "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="124" width="42" height="30"
                               uuid="c7ff083c-f9bf-49d6-ab92-f3d46625935f"/>
                <textFieldExpression><![CDATA["Thema "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="124" width="14" height="30"
                               uuid="45be8266-40c8-4cc0-8194-58365d3b1d70"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="124" width="146" height="30"
                               uuid="a8487747-4f71-4a6b-9e90-26d9fe7e1dac"/>
                <textFieldExpression><![CDATA["Holmpassage, Holm 39 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="124" width="167" height="30"
                               uuid="c3025359-93d3-4199-ab2a-1e11f79144de"/>
                <textFieldExpression><![CDATA["KATAGABRUF Katag Abrufe"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="134" width="63" height="30"
                               uuid="0ce667c3-52cc-4bc8-a7c9-52fe64d77a66"/>
                <textFieldExpression><![CDATA["Prospekt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="134" width="14" height="30"
                               uuid="66e0b237-3bf0-49e4-8e57-d4e4d9ad52fa"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="144" width="97" height="30"
                               uuid="8c868587-f439-488d-ba7e-8c20df950f71"/>
                <textFieldExpression><![CDATA["Auftragstyp : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30"
                               uuid="ba10ffa4-b019-4fac-b0ea-c1d57f28b10a"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30"
                               uuid="466f60d8-8349-4181-9f11-c507b9191db1"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="144" width="257" height="30"
                               uuid="d338312d-bb67-4c77-a215-2b9d1603e4a4"/>
                <textFieldExpression><![CDATA["291 Katag Lagerauftrag Anschlusshaus "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="154" width="153" height="30"
                               uuid="488a3f66-ca96-49a6-a914-d26aca1087fa"/>
                <textFieldExpression><![CDATA["Verdichtung...: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="154" width="42" height="30"
                               uuid="529de5f2-6d4d-4131-8a9b-926853472a2e"/>
                <textFieldExpression><![CDATA["VERSA "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="164" width="70" height="30"
                               uuid="6471d849-9211-4166-9b51-4b9326c80952"/>
                <textFieldExpression><![CDATA["Versandart"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="164" width="28" height="30"
                               uuid="4012443d-583d-476c-9af6-a2967b0190ef"/>
                <textFieldExpression><![CDATA["...."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="164" width="278" height="30"
                               uuid="4386e810-dd54-45e2-bc21-aeade663ab11"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="141" y="164" width="237" height="30"
                               uuid="6a43b1b4-6d1e-4eec-b863-8cf7a46c16ba"/>
                <textFieldExpression><![CDATA["Hängend: DKS / Liegend: DPD-unfr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="174" width="104" height="30"
                               uuid="497f62ec-782b-4522-b0a6-5d1e3e05ce8f"/>
                <textFieldExpression><![CDATA["Kundentermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="174" width="84" height="30"
                               uuid="be3efcb8-bf3b-42e8-914a-0343a659934b"/>
                <textFieldExpression><![CDATA["Denim Jeans "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="174" width="63" height="30"
                               uuid="e9fb8954-a872-4ec9-b822-569c809a673b"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="174" width="63" height="30"
                               uuid="c24084f6-75a3-4ed1-85f7-3ffde2b55e2d"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="183" width="97" height="30"
                               uuid="cf251eb3-ba40-4db8-8ec6-8ab9bee69561"/>
                <textFieldExpression><![CDATA["Modellnummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="183" width="104" height="30"
                               uuid="50bb5374-5ef2-455d-86ab-9d7e34bc65f3"/>
                <textFieldExpression><![CDATA["Kundenauftrag: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="183" width="70" height="30"
                               uuid="5ed11635-c368-4259-a0ec-256514c89929"/>
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="183" width="70" height="30"
                               uuid="3d00caea-fa04-4d30-bab5-0d0fdcbd8d9e"/>
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="183" width="56" height="30"
                               uuid="82f1f500-9e1f-408f-be77-b129bae3ec56"/>
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="193" width="77" height="30"
                               uuid="645c6daa-c8fb-4f10-b9f9-c68cf9bacb92"/>
                <textFieldExpression><![CDATA["Lagerplatz "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="193" width="14" height="30"
                               uuid="3ea9044a-1852-41c1-9566-df10f41f11c0"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="193" width="104" height="30"
                               uuid="004d22bd-b838-4c34-8127-535bcac6ca39"/>
                <textFieldExpression><![CDATA["Art.Nr. Lief.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="193" width="28" height="30"
                               uuid="6be636a7-8995-4691-8de4-37d71fc95443"/>
                <textFieldExpression><![CDATA["P10 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="193" width="56" height="30"
                               uuid="4c3b8751-f4ce-4ea4-9820-85141d57bb69"/>
                <textFieldExpression><![CDATA["700 NOS "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="203" width="63" height="30"
                               uuid="7448809f-07f9-4fe5-bd8f-1fb6994c68a4"/>
                <textFieldExpression><![CDATA["Bereich: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="203" width="104" height="30"
                               uuid="3cc9ecab-a657-43a7-b488-04edd19edae0"/>
                <textFieldExpression><![CDATA["Art.Bez.Lief.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="134" y="203" width="188" height="30"
                               uuid="221c46e1-32c9-4f93-95d7-49225895737a"/>
                <textFieldExpression><![CDATA["2100 Katag, HAKA I / Hosen "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="203" width="118" height="30"
                               uuid="c8fc6795-9cdf-42b4-ac12-8b19b3a10535"/>
                <textFieldExpression><![CDATA["605 5 P. Regular "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="233" width="912" height="30"
                               uuid="a3a7d32c-b8a8-43be-a1e3-e453115c96bd"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="233" width="912" height="30"
                               uuid="e1a50bdf-46b4-4d1f-aa7c-2f7d519335e8"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="243" width="14" height="30"
                               uuid="7c0edfd8-a133-4106-8763-fa0356d71938"/>
                <textFieldExpression><![CDATA["A "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="127" y="243" width="668" height="30"
                               uuid="48a125ce-c96d-4fce-bfbb-98ad9cefc8df"/>
                <textFieldExpression>
                    <![CDATA["31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="253" width="14" height="30"
                               uuid="fa4589aa-1b6f-4ce0-b576-68db372e21a0"/>
                <textFieldExpression><![CDATA["B "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="127" y="253" width="209" height="30"
                               uuid="8fe3d08b-0aa5-4945-b501-486e1e50332c"/>
                <textFieldExpression><![CDATA["33/34 34/34 36/34 38/34 40/34 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="263" width="912" height="30"
                               uuid="584adfb4-76de-449f-9687-0434e8d0cc7f"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="263" width="912" height="30"
                               uuid="c26a188c-a15b-48f8-ae96-a51888907d41"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="293" width="90" height="30"
                               uuid="b3be0fd2-d206-4b71-b046-75062bd6cad9"/>
                <textFieldExpression><![CDATA["A BLUE STONE "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="191" y="293" width="14" height="30"
                               uuid="c3d943aa-4997-4607-a8be-be99c12eb023"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="236" y="293" width="14" height="30"
                               uuid="b55841c2-8c85-4708-858c-35f3fbc47526"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="280" y="293" width="14" height="30"
                               uuid="c26d6ccd-789c-4f2e-9d31-bf31bf3b59e3"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="326" y="293" width="14" height="30"
                               uuid="b81a2a70-7b09-44d7-8cf5-56e0c3ff625a"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="370" y="293" width="14" height="30"
                               uuid="c47f7bd1-f8a7-4d22-9288-e4053414e270"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="415" y="293" width="14" height="30"
                               uuid="6300c516-f741-486f-9495-e7322909810e"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="459" y="293" width="14" height="30"
                               uuid="bd05be45-8170-4f92-a4ae-18b400dded42"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="504" y="293" width="14" height="30"
                               uuid="dac7e126-30e2-4bdb-b8ea-fd479765929c"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="548" y="293" width="14" height="30"
                               uuid="3ba1a947-a0b4-49f0-9656-5ffefa9d31be"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="594" y="293" width="14" height="30"
                               uuid="44845b7e-709c-413b-a544-8b582bbf84cc"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="638" y="293" width="14" height="30"
                               uuid="e21b9b11-7513-43b1-806a-296ea8690236"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="683" y="293" width="14" height="30"
                               uuid="9c8037aa-03a6-4d42-9794-12b495d57b58"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="727" y="293" width="14" height="30"
                               uuid="cb4a1c4b-5ac0-47bd-8a03-7405eccef2cd"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="772" y="293" width="14" height="30"
                               uuid="23d88a7e-a403-4c4a-88e7-3eeb1bd608cc"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="816" y="293" width="14" height="30"
                               uuid="b7ac4006-33fc-4323-8bfb-5222f1496707"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="19" y="302" width="28" height="30"
                               uuid="3cf0817a-34cf-49c1-b304-e7d8144aae6e"/>
                <textFieldExpression><![CDATA["600 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="166" y="302" width="731" height="30"
                               uuid="9c158b60-559e-4063-90c2-5b153f219056"/>
                <textFieldExpression>
                    <![CDATA["______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="6" y="312" width="90" height="30"
                               uuid="edda79c8-5e27-46e1-8a03-29f5695dd623"/>
                <textFieldExpression><![CDATA["B BLUE STONE "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="147" y="312" width="14" height="30"
                               uuid="a617695c-e6ea-4c41-b696-3573e4d23bac"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="191" y="312" width="14" height="30"
                               uuid="cc867147-b3b9-43bf-b66e-ed7fab86928f"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="236" y="312" width="14" height="30"
                               uuid="02057ac0-4cd7-4ca4-b560-e86463451500"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="280" y="312" width="14" height="30"
                               uuid="7d2080ca-4a40-4cca-9e55-b7f3fc1eca38"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="19" y="322" width="28" height="30"
                               uuid="c83c134b-5ff3-4804-9904-84d9c20b6b4a"/>
                <textFieldExpression><![CDATA["600 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="121" y="322" width="195" height="30"
                               uuid="16150cf5-ebb0-4b0f-94f1-ea650e11a917"/>
                <textFieldExpression><![CDATA["______ ______ ______ ______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="568" y="332" width="104" height="30"
                               uuid="277e1e5b-d83e-4ea4-8e67-65c3f56b3594"/>
                <textFieldExpression><![CDATA["Stück gesamt : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="715" y="332" width="21" height="30"
                               uuid="c506da11-d512-4497-9aea-59515b493430"/>
                <textFieldExpression><![CDATA["19 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="715" y="332" width="49" height="30"
                               uuid="d806813f-0156-452f-82ae-0d8044688d9b"/>
                <textFieldExpression><![CDATA["19 STK "]]></textFieldExpression>
            </textField>
        </band>
    </title>
    <pageHeader>
        <band height="20" splitType="Stretch"/>
    </pageHeader>
    <columnHeader>
        <band height="10" splitType="Stretch"/>
    </columnHeader>
    <detail>
        <band height="50" splitType="Stretch"/>
    </detail>
    <columnFooter>
        <band height="10" splitType="Stretch"/>
    </columnFooter>
    <pageFooter>
        <band height="20" splitType="Stretch"/>
    </pageFooter>
    <summary>
        <band height="20" splitType="Stretch"/>
    </summary>
</jasperReport>
"""


# Running the function again to sort the textfields and preserve CDATA sections
print(sort_textfields_by_y_etree_v3(test_data))

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Blank_A4_Landscape_1" pageWidth="842" pageHeight="595" orientation="Landscape" columnWidth="802" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="5257a660-2fb9-4b86-a461-988c272a56b2">
    <style name="t s0" fontName="Courier" fontSize="10" />
    <queryString>
        <![CDATA[]]>
    </queryString>
    <background>
        <band splitType="Stretch" />
    </background>
    <title>
        <band height="370" splitType="Stretch">
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30" uuid="d5c3fdc3-c70e-4f53-beca-0fc574367d2c" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30" uuid="8c8fa432-7b6f-4b50-ac53-636aa149182c" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30" uuid="ada4bef8-9ee6-4385-a209-a69527e035cd" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30" uuid="5529a32d-8219-427a-b3e1-4c311cbd42ae" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30" uuid="931130b9-140a-4803-8ecd-5b5c78a61f2f" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30" uuid="380626e2-1842-4a2f-854e-b2e3d4654210" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30" uuid="b9710825-801c-4232-aad3-93df902904c5" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30" uuid="f2c75650-e46a-4470-8d3b-19cf04663732" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30" uuid="e129e798-ec34-4a9e-9227-2b6c2ff713f2" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30" uuid="2bc4a69c-761b-4140-bd2a-a36ab4624da3" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="15" width="14" height="30" uuid="674d2a95-641a-4d70-87c1-1af2e6361b18" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="109" y="15" width="14" height="30" uuid="dad8e3ca-1ada-4c0a-be11-f2529292dc0c" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="70" y="35" width="14" height="30" uuid="4c299d51-1e81-4207-b66e-27ed1d53398e" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="485" y="35" width="56" height="30" uuid="2df0b13b-ec14-4454-a796-5ff755ebd910" />
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="35" width="63" height="30" uuid="4e7ad477-f4f4-4643-b954-76d0b3416c8e" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="83" y="35" width="42" height="30" uuid="0da17093-15d4-4d16-97b0-b213a26df606" />
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="56" height="30" uuid="1ae78e77-9be2-461d-a151-c0c490a0a2bb" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="63" height="30" uuid="920be72f-23a9-4eb8-ba18-c3e7e4f1b1ae" />
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="14" height="30" uuid="1ecd4211-71b0-44ce-abc2-622b253e675d" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="28" height="30" uuid="c9997927-b754-494a-93a6-70b8a9499fe3" />
                <textFieldExpression><![CDATA["1"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="619" y="35" width="14" height="30" uuid="f37d057b-726a-46fd-8f2c-4457e06481ad" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="28" height="30" uuid="0e2deb51-35d6-4b71-b894-8aab86ee1cac" />
                <textFieldExpression><![CDATA["120 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="49" height="30" uuid="075b7bb7-f71f-4af9-ac76-497e269d4614" />
                <textFieldExpression><![CDATA["120"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="35" width="21" height="30" uuid="92ef6690-0e69-4f61-babc-90ca8d352f97" />
                <textFieldExpression><![CDATA["31"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="45" width="104" height="30" uuid="ee17a1ce-a8c6-47e0-be59-5f8fac3d9232" />
                <textFieldExpression><![CDATA["Auftrag Ind SF "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="45" width="21" height="30" uuid="9090c500-d27f-4b56-822b-afabed7345f2" />
                <textFieldExpression><![CDATA["LO "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="45" width="21" height="30" uuid="e14a262b-e2f3-4ff6-98d2-2bcc4d823aff" />
                <textFieldExpression><![CDATA["Bt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30" uuid="809e0909-dc78-4667-9744-1dba1b364797" />
                <textFieldExpression><![CDATA["Liefernr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30" uuid="5ef07b09-c8d3-4afa-b620-1e5909f53b83" />
                <textFieldExpression><![CDATA["_________ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="125" height="30" uuid="3a8c364d-91ff-4796-a8d6-309fa14743cf" />
                <textFieldExpression><![CDATA["Liefernr."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="56" height="30" uuid="05520c4b-bf6c-4b49-9a39-84bb8cc32c54" />
                <textFieldExpression><![CDATA["_______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="84" height="30" uuid="a7cfb74d-253b-472a-8099-93524091eabb" />
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="28" height="30" uuid="7146a89e-db79-40de-9b18-b8ed7243ee36" />
                <textFieldExpression><![CDATA["___ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="42" height="30" uuid="1b6869bf-372f-439c-aa7b-2cdf5ebed1b9" />
                <textFieldExpression><![CDATA["001 1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="326" y="55" width="21" height="30" uuid="85cf340e-b032-4895-a680-d6fb07e59b94" />
                <textFieldExpression><![CDATA["__ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30" uuid="97839690-bced-440f-904a-391bc85a5716" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30" uuid="fe0cc6c1-6d40-452b-a80f-94a3dd6b116b" />
                <textFieldExpression><![CDATA["_ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30" uuid="e423269c-63e2-432d-8126-256be9635232" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="548" y="84" width="148" height="30" uuid="44aeb00c-b43a-4e48-adb2-d44cb4f7eecf" />
                <textFieldExpression><![CDATA["30349480010112031"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="94" width="97" height="30" uuid="fa93e888-50d1-4570-a5ed-73c94f8278dd" />
                <textFieldExpression><![CDATA["Kundennummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="94" width="97" height="30" uuid="299be608-994c-4e60-9665-7f572650ed4a" />
                <textFieldExpression><![CDATA["Streutermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="63" height="30" uuid="34a368fe-a36f-442f-80b0-4968434b9e29" />
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="70" height="30" uuid="7bf8f426-2ee2-4783-9d04-1f1eafbab0ad" />
                <textFieldExpression><![CDATA["28260001"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="104" width="97" height="30" uuid="d252009e-5c81-4658-9635-48ad17bd941d" />
                <textFieldExpression><![CDATA["Auftragsdat.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="104" width="160" height="30" uuid="fc4aaf3f-f9cc-41cf-9aec-5ee2b265cfe7" />
                <textFieldExpression><![CDATA["Young Fashion Behrendt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="104" width="63" height="30" uuid="fa0f2619-392d-4481-bca6-5060e03f9f06" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="114" width="42" height="30" uuid="a60ea765-2b12-4bb0-94af-62dacffbe049" />
                <textFieldExpression><![CDATA["Marke "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="114" width="14" height="30" uuid="26b968ad-36d2-47dd-a45b-e90afe71e8ec" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="114" width="14" height="30" uuid="083bfabf-bd80-4bcd-b3d2-9da44c88149b" />
                <textFieldExpression><![CDATA[". "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="114" width="104" height="30" uuid="aed18c17-a171-43b4-b195-6df4b2b36f53" />
                <textFieldExpression><![CDATA["50 ***Mc Percy "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="124" width="42" height="30" uuid="c7ff083c-f9bf-49d6-ab92-f3d46625935f" />
                <textFieldExpression><![CDATA["Thema "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="124" width="14" height="30" uuid="45be8266-40c8-4cc0-8194-58365d3b1d70" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="124" width="146" height="30" uuid="a8487747-4f71-4a6b-9e90-26d9fe7e1dac" />
                <textFieldExpression><![CDATA["Holmpassage, Holm 39 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="124" width="167" height="30" uuid="c3025359-93d3-4199-ab2a-1e11f79144de" />
                <textFieldExpression><![CDATA["KATAGABRUF Katag Abrufe"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="134" width="63" height="30" uuid="0ce667c3-52cc-4bc8-a7c9-52fe64d77a66" />
                <textFieldExpression><![CDATA["Prospekt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="134" width="14" height="30" uuid="66e0b237-3bf0-49e4-8e57-d4e4d9ad52fa" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="144" width="97" height="30" uuid="8c868587-f439-488d-ba7e-8c20df950f71" />
                <textFieldExpression><![CDATA["Auftragstyp : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30" uuid="ba10ffa4-b019-4fac-b0ea-c1d57f28b10a" />
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30" uuid="466f60d8-8349-4181-9f11-c507b9191db1" />
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="144" width="257" height="30" uuid="d338312d-bb67-4c77-a215-2b9d1603e4a4" />
                <textFieldExpression><![CDATA["291 Katag Lagerauftrag Anschlusshaus "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="154" width="153" height="30" uuid="488a3f66-ca96-49a6-a914-d26aca1087fa" />
                <textFieldExpression><![CDATA["Verdichtung...: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="154" width="42" height="30" uuid="529de5f2-6d4d-4131-8a9b-926853472a2e" />
                <textFieldExpression><![CDATA["VERSA "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="164" width="70" height="30" uuid="6471d849-9211-4166-9b51-4b9326c80952" />
                <textFieldExpression><![CDATA["Versandart"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="164" width="28" height="30" uuid="4012443d-583d-476c-9af6-a2967b0190ef" />
                <textFieldExpression><![CDATA["...."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="164" width="278" height="30" uuid="4386e810-dd54-45e2-bc21-aeade663ab11" />
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="141" y="164" width="237" height="30" uuid="6a43b1b4-6d1e-4eec-b863-8cf7a46c16ba" />
                <textFieldExpression><![CDATA["Hängend: DKS / Liegend: DPD-unfr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="174" width="104" height="30" uuid="497f62ec-782b-4522-b0a6-5d1e3e05ce8f" />
                <textFieldExpression><![CDATA["Kundentermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="174" width="84" height="30" uuid="be3efcb8-bf3b-42e8-914a-0343a659934b" />
                <textFieldExpression><![CDATA["Denim Jeans "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="174" width="63" height="30" uuid="e9fb8954-a872-4ec9-b822-569c809a673b" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="174" width="63" height="30" uuid="c24084f6-75a3-4ed1-85f7-3ffde2b55e2d" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="183" width="97" height="30" uuid="cf251eb3-ba40-4db8-8ec6-8ab9bee69561" />
                <textFieldExpression><![CDATA["Modellnummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="440" y="183" width="104" height="30" uuid="50bb5374-5ef2-455d-86ab-9d7e34bc65f3" />
                <textFieldExpression><![CDATA["Kundenauftrag: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="183" width="70" height="30" uuid="5ed11635-c368-4259-a0ec-256514c89929" />
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>
            <textField>

# Offsets +- X und Y Werte

In [ ]:
import re

def adjust_jasperreport_positions_regex(xml_content: str, x_offset=0, y_offset=0) -> str:

    # Define a function to update x and y values using regex
    def repl(match):
        if match.group(1) == "x":
            return 'x="{}"'.format(int(match.group(2)) + x_offset)
        if match.group(1) == "y":
            return 'y="{}"'.format(int(match.group(2)) + y_offset)
        return match.group(0)

    # Apply the regex replacement
    adjusted_xml = re.sub(r'(\b[x|y])="(\d+)"', repl, xml_content)
    return adjusted_xml

# Set your desired offsets here
x_offset_value_test = -16 #-16 when moving after scaling for marging matching
y_offset_value_test = -545 #-44 form moving header up
# Test
xml_input_test = """<textField>
				<reportElement style="t s23" x="188" y="634" width="85" height="30" uuid="f63a2396-e026-4d4a-97fa-e3cc3d576634"/>
				<textFieldExpression><![CDATA["43 Sonstiges "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="668" width="131" height="30" uuid="18fe12e3-7780-4716-ba94-1ea976db1cfb"/>
				<textFieldExpression><![CDATA["weitere Bemerkungen "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s24" x="29" y="545" width="98" height="30" uuid="e0a27826-261b-41bb-bfe0-55186d334056"/>
				<textFieldExpression><![CDATA["Retourengründe "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="564" width="72" height="30" uuid="d37c0748-f1c0-4560-b74f-7d26e9cdabee"/>
				<textFieldExpression><![CDATA["11 zu groß "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="564" width="79" height="30" uuid="0cb17031-1272-4bdf-9072-4f820bd4895d"/>
				<textFieldExpression><![CDATA["12 zu klein "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="576" width="72" height="30" uuid="d02b72ac-5527-41b8-8d6e-47de486424f3"/>
				<textFieldExpression><![CDATA["14 zu kurz "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="576" width="72" height="30" uuid="35ae2f63-ea8d-4536-bdd5-98a83d66ae13"/>
				<textFieldExpression><![CDATA["13 zu lang "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="587" width="79" height="30" uuid="43255493-86fb-46b7-90e5-605843067ebe"/>
				<textFieldExpression><![CDATA["21 Material "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="587" width="52" height="30" uuid="b9ebd15d-1b75-4dbc-b8d3-32fabce42fcb"/>
				<textFieldExpression><![CDATA["22 Form "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="599" width="216" height="30" uuid="88a27dc8-3680-4d75-8ea0-a73d0bff4124"/>
				<textFieldExpression><![CDATA["24 Stimmt nicht mit Abb. überein "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="599" width="118" height="30" uuid="5491b4d7-33fa-47a6-8dbd-690f3795126c"/>
				<textFieldExpression><![CDATA["23 Farbe / Muster "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="610" width="137" height="30" uuid="21823652-7760-4278-8b88-73e6f0d5aad0"/>
				<textFieldExpression><![CDATA["31 Lieferung zu spät "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="610" width="124" height="30" uuid="ee02c7b6-00f6-45bc-b12c-2e85833240ef"/>
				<textFieldExpression><![CDATA["32 falsche Artikel "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="188" y="622" width="144" height="30" uuid="db0de4d3-fe17-416a-b13a-a56e248aef4a"/>
				<textFieldExpression><![CDATA["41 Artikel beschädigt "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="622" width="157" height="30" uuid="ef8068c3-46f4-4a3d-bdfd-eb092ce5d9fe"/>
				<textFieldExpression><![CDATA["33 zur Auswahl bestellt "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s23" x="29" y="634" width="118" height="30" uuid="7143579c-ee2b-47b0-8c5c-1b87fec0591c"/>
				<textFieldExpression><![CDATA["42 Materialfehler "]]></textFieldExpression>
			</textField>
"""

adjusted_xml_test = adjust_jasperreport_positions_regex(xml_input_test, x_offset=x_offset_value_test, y_offset=y_offset_value_test)
print(adjusted_xml_test)

<pageHeader>
        <band height="162" splitType="Stretch">
            <textField>
                <reportElement x="0" y="183" width="360" height="30" uuid="23c864e2-aa31-4e8f-879b-7fce39746632">
                    <property name="com.jaspersoft.studio.unit.x" value="px"/>
                    <property name="com.jaspersoft.studio.unit.y" value="px"/>
                </reportElement>
                <textElement>
                    <font fontName="Arial Black" size="16" isBold="true"/>
                </textElement>
                <textFieldExpression><![CDATA["Invoice for custom purpose"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="0" y="223" width="550" height="30" uuid="a7b50506-8111-4b3e-b85b-50bc133d000b"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{shippingMethod}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="0" y="240" width="100" height="30" uuid="57de9619-d4a0-4bdc-9b90-1459acb8f089"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA["Term of Delivery"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="100" y="240" width="450" height="30" uuid="c720d5e4-a8c7-4b83-b04b-e17c03c1e73a"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{TermOfDeliveryValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="100" y="257" width="130" height="30" uuid="eb0f0400-23f7-48f4-86a0-7753aea2e009"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{DeliveryAdressNameValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="100" y="274" width="450" height="30" uuid="cf914aba-6924-4cd7-9e37-287a7e296b05"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{CompanyID&CustomsDefermentValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="100" y="291" width="450" height="30" uuid="21124bb8-357a-4350-a3a5-716ab3e053d5"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{ContentValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="0" y="257" width="100" height="30" uuid="abc63bac-ea08-45ef-abd0-9232ef43bd64"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA["Delivery Adress"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="230" y="257" width="130" height="30" uuid="f48357cb-29ec-4d74-b0a4-814b8e31bb79"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{DeliveryAdressStreetValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="360" y="257" width="130" height="30" uuid="afffd6ef-3c68-4a80-bf3d-112521c32767"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA[$P{DeliveryAdressCityValue}]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="0" y="274" width="100" height="30" uuid="4e34ca45-f54d-4ccc-aab4-d776a6692cd4"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA["Shipment number"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement x="0" y="291" width="100" height="30" uuid="e50cbf86-8a57-4c5b-bc86-ddfd2810b813"/>
                <textElement>
                    <font fontName="Arial Unicode MS" size="9"/>
                </textElement>
                <textFieldExpression><![CDATA["Content"]]></textFieldExpression>
            </textField>
        </band>
    </pageHeader>

# Skalierte X und Y werte

In [ ]:
import re
def adjust_jasperreport_positions_corrected(xml_content: str, x_scale_factor=1.0, y_scale_factor=1.0, font_scale_factor=1.0, height_scale_factor=1.0, width_scale_factor=1.0) -> str:

    def repl(match):
        attribute = match.group(1)
        value = match.group(2)

        # Scale the value if necessary
        if attribute == "x":
            value = str(round(float(value) * x_scale_factor))
        elif attribute == "y":
            value = str(round(float(value) * y_scale_factor))
        elif attribute == "fontSize":
            value = str(round(float(value) * font_scale_factor))
        elif attribute == "height":
            value = str(round(float(value) * height_scale_factor))
        elif attribute == "width":
            value = str(round(float(value) * width_scale_factor))

        return attribute + '="' + value + '"'

    # Correcting the regex pattern to capture decimal values as well
    adjusted_xml = re.sub(r'(\bx|y|fontSize|height|width)="([\d.]+)"', repl, xml_content)
    return adjusted_xml


# Set your desired offsets here A3 zu A4 ohne verschieben : 0,654481132075472
x_scale_value = (842/1210)
y_scale_value = (595/825)
fontSize_scale_value = (842/1210)
height_scale_value= 1
width_scale_value= (842/1210)
##
# Test
xml_input_test = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.20.6.final using JasperReports Library version 6.20.6-5c96b6aa8a39ac1dc6b6bea4b81168e16dd39231  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
              name="Blank_A4_Landscape_1" pageWidth="1210" pageHeight="5950" orientation="Landscape" columnWidth="802"
              leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20"
              uuid="5257a660-2fb9-4b86-a461-988c272a56b2">
    <style name="t s0" fontName="Courier" fontSize="15"/>
    <queryString>
        <![CDATA[]]>
    </queryString>
    <background>
        <band splitType="Stretch"/>
    </background>
    <title>
        <band height="560" splitType="Stretch">
            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30"
                               uuid="d5c3fdc3-c70e-4f53-beca-0fc574367d2c"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30"
                               uuid="8c8fa432-7b6f-4b50-ac53-636aa149182c"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30"
                               uuid="ada4bef8-9ee6-4385-a209-a69527e035cd"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30"
                               uuid="5529a32d-8219-427a-b3e1-4c311cbd42ae"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30"
                               uuid="931130b9-140a-4803-8ecd-5b5c78a61f2f"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30"
                               uuid="380626e2-1842-4a2f-854e-b2e3d4654210"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30"
                               uuid="b9710825-801c-4232-aad3-93df902904c5"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30"
                               uuid="f2c75650-e46a-4470-8d3b-19cf04663732"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30"
                               uuid="e129e798-ec34-4a9e-9227-2b6c2ff713f2"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30"
                               uuid="2bc4a69c-761b-4140-bd2a-a36ab4624da3"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="110" y="21" width="20" height="30"
                               uuid="674d2a95-641a-4d70-87c1-1af2e6361b18"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="156" y="21" width="20" height="30"
                               uuid="dad8e3ca-1ada-4c0a-be11-f2529292dc0c"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="101" y="48" width="20" height="30"
                               uuid="4c299d51-1e81-4207-b66e-27ed1d53398e"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="697" y="48" width="80" height="30"
                               uuid="2df0b13b-ec14-4454-a796-5ff755ebd910"/>
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="48" width="90" height="30"
                               uuid="4e7ad477-f4f4-4643-b954-76d0b3416c8e"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="119" y="48" width="60" height="30"
                               uuid="0da17093-15d4-4d16-97b0-b213a26df606"/>
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="48" width="80" height="30"
                               uuid="1ae78e77-9be2-461d-a151-c0c490a0a2bb"/>
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="48" width="90" height="30"
                               uuid="920be72f-23a9-4eb8-ba18-c3e7e4f1b1ae"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="862" y="48" width="20" height="30"
                               uuid="1ecd4211-71b0-44ce-abc2-622b253e675d"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="862" y="48" width="40" height="30"
                               uuid="c9997927-b754-494a-93a6-70b8a9499fe3"/>
                <textFieldExpression><![CDATA["1"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="889" y="48" width="20" height="30"
                               uuid="f37d057b-726a-46fd-8f2c-4457e06481ad"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="953" y="48" width="40" height="30"
                               uuid="0e2deb51-35d6-4b71-b894-8aab86ee1cac"/>
                <textFieldExpression><![CDATA["120 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="953" y="48" width="70" height="30"
                               uuid="075b7bb7-f71f-4af9-ac76-497e269d4614"/>
                <textFieldExpression><![CDATA["120"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="990" y="48" width="30" height="30"
                               uuid="92ef6690-0e69-4f61-babc-90ca8d352f97"/>
                <textFieldExpression><![CDATA["31"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="62" width="150" height="30"
                               uuid="ee17a1ce-a8c6-47e0-be59-5f8fac3d9232"/>
                <textFieldExpression><![CDATA["Auftrag Ind SF "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="953" y="62" width="30" height="30"
                               uuid="9090c500-d27f-4b56-822b-afabed7345f2"/>
                <textFieldExpression><![CDATA["LO "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="990" y="62" width="30" height="30"
                               uuid="e14a262b-e2f3-4ff6-98d2-2bcc4d823aff"/>
                <textFieldExpression><![CDATA["Bt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="266" y="76" width="100" height="30"
                               uuid="809e0909-dc78-4667-9744-1dba1b364797"/>
                <textFieldExpression><![CDATA["Liefernr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="266" y="76" width="100" height="30"
                               uuid="5ef07b09-c8d3-4afa-b620-1e5909f53b83"/>
                <textFieldExpression><![CDATA["_________ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="266" y="76" width="180" height="30"
                               uuid="3a8c364d-91ff-4796-a8d6-309fa14743cf"/>
                <textFieldExpression><![CDATA["Liefernr."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="358" y="76" width="80" height="30"
                               uuid="05520c4b-bf6c-4b49-9a39-84bb8cc32c54"/>
                <textFieldExpression><![CDATA["_______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="358" y="76" width="120" height="30"
                               uuid="a7cfb74d-253b-472a-8099-93524091eabb"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="431" y="76" width="40" height="30"
                               uuid="7146a89e-db79-40de-9b18-b8ed7243ee36"/>
                <textFieldExpression><![CDATA["___ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="431" y="76" width="60" height="30"
                               uuid="1b6869bf-372f-439c-aa7b-2cdf5ebed1b9"/>
                <textFieldExpression><![CDATA["001 1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="468" y="76" width="30" height="30"
                               uuid="85cf340e-b032-4895-a680-d6fb07e59b94"/>
                <textFieldExpression><![CDATA["__ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30"
                               uuid="97839690-bced-440f-904a-391bc85a5716"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30"
                               uuid="fe0cc6c1-6d40-452b-a80f-94a3dd6b116b"/>
                <textFieldExpression><![CDATA["_ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="422" y="76" width="20" height="30"
                               uuid="e423269c-63e2-432d-8126-256be9635232"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="788" y="117" width="213" height="30"
                               uuid="44aeb00c-b43a-4e48-adb2-d44cb4f7eecf"/>
                <textFieldExpression><![CDATA["30349480010112031"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="131" width="140" height="30"
                               uuid="fa93e888-50d1-4570-a5ed-73c94f8278dd"/>
                <textFieldExpression><![CDATA["Kundennummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="131" width="140" height="30"
                               uuid="299be608-994c-4e60-9665-7f572650ed4a"/>
                <textFieldExpression><![CDATA["Streutermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="165" y="131" width="90" height="30"
                               uuid="34a368fe-a36f-442f-80b0-4968434b9e29"/>
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="165" y="131" width="101" height="30"
                               uuid="7bf8f426-2ee2-4783-9d04-1f1eafbab0ad"/>
                <textFieldExpression><![CDATA["28260001"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="144" width="140" height="30"
                               uuid="d252009e-5c81-4658-9635-48ad17bd941d"/>
                <textFieldExpression><![CDATA["Auftragsdat.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="144" width="230" height="30"
                               uuid="fc4aaf3f-f9cc-41cf-9aec-5ee2b265cfe7"/>
                <textFieldExpression><![CDATA["Young Fashion Behrendt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="541" y="144" width="90" height="30"
                               uuid="fa0f2619-392d-4481-bca6-5060e03f9f06"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="158" width="60" height="30"
                               uuid="a60ea765-2b12-4bb0-94af-62dacffbe049"/>
                <textFieldExpression><![CDATA["Marke "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="523" y="158" width="20" height="30"
                               uuid="26b968ad-36d2-47dd-a45b-e90afe71e8ec"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="158" width="20" height="30"
                               uuid="083bfabf-bd80-4bcd-b3d2-9da44c88149b"/>
                <textFieldExpression><![CDATA[". "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="541" y="158" width="150" height="30"
                               uuid="aed18c17-a171-43b4-b195-6df4b2b36f53"/>
                <textFieldExpression><![CDATA["50 ***Mc Percy "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="172" width="60" height="30"
                               uuid="c7ff083c-f9bf-49d6-ab92-f3d46625935f"/>
                <textFieldExpression><![CDATA["Thema "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="523" y="172" width="20" height="30"
                               uuid="45be8266-40c8-4cc0-8194-58365d3b1d70"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="172" width="210" height="30"
                               uuid="a8487747-4f71-4a6b-9e90-26d9fe7e1dac"/>
                <textFieldExpression><![CDATA["Holmpassage, Holm 39 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="541" y="172" width="240" height="30"
                               uuid="c3025359-93d3-4199-ab2a-1e11f79144de"/>
                <textFieldExpression><![CDATA["KATAGABRUF Katag Abrufe"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="186" width="90" height="30"
                               uuid="0ce667c3-52cc-4bc8-a7c9-52fe64d77a66"/>
                <textFieldExpression><![CDATA["Prospekt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="523" y="186" width="20" height="30"
                               uuid="66e0b237-3bf0-49e4-8e57-d4e4d9ad52fa"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="413" y="199" width="140" height="30"
                               uuid="8c868587-f439-488d-ba7e-8c20df950f71"/>
                <textFieldExpression><![CDATA["Auftragstyp : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="199" width="180" height="30"
                               uuid="ba10ffa4-b019-4fac-b0ea-c1d57f28b10a"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="199" width="180" height="30"
                               uuid="466f60d8-8349-4181-9f11-c507b9191db1"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="541" y="199" width="370" height="30"
                               uuid="d338312d-bb67-4c77-a215-2b9d1603e4a4"/>
                <textFieldExpression><![CDATA["291 Katag Lagerauftrag Anschlusshaus "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="213" width="220" height="30"
                               uuid="488a3f66-ca96-49a6-a914-d26aca1087fa"/>
                <textFieldExpression><![CDATA["Verdichtung...: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="165" y="213" width="60" height="30"
                               uuid="529de5f2-6d4d-4131-8a9b-926853472a2e"/>
                <textFieldExpression><![CDATA["VERSA "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="227" width="100" height="30"
                               uuid="6471d849-9211-4166-9b51-4b9326c80952"/>
                <textFieldExpression><![CDATA["Versandart"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="110" y="227" width="40" height="30"
                               uuid="4012443d-583d-476c-9af6-a2967b0190ef"/>
                <textFieldExpression><![CDATA["...."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="147" y="227" width="400" height="30"
                               uuid="4386e810-dd54-45e2-bc21-aeade663ab11"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="202" y="227" width="340" height="30"
                               uuid="6a43b1b4-6d1e-4eec-b863-8cf7a46c16ba"/>
                <textFieldExpression><![CDATA["Hängend: DKS / Liegend: DPD-unfr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="633" y="241" width="150" height="30"
                               uuid="497f62ec-782b-4522-b0a6-5d1e3e05ce8f"/>
                <textFieldExpression><![CDATA["Kundentermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="241" width="120" height="30"
                               uuid="be3efcb8-bf3b-42e8-914a-0343a659934b"/>
                <textFieldExpression><![CDATA["Denim Jeans "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="241" width="90" height="30"
                               uuid="e9fb8954-a872-4ec9-b822-569c809a673b"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="241" width="90" height="30"
                               uuid="c24084f6-75a3-4ed1-85f7-3ffde2b55e2d"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="254" width="140" height="30"
                               uuid="cf251eb3-ba40-4db8-8ec6-8ab9bee69561"/>
                <textFieldExpression><![CDATA["Modellnummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="633" y="254" width="150" height="30"
                               uuid="50bb5374-5ef2-455d-86ab-9d7e34bc65f3"/>
                <textFieldExpression><![CDATA["Kundenauftrag: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="147" y="254" width="100" height="30"
                               uuid="5ed11635-c368-4259-a0ec-256514c89929"/>
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="147" y="254" width="100" height="30"
                               uuid="3d00caea-fa04-4d30-bab5-0d0fdcbd8d9e"/>
                <textFieldExpression><![CDATA["210000943 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="254" width="80" height="30"
                               uuid="82f1f500-9e1f-408f-be77-b129bae3ec56"/>
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="268" width="110" height="30"
                               uuid="645c6daa-c8fb-4f10-b9f9-c68cf9bacb92"/>
                <textFieldExpression><![CDATA["Lagerplatz "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="128" y="268" width="20" height="30"
                               uuid="3ea9044a-1852-41c1-9566-df10f41f11c0"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="633" y="268" width="150" height="30"
                               uuid="004d22bd-b838-4c34-8127-535bcac6ca39"/>
                <textFieldExpression><![CDATA["Art.Nr. Lief.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="147" y="268" width="40" height="30"
                               uuid="6be636a7-8995-4691-8de4-37d71fc95443"/>
                <textFieldExpression><![CDATA["P10 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="268" width="80" height="30"
                               uuid="4c3b8751-f4ce-4ea4-9820-85141d57bb69"/>
                <textFieldExpression><![CDATA["700 NOS "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="18" y="282" width="90" height="30"
                               uuid="7448809f-07f9-4fe5-bd8f-1fb6994c68a4"/>
                <textFieldExpression><![CDATA["Bereich: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="633" y="282" width="150" height="30"
                               uuid="3cc9ecab-a657-43a7-b488-04edd19edae0"/>
                <textFieldExpression><![CDATA["Art.Bez.Lief.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="193" y="282" width="270" height="30"
                               uuid="221c46e1-32c9-4f93-95d7-49225895737a"/>
                <textFieldExpression><![CDATA["2100 Katag, HAKA I / Hosen "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="770" y="282" width="170" height="30"
                               uuid="c8fc6795-9cdf-42b4-ac12-8b19b3a10535"/>
                <textFieldExpression><![CDATA["605 5 P. Regular "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="323" width="1310" height="30"
                               uuid="a3a7d32c-b8a8-43be-a1e3-e453115c96bd"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="323" width="1310" height="30"
                               uuid="e1a50bdf-46b4-4d1f-aa7c-2f7d519335e8"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="337" width="20" height="30"
                               uuid="7c0edfd8-a133-4106-8763-fa0356d71938"/>
                <textFieldExpression><![CDATA["A "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="183" y="337" width="960" height="30"
                               uuid="48a125ce-c96d-4fce-bfbb-98ad9cefc8df"/>
                <textFieldExpression>
                    <![CDATA["31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="351" width="20" height="30"
                               uuid="fa4589aa-1b6f-4ce0-b576-68db372e21a0"/>
                <textFieldExpression><![CDATA["B "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="183" y="351" width="300" height="30"
                               uuid="8fe3d08b-0aa5-4945-b501-486e1e50332c"/>
                <textFieldExpression><![CDATA["33/34 34/34 36/34 38/34 40/34 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="364" width="1310" height="30"
                               uuid="584adfb4-76de-449f-9687-0434e8d0cc7f"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="364" width="1310" height="30"
                               uuid="c26a188c-a15b-48f8-ae96-a51888907d41"/>
                <textFieldExpression>
                    <![CDATA["================================================================================================================================== "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="406" width="130" height="30"
                               uuid="b3be0fd2-d206-4b71-b046-75062bd6cad9"/>
                <textFieldExpression><![CDATA["A BLUE STONE "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="275" y="406" width="20" height="30"
                               uuid="c3d943aa-4997-4607-a8be-be99c12eb023"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="339" y="406" width="20" height="30"
                               uuid="b55841c2-8c85-4708-858c-35f3fbc47526"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="403" y="406" width="20" height="30"
                               uuid="c26d6ccd-789c-4f2e-9d31-bf31bf3b59e3"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="468" y="406" width="20" height="30"
                               uuid="b81a2a70-7b09-44d7-8cf5-56e0c3ff625a"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="532" y="406" width="20" height="30"
                               uuid="c47f7bd1-f8a7-4d22-9288-e4053414e270"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="596" y="406" width="20" height="30"
                               uuid="6300c516-f741-486f-9495-e7322909810e"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="660" y="406" width="20" height="30"
                               uuid="bd05be45-8170-4f92-a4ae-18b400dded42"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="724" y="406" width="20" height="30"
                               uuid="dac7e126-30e2-4bdb-b8ea-fd479765929c"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="788" y="406" width="20" height="30"
                               uuid="3ba1a947-a0b4-49f0-9656-5ffefa9d31be"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="853" y="406" width="20" height="30"
                               uuid="44845b7e-709c-413b-a544-8b582bbf84cc"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="917" y="406" width="20" height="30"
                               uuid="e21b9b11-7513-43b1-806a-296ea8690236"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="981" y="406" width="20" height="30"
                               uuid="9c8037aa-03a6-4d42-9794-12b495d57b58"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="1045" y="406" width="20" height="30"
                               uuid="cb4a1c4b-5ac0-47bd-8a03-7405eccef2cd"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="1109" y="406" width="20" height="30"
                               uuid="23d88a7e-a403-4c4a-88e7-3eeb1bd608cc"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="1173" y="406" width="20" height="30"
                               uuid="b7ac4006-33fc-4323-8bfb-5222f1496707"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="28" y="419" width="40" height="30"
                               uuid="3cf0817a-34cf-49c1-b304-e7d8144aae6e"/>
                <textFieldExpression><![CDATA["600 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="238" y="419" width="1050" height="30"
                               uuid="9c158b60-559e-4063-90c2-5b153f219056"/>
                <textFieldExpression>
                    <![CDATA["______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="9" y="433" width="130" height="30"
                               uuid="edda79c8-5e27-46e1-8a03-29f5695dd623"/>
                <textFieldExpression><![CDATA["B BLUE STONE "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="211" y="433" width="20" height="30"
                               uuid="a617695c-e6ea-4c41-b696-3573e4d23bac"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="275" y="433" width="20" height="30"
                               uuid="cc867147-b3b9-43bf-b66e-ed7fab86928f"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="339" y="433" width="20" height="30"
                               uuid="02057ac0-4cd7-4ca4-b560-e86463451500"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="403" y="433" width="20" height="30"
                               uuid="7d2080ca-4a40-4cca-9e55-b7f3fc1eca38"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="28" y="447" width="40" height="30"
                               uuid="c83c134b-5ff3-4804-9904-84d9c20b6b4a"/>
                <textFieldExpression><![CDATA["600 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="174" y="447" width="280" height="30"
                               uuid="16150cf5-ebb0-4b0f-94f1-ea650e11a917"/>
                <textFieldExpression><![CDATA["______ ______ ______ ______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="816" y="461" width="150" height="30"
                               uuid="277e1e5b-d83e-4ea4-8e67-65c3f56b3594"/>
                <textFieldExpression><![CDATA["Stück gesamt : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="1027" y="461" width="30" height="30"
                               uuid="c506da11-d512-4497-9aea-59515b493430"/>
                <textFieldExpression><![CDATA["19 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="1027" y="461" width="70" height="30"
                               uuid="d806813f-0156-452f-82ae-0d8044688d9b"/>
                <textFieldExpression><![CDATA["19 STK "]]></textFieldExpression>
            </textField>
        </band>
    </title>
    <pageHeader>
        <band height="35" splitType="Stretch"/>
    </pageHeader>
    <columnHeader>
        <band height="61" splitType="Stretch"/>
    </columnHeader>
    <detail>
        <band height="125" splitType="Stretch"/>
    </detail>
    <columnFooter>
        <band height="45" splitType="Stretch"/>
    </columnFooter>
    <pageFooter>
        <band height="54" splitType="Stretch"/>
    </pageFooter>
    <summary>
        <band height="42" splitType="Stretch"/>
    </summary>
</jasperReport>
"""

scaled_xml_content = adjust_jasperreport_positions_corrected(xml_input_test, x_scale_value, y_scale_value, fontSize_scale_value, height_scale_value, width_scale_value)
print(scaled_xml_content)

<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.20.6.final using JasperReports Library version 6.20.6-5c96b6aa8a39ac1dc6b6bea4b81168e16dd39231  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
              name="Blank_A4_Landscape_1" pageWidth="1210" pageHeight="5950" orientation="Landscape" columnWidth="802"
              leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20"
              uuid="5257a660-2fb9-4b86-a461-988c272a56b2">
    <style name="t s0" fontName="Courier" fontSize="10"/>
    <queryString>
        <![CDATA[]]>
    </queryString>
    <background>
        <band splitType="Stretch"/>
    </background>
    <title>
        <band height="560" splitType="Stretch">
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30"
                               uuid="d5c3fdc3-c70e-4f53-beca-0fc574367d2c"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30"
                               uuid="8c8fa432-7b6f-4b50-ac53-636aa149182c"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30"
                               uuid="ada4bef8-9ee6-4385-a209-a69527e035cd"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30"
                               uuid="5529a32d-8219-427a-b3e1-4c311cbd42ae"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30"
                               uuid="931130b9-140a-4803-8ecd-5b5c78a61f2f"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="15" width="49" height="30"
                               uuid="380626e2-1842-4a2f-854e-b2e3d4654210"/>
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="89" y="15" width="14" height="30"
                               uuid="b9710825-801c-4232-aad3-93df902904c5"/>
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="15" width="70" height="30"
                               uuid="f2c75650-e46a-4470-8d3b-19cf04663732"/>
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="15" width="90" height="30"
                               uuid="e129e798-ec34-4a9e-9227-2b6c2ff713f2"/>
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="274" y="15" width="327" height="30"
                               uuid="2bc4a69c-761b-4140-bd2a-a36ab4624da3"/>
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="15" width="14" height="30"
                               uuid="674d2a95-641a-4d70-87c1-1af2e6361b18"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="109" y="15" width="14" height="30"
                               uuid="dad8e3ca-1ada-4c0a-be11-f2529292dc0c"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="70" y="35" width="14" height="30"
                               uuid="4c299d51-1e81-4207-b66e-27ed1d53398e"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="485" y="35" width="56" height="30"
                               uuid="2df0b13b-ec14-4454-a796-5ff755ebd910"/>
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="35" width="63" height="30"
                               uuid="4e7ad477-f4f4-4643-b954-76d0b3416c8e"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="83" y="35" width="42" height="30"
                               uuid="0da17093-15d4-4d16-97b0-b213a26df606"/>
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="56" height="30"
                               uuid="1ae78e77-9be2-461d-a151-c0c490a0a2bb"/>
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="35" width="63" height="30"
                               uuid="920be72f-23a9-4eb8-ba18-c3e7e4f1b1ae"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="14" height="30"
                               uuid="1ecd4211-71b0-44ce-abc2-622b253e675d"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="600" y="35" width="28" height="30"
                               uuid="c9997927-b754-494a-93a6-70b8a9499fe3"/>
                <textFieldExpression><![CDATA["1"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="619" y="35" width="14" height="30"
                               uuid="f37d057b-726a-46fd-8f2c-4457e06481ad"/>
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="28" height="30"
                               uuid="0e2deb51-35d6-4b71-b894-8aab86ee1cac"/>
                <textFieldExpression><![CDATA["120 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="35" width="49" height="30"
                               uuid="075b7bb7-f71f-4af9-ac76-497e269d4614"/>
                <textFieldExpression><![CDATA["120"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="35" width="21" height="30"
                               uuid="92ef6690-0e69-4f61-babc-90ca8d352f97"/>
                <textFieldExpression><![CDATA["31"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="536" y="45" width="104" height="30"
                               uuid="ee17a1ce-a8c6-47e0-be59-5f8fac3d9232"/>
                <textFieldExpression><![CDATA["Auftrag Ind SF "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="663" y="45" width="21" height="30"
                               uuid="9090c500-d27f-4b56-822b-afabed7345f2"/>
                <textFieldExpression><![CDATA["LO "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="689" y="45" width="21" height="30"
                               uuid="e14a262b-e2f3-4ff6-98d2-2bcc4d823aff"/>
                <textFieldExpression><![CDATA["Bt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30"
                               uuid="809e0909-dc78-4667-9744-1dba1b364797"/>
                <textFieldExpression><![CDATA["Liefernr. "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="70" height="30"
                               uuid="5ef07b09-c8d3-4afa-b620-1e5909f53b83"/>
                <textFieldExpression><![CDATA["_________ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="185" y="55" width="125" height="30"
                               uuid="3a8c364d-91ff-4796-a8d6-309fa14743cf"/>
                <textFieldExpression><![CDATA["Liefernr."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="56" height="30"
                               uuid="05520c4b-bf6c-4b49-9a39-84bb8cc32c54"/>
                <textFieldExpression><![CDATA["_______ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="249" y="55" width="84" height="30"
                               uuid="a7cfb74d-253b-472a-8099-93524091eabb"/>
                <textFieldExpression><![CDATA["3034948"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="28" height="30"
                               uuid="7146a89e-db79-40de-9b18-b8ed7243ee36"/>
                <textFieldExpression><![CDATA["___ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="300" y="55" width="42" height="30"
                               uuid="1b6869bf-372f-439c-aa7b-2cdf5ebed1b9"/>
                <textFieldExpression><![CDATA["001 1 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="326" y="55" width="21" height="30"
                               uuid="85cf340e-b032-4895-a680-d6fb07e59b94"/>
                <textFieldExpression><![CDATA["__ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="97839690-bced-440f-904a-391bc85a5716"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="fe0cc6c1-6d40-452b-a80f-94a3dd6b116b"/>
                <textFieldExpression><![CDATA["_ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="294" y="55" width="14" height="30"
                               uuid="e423269c-63e2-432d-8126-256be9635232"/>
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="548" y="84" width="148" height="30"
                               uuid="44aeb00c-b43a-4e48-adb2-d44cb4f7eecf"/>
                <textFieldExpression><![CDATA["30349480010112031"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="94" width="97" height="30"
                               uuid="fa93e888-50d1-4570-a5ed-73c94f8278dd"/>
                <textFieldExpression><![CDATA["Kundennummer: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="94" width="97" height="30"
                               uuid="299be608-994c-4e60-9665-7f572650ed4a"/>
                <textFieldExpression><![CDATA["Streutermin : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="63" height="30"
                               uuid="34a368fe-a36f-442f-80b0-4968434b9e29"/>
                <textFieldExpression><![CDATA["28260001 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="94" width="70" height="30"
                               uuid="7bf8f426-2ee2-4783-9d04-1f1eafbab0ad"/>
                <textFieldExpression><![CDATA["28260001"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="104" width="97" height="30"
                               uuid="d252009e-5c81-4658-9635-48ad17bd941d"/>
                <textFieldExpression><![CDATA["Auftragsdat.: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="104" width="160" height="30"
                               uuid="fc4aaf3f-f9cc-41cf-9aec-5ee2b265cfe7"/>
                <textFieldExpression><![CDATA["Young Fashion Behrendt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="104" width="63" height="30"
                               uuid="fa0f2619-392d-4481-bca6-5060e03f9f06"/>
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="114" width="42" height="30"
                               uuid="a60ea765-2b12-4bb0-94af-62dacffbe049"/>
                <textFieldExpression><![CDATA["Marke "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="114" width="14" height="30"
                               uuid="26b968ad-36d2-47dd-a45b-e90afe71e8ec"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="114" width="14" height="30"
                               uuid="083bfabf-bd80-4bcd-b3d2-9da44c88149b"/>
                <textFieldExpression><![CDATA[". "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="114" width="104" height="30"
                               uuid="aed18c17-a171-43b4-b195-6df4b2b36f53"/>
                <textFieldExpression><![CDATA["50 ***Mc Percy "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="124" width="42" height="30"
                               uuid="c7ff083c-f9bf-49d6-ab92-f3d46625935f"/>
                <textFieldExpression><![CDATA["Thema "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="124" width="14" height="30"
                               uuid="45be8266-40c8-4cc0-8194-58365d3b1d70"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="124" width="146" height="30"
                               uuid="a8487747-4f71-4a6b-9e90-26d9fe7e1dac"/>
                <textFieldExpression><![CDATA["Holmpassage, Holm 39 "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="124" width="167" height="30"
                               uuid="c3025359-93d3-4199-ab2a-1e11f79144de"/>
                <textFieldExpression><![CDATA["KATAGABRUF Katag Abrufe"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="134" width="63" height="30"
                               uuid="0ce667c3-52cc-4bc8-a7c9-52fe64d77a66"/>
                <textFieldExpression><![CDATA["Prospekt "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="364" y="134" width="14" height="30"
                               uuid="66e0b237-3bf0-49e4-8e57-d4e4d9ad52fa"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="287" y="144" width="97" height="30"
                               uuid="8c868587-f439-488d-ba7e-8c20df950f71"/>
                <textFieldExpression><![CDATA["Auftragstyp : "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30"
                               uuid="ba10ffa4-b019-4fac-b0ea-c1d57f28b10a"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="144" width="125" height="30"
                               uuid="466f60d8-8349-4181-9f11-c507b9191db1"/>
                <textFieldExpression><![CDATA["D-24937 Flensburg "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="376" y="144" width="257" height="30"
                               uuid="d338312d-bb67-4c77-a215-2b9d1603e4a4"/>
                <textFieldExpression><![CDATA["291 Katag Lagerauftrag Anschlusshaus "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="154" width="153" height="30"
                               uuid="488a3f66-ca96-49a6-a914-d26aca1087fa"/>
                <textFieldExpression><![CDATA["Verdichtung...: "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="115" y="154" width="42" height="30"
                               uuid="529de5f2-6d4d-4131-8a9b-926853472a2e"/>
                <textFieldExpression><![CDATA["VERSA "]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="13" y="164" width="70" height="30"
                               uuid="6471d849-9211-4166-9b51-4b9326c80952"/>
                <textFieldExpression><![CDATA["Versandart"]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="77" y="164" width="28" height="30"
                               uuid="4012443d-583d-476c-9af6-a2967b0190ef"/>
                <textFieldExpression><![CDATA["...."]]></textFieldExpression>
            </textField>
            <textField>
                <reportElement style="t s0" x="102" y="164" width="278" height="30"
                               uuid="4386e810-dd54-45e2-bc21-aeade663ab11"/>
                <textFieldExpression><![CDATA[": "]]></textFieldExpression>
            </textField>
            <textField>

In [ ]:
import re

def adjust_jasperreport_positions_regex(xml_content: str, x_scale_factor=1.0, y_scale_factor=1.0, font_scale_factor=1.0, height_scale_factor=1.0, width_scale_factor=1.0, isTextFieldScaling=True, scaleAll=False) -> str:

    def repl(match):
        # Check if the current match is inside a <textField> element
        preceding_text = match.group(1) or ""  # The text before the attribute
        attribute = match.group(2)
        value = match.group(3)
        following_text = match.group(4) or ""  # The text after the attribute

        # Determine if the current match should be scaled
        #is_textfield = "<textField>" in preceding_text
        #if scaleAll:
        #    should_scale = True
        #else:
        #    should_scale = (is_textfield and isTextFieldScaling) or (not is_textfield and not isTextFieldScaling)

        # Scale the value if necessary
        #if should_scale:
        if attribute == "x":
            value = str(round(int(value) * x_scale_factor))
        elif attribute == "y":
            value = str(round(int(value) * y_scale_factor))
        elif attribute == "fontSize":
            value = str(round(int(value) * font_scale_factor))
        elif attribute == "height":
            value = str(round(int(value) * height_scale_factor))
        elif attribute == "width":
            value = str(round(int(value) * width_scale_factor))

        return preceding_text + attribute + '="' + value + '"' + following_text

    adjusted_xml = re.sub(r'(.)?(\bx|y|fontSize|height|width)=\"(\d+)\"(.)?"g', repl, xml_content)
    return adjusted_xml

# Set your desired offsets here
x_scale_value = 10
y_scale_value = 10
fontSize_scale_value = 10
height_scale_value= 10
width_scale_value= 10
#this shoud be deaktivated
isTextFieldScaling=True
scaleAll=True

##
# Test
xml_input_test = """
<pageHeader>
        <band height="450" splitType="Stretch">
            <textField>
                <reportElement style="t s8" x="174" y="94" width="272" height="77"
                               uuid="a80924d8-085b-4624-a9c1-f65974565537"/>
                <textFieldExpression><![CDATA[$P{Header}]]></textFieldExpression>
            </textField>
       </band>
</pageHeader>

"""


#Mit diesen Ein stellungen soll Nicht das ganze Dokument scaliert werden sondern nur ein Teil, isTextFieldScaling gibt an ob nur <textFiels> oder nur alle anderen Elemente skaliert werden.
# Beispiel: Zum Skalieren von x um den Faktor 1.2, y um 0.83, fontSize um 1.1, height um 1.05, und width um 0.95,isTextFieldScaling, scaleAll
scaled_xml_content = adjust_jasperreport_positions_regex(xml_input_test, x_scale_value, y_scale_value, fontSize_scale_value, height_scale_value, width_scale_value, isTextFieldScaling, scaleAll)

print(scaled_xml_content)

<pageHeader>
        <band height="450" splitType="Stretch">
            <textField>
                <reportElement style="t s8" x="174" y="94" width="272" height="77"
                               uuid="a80924d8-085b-4624-a9c1-f65974565537"/>
                <textFieldExpression><![CDATA[$P{Header}]]></textFieldExpression>
            </textField>
       </band>
</pageHeader>

# Parameter Oder Fields anlegen

In [ ]:
import re

def transform_jasper_report(xml_content: str) -> str:
    added_parameters = []
    added_fields = []

    skip_all = False  # global variable to check if the user has chosen the "Skip All" option

    # Diese Funktion ersetzt das textField anhand der Auswahl des Benutzers
    def replace_text_field(match):
        nonlocal skip_all
        # Wenn skip_all True ist, geben Sie das textField so zurück, wie es ist
        if skip_all:
            return match.group(0)

        # textField-Inhalt extrahieren
        text_field_content = match.group(0)

        # Fragen Sie den Benutzer nach einer Wahl
        print("Für das textField:", text_field_content)
        choice = input("Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): ")

        # Wenn keine Auswahl getroffen wird, wird "Parameter" als Standardwert festgelegt
        if choice.strip() == '':
            choice = '1'

        # Wenn der Benutzer "Alles überspringen" wählt
        if choice == '4':
            skip_all = True
            return text_field_content

        # Wenn der Benutzer überspringt
        if choice == '3':
            return text_field_content

        # Extrahieren Sie den String aus textFieldExpression
        expression_match = re.search(r'<textFieldExpression><!\[CDATA\[(.*?)\]\]></textFieldExpression>', text_field_content)
        if not expression_match:
            return text_field_content
        extracted_string = expression_match.group(1)

        # Fragen Sie den Benutzer nach dem Namen
        name = input(f"Geben Sie einen Namen für den {'Parameter' if choice == '1' else 'Feld'} ein: ")

        # Fragen Sie nach dem Datentyp
        data_type = input(f"Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): ")
        if data_type.strip() == '' or data_type == '1':
            data_type = 'java.lang.String'
        else:
            data_type = 'java.lang.Integer'

        # Erstellen Sie Parameter oder Feld basierend auf der Wahl des Benutzers
        if choice == '1':
            param_str = (
                f'<parameter name="{name}" class="{data_type}">\n'
                f'\t<defaultValueExpression><![CDATA[{extracted_string}]]></defaultValueExpression>\n'
                f'</parameter>'
            )
            added_parameters.append(param_str)
        else:
            field_str = f'<field name="{name}" class="{data_type}">\n\t<defaultValueExpression><![CDATA[{extracted_string}]]></defaultValueExpression>\n</field>'
            added_fields.append(field_str)

        # Erstellen Sie den Ersatzstring
        prefix = 'P' if choice == '1' else 'F'
        replacement = f'<textFieldExpression><![CDATA[${prefix}{{{name}}}]]></textFieldExpression>'

        # Ersetzen Sie den Inhalt mit re.sub()
        new_text_field_content = re.sub(r'<textFieldExpression><!\[CDATA\[(.*?)\]\]></textFieldExpression>', replacement, text_field_content)

        return new_text_field_content

    # Ersetzen Sie alle textFields im XML-Inhalt
    modified_xml = re.sub(r'(<textField>.*?</textField>)', replace_text_field, xml_content, flags=re.DOTALL)

    # Finden Sie den Einfügepunkt für die Parameter
    params_insertion_point = modified_xml.rfind('</parameter>')
    if params_insertion_point != -1:
        modified_xml = modified_xml[:params_insertion_point + 12] + "\n\n" + "\n".join(added_parameters) + modified_xml[params_insertion_point + 12:]
    else:
        modified_xml += "\n\n<!-- Added Parameter Definitions -->\n"
        modified_xml += "\n".join(added_parameters)

    # Finden Sie den Einfügepunkt für die Felder
    fields_insertion_point = re.search(r'</queryString>', modified_xml)
    if fields_insertion_point:
        modified_xml = modified_xml[:fields_insertion_point.end()] + "\n\n" + "\n".join(added_fields) + modified_xml[fields_insertion_point.end():]
    else:
        modified_xml += "\n\n<!-- Added Field Definitions -->\n"
        modified_xml += "\n".join(added_fields)

    return modified_xml

# Let's load the provided XML and test the function
xml_content = """
    <?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.20.6.final using JasperReports Library version 6.20.6-5c96b6aa8a39ac1dc6b6bea4b81168e16dd39231  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="B2B_DeliveryNote" pageWidth="1286" pageHeight="1819" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" isFloatColumnFooter="true" uuid="8e05fc2d-d534-416e-9828-f0a2760e7a7f">
	<property name="com.jaspersoft.studio.data.sql.tables" value=""/>
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="jespersoft_report_Db"/>
	<style name="t s0" fontName="Arial Unicode MS" fontSize="13"/>
	<style name="t s1" fontName="Arial Unicode MS" fontSize="12"/>
	<style name="t s2" fontName="Arial" fontSize="17" isBold="true"/>
	<style name="t s3" fontName="Arial Unicode MS" fontSize="11"/>
	<style name="t s4" fontName="Arial" fontSize="12" isBold="true"/>
	<style name="t s5" fontName="Arial Unicode MS" fontSize="8"/>
	<style name="t s6" fontName="Arial" fontSize="24" isBold="true"/>
	<style name="t s7" fontName="Arial Unicode MS" fontSize="15"/>
	<style name="t s8" fontName="Arial" fontSize="55" isBold="true"/>
	<parameter name="Header" class="java.lang.String">
		<defaultValueExpression><![CDATA["WRSTBHVR "]]></defaultValueExpression>
	</parameter>
	<queryString language="SQL">
		<![CDATA[Select * From jespersoft_report_data.ArticleDataRows]]>
	</queryString>
	<field name="id" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.name" value="id"/>
		<property name="com.jaspersoft.studio.field.label" value="id"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="article_id" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.name" value="article_id"/>
		<property name="com.jaspersoft.studio.field.label" value="article_id"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="row_num" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.name" value="row_num"/>
		<property name="com.jaspersoft.studio.field.label" value="row_num"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="row_name" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="row_name"/>
		<property name="com.jaspersoft.studio.field.label" value="row_name"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="row_data_values_sum" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.name" value="row_data_values_sum"/>
		<property name="com.jaspersoft.studio.field.label" value="row_data_values_sum"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="data_count" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.name" value="data_count"/>
		<property name="com.jaspersoft.studio.field.label" value="data_count"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value0" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value0"/>
		<property name="com.jaspersoft.studio.field.label" value="value0"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value1" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value1"/>
		<property name="com.jaspersoft.studio.field.label" value="value1"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value2" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value2"/>
		<property name="com.jaspersoft.studio.field.label" value="value2"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value3" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value3"/>
		<property name="com.jaspersoft.studio.field.label" value="value3"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value4" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value4"/>
		<property name="com.jaspersoft.studio.field.label" value="value4"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value5" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value5"/>
		<property name="com.jaspersoft.studio.field.label" value="value5"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value6" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value6"/>
		<property name="com.jaspersoft.studio.field.label" value="value6"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value7" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value7"/>
		<property name="com.jaspersoft.studio.field.label" value="value7"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value8" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value8"/>
		<property name="com.jaspersoft.studio.field.label" value="value8"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value9" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value9"/>
		<property name="com.jaspersoft.studio.field.label" value="value9"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value10" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value10"/>
		<property name="com.jaspersoft.studio.field.label" value="value10"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value11" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value11"/>
		<property name="com.jaspersoft.studio.field.label" value="value11"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<field name="value12" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.name" value="value12"/>
		<property name="com.jaspersoft.studio.field.label" value="value12"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="ArticleDataRows"/>
	</field>
	<group name="id">
		<groupExpression><![CDATA[$F{id}]]></groupExpression>
	</group>
	<background>
		<band splitType="Stretch"/>
	</background>
	<title>
		<band splitType="Stretch"/>
	</title>
	<pageHeader>
		<band height="450" splitType="Stretch">
			<textField>
				<reportElement style="t s8" x="290" y="143" width="416" height="77" uuid="a80924d8-085b-4624-a9c1-f65974565537"/>
				<textFieldExpression><![CDATA[$P{Header}]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="24" y="234" width="630" height="30" uuid="324cbcb0-200c-4bae-a152-ba96901db464"/>
				<textFieldExpression><![CDATA["Worst Behavior GmbH - Carl-Benz-Straße 17 - 89597 Munderkingen "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="695" y="267" width="60" height="30" uuid="ba6e7f98-70b2-46ae-af16-dbbd2064368b"/>
				<textFieldExpression><![CDATA["64128 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="24" y="267" width="300" height="30" uuid="62179801-77db-4644-ad39-889c36532c7c"/>
				<textFieldExpression><![CDATA["Zalando OpCo Polska Sp. z o.o "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="554" y="267" width="190" height="30" uuid="3706f7d1-97a6-4b62-bd20-fe4ee25db15d"/>
				<textFieldExpression><![CDATA["Lieferscheinnummer "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="24" y="284" width="300" height="30" uuid="40db5959-d6ae-4fec-8c59-e8bd648f7749"/>
				<textFieldExpression><![CDATA["Zalando OpCo Polska Sp. z o.o "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="24" y="302" width="180" height="30" uuid="6a53cccf-23d4-413a-82c5-6c73555494b0"/>
				<textFieldExpression><![CDATA["ul. Innowacyina 1 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="554" y="302" width="60" height="30" uuid="70573571-151c-4bd8-bf1d-c364a77267fb"/>
				<textFieldExpression><![CDATA["Datum "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="695" y="302" width="110" height="30" uuid="3be76a89-81e1-417d-9ad2-015bf5b73056"/>
				<textFieldExpression><![CDATA["19.10.2023 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="24" y="317" width="150" height="30" uuid="64254185-eea4-4e40-81df-339ff887c153"/>
				<textFieldExpression><![CDATA["95-080 Gluchow "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="695" y="317" width="60" height="30" uuid="68b054be-5c5d-437b-bf07-c28de66c2b0c"/>
				<textFieldExpression><![CDATA["10006 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="554" y="317" width="130" height="30" uuid="58609327-5433-49fc-a80e-97f046dfa208"/>
				<textFieldExpression><![CDATA["Kundennummer "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s6" x="24" y="367" width="335" height="30" uuid="9734306d-bff4-4e39-a2b4-d132c9a7a47d"/>
				<textFieldExpression><![CDATA["Lieferschein "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="554" y="368" width="60" height="30" uuid="f4717dd5-40cc-4a2e-a374-91efe0abb200"/>
				<textFieldExpression><![CDATA["Seite "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="695" y="368" width="60" height="30" uuid="ad967adc-83a2-4dba-9fab-d18032c1aad5"/>
				<textFieldExpression><![CDATA["1 / 1 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s7" x="24" y="421" width="110" height="29" uuid="3050ea14-ad53-4d2f-93d1-4cc74afa4544"/>
				<textFieldExpression><![CDATA["Versandart "]]></textFieldExpression>
			</textField>
		</band>
	</pageHeader>
	<columnHeader>
		<band height="60" splitType="Stretch">
			<line>
				<reportElement x="25" y="1" width="848" height="1" uuid="74d79a6c-b423-4216-9648-ef215c75eb2b">
					<property name="com.jaspersoft.studio.unit.width" value="px"/>
				</reportElement>
			</line>
			<line>
				<reportElement x="25" y="25" width="848" height="1" uuid="74d79a6c-b423-4216-9648-ef215c75eb2b">
					<property name="com.jaspersoft.studio.unit.width" value="px"/>
				</reportElement>
			</line>
			<textField>
				<reportElement style="t s2" x="73" y="2" width="70" height="30" uuid="8c6cf1fe-5b8f-4cc0-b874-2d7ab02ca255"/>
				<textFieldExpression><![CDATA["Modell "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s2" x="312" y="2" width="60" height="30" uuid="884b6f75-3319-4dfc-a634-bd3e8c6b55bd"/>
				<textFieldExpression><![CDATA["Farbe "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s2" x="30" y="2" width="40" height="30" uuid="ce9d6b00-4d94-4765-a956-ae84ae906ad6"/>
				<textFieldExpression><![CDATA["Pos "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s2" x="818" y="2" width="82" height="30" uuid="26d70d97-e29a-4c54-b970-c9db18f405f8"/>
				<textFieldExpression><![CDATA["Stück "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s2" x="439" y="3" width="80" height="30" uuid="0a40f253-f8a4-4f6b-bbcf-254b81b2475e"/>
				<textFieldExpression><![CDATA["Artikel "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="30" y="28" width="370" height="30" uuid="85a6b313-1e62-4e01-93ec-1246d315e1f9"/>
				<textFieldExpression><![CDATA["PO TT 01/23 WOMEN Zalando PO1416415C "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s0" x="313" y="28" width="110" height="30" uuid="753c8bd2-7c16-4fbb-ae47-edaf6c98c033"/>
				<textFieldExpression><![CDATA["Lodz Auftr "]]></textFieldExpression>
			</textField>
			<line>
				<reportElement x="435" y="25" width="1" height="35" uuid="1acd1808-f1d9-4dba-91fb-4c7f43c408d3"/>
			</line>
			<line>
				<reportElement x="499" y="25" width="1" height="35" uuid="1a15bd76-c24d-4621-9ed5-b67f3678e96e"/>
			</line>
			<line>
				<reportElement x="24" y="1" width="1" height="25" uuid="1297727a-c3c3-4b22-b327-8b527081a823">
					<property name="com.jaspersoft.studio.unit.height" value="px"/>
					<property name="com.jaspersoft.studio.unit.y" value="px"/>
				</reportElement>
			</line>
			<line>
				<reportElement x="873" y="1" width="1" height="25" uuid="b7604b72-1094-4510-8ecd-a85af77e975e"/>
			</line>
		</band>
	</columnHeader>
	<detail>
		<band height="60" splitType="Stretch">
			<textField>
				<reportElement style="t s4" x="607" y="0" width="20" height="30" uuid="e78ea146-bb08-4d9e-a05a-b21487c97e06"/>
				<textFieldExpression><![CDATA["S "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="677" y="0" width="20" height="30" uuid="6e71152e-3b79-4a42-af26-c0beafdb244a"/>
				<textFieldExpression><![CDATA["L "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="766" y="0" width="40" height="30" uuid="25df0ca0-73a8-40a2-8e1e-27219f8428c7"/>
				<textFieldExpression><![CDATA["3XL "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="704" y="0" width="30" height="30" uuid="771aae79-0af6-4648-87a0-2e5b22d481da"/>
				<textFieldExpression><![CDATA["XL "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="731" y="0" width="40" height="30" uuid="10a5e26a-7133-43c3-8d07-dd35eddafb00"/>
				<textFieldExpression><![CDATA["XXL "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="640" y="0" width="20" height="30" uuid="b7db5d44-93d7-4b54-b042-bf5e89c5993f"/>
				<textFieldExpression><![CDATA["M "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="563" y="0" width="30" height="30" uuid="04c24e5d-e78f-4b3d-aacb-c1a427ac722e"/>
				<textFieldExpression><![CDATA["XS "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="521" y="0" width="40" height="30" uuid="d1ca2b90-2b8c-42dd-8197-e0831e58cd42"/>
				<textFieldExpression><![CDATA["XXS "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s3" x="444" y="24" width="50" height="30" uuid="18edbb6b-f36c-4125-a868-06efd49c728e"/>
				<textFieldExpression><![CDATA["2311 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s3" x="312" y="24" width="100" height="30" uuid="6d1d5c44-ac31-4a98-a18f-427953b8a9a8"/>
				<textFieldExpression><![CDATA["TANGERINE "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s3" x="191" y="24" width="120" height="30" uuid="2a4a6700-53ea-4410-9846-4feff88e3c6a"/>
				<textFieldExpression><![CDATA["VALO HOODIE "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="843" y="26" width="40" height="30" uuid="2711f049-dc36-4a13-9252-77ea1175ff66"/>
				<textFieldExpression><![CDATA["119 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="539" y="26" width="20" height="30" uuid="3769b5f3-b1b7-46e4-9a43-e6b90e300886"/>
				<textFieldExpression><![CDATA["1 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="566" y="26" width="30" height="30" uuid="221e4da2-fcf6-4eaa-87d7-f0816db38184"/>
				<textFieldExpression><![CDATA["27 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="601" y="26" width="30" height="30" uuid="c9c4b024-ae04-4735-a053-bde8ea32450c"/>
				<textFieldExpression><![CDATA["47 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="637" y="26" width="30" height="30" uuid="1811b53a-1e9c-4f41-bc41-ef9e55fb0367"/>
				<textFieldExpression><![CDATA["32 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="671" y="26" width="30" height="30" uuid="a558166e-d5d8-402f-8ef4-656ada1e770a"/>
				<textFieldExpression><![CDATA["12 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="73" y="26" width="80" height="30" uuid="e8ac5007-2a06-4842-8695-b706b33e4cfb"/>
				<textFieldExpression><![CDATA["W2023TT "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="48" y="30" width="20" height="30" uuid="5dd42759-ad57-4dca-a008-27ff0895622a"/>
				<textFieldExpression><![CDATA["1 "]]></textFieldExpression>
			</textField>
			<line>
				<reportElement x="25" y="58" width="848" height="1" uuid="74dc085e-84d6-4808-ae37-57961051d2f9">
					<property name="com.jaspersoft.studio.unit.width" value="px"/>
					<property name="com.jaspersoft.studio.unit.x" value="px"/>
					<property name="com.jaspersoft.studio.unit.y" value="px"/>
				</reportElement>
			</line>
			<line>
				<reportElement x="499" y="-2" width="1" height="61" uuid="53778345-5f02-4592-bb25-b6724ccf8073"/>
			</line>
			<line>
				<reportElement x="435" y="-2" width="1" height="61" uuid="a972f60a-944b-4451-80b1-06abc6f32197"/>
			</line>
		</band>
	</detail>
	<columnFooter>
		<band height="45" splitType="Stretch">
			<textField>
				<reportElement style="t s1" x="842" y="0" width="40" height="30" uuid="b3dfd69b-4b7c-4dce-82e0-bca39b26cb58"/>
				<textFieldExpression><![CDATA["272 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s4" x="704" y="0" width="140" height="30" uuid="14fad654-32a5-46dd-b029-6c8b84124ec3"/>
				<textFieldExpression><![CDATA["Gesamt Stück: "]]></textFieldExpression>
			</textField>
		</band>
	</columnFooter>
	<pageFooter>
		<band height="600" splitType="Stretch">
			<textField>
				<reportElement style="t s1" x="24" y="0" width="410" height="30" uuid="226f6248-4a93-429e-8806-ded800f557b6"/>
				<textFieldExpression><![CDATA["Sitz der Gesellschaft / Lieferanschrift: "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="263" y="0" width="160" height="30" uuid="8784c329-4fa6-431d-ba61-725a3f7e59dc"/>
				<textFieldExpression><![CDATA["Bankverbindung: "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="664" y="0" width="180" height="30" uuid="ddc6942c-5d0f-45ac-b412-39989ce1172f"/>
				<textFieldExpression><![CDATA["Geschäftsführung: "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="486" y="0" width="170" height="30" uuid="5af5f189-0d1d-41f3-9a84-9c3747951380"/>
				<textFieldExpression><![CDATA["Amtsgericht: Ulm "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="24" y="15" width="200" height="30" uuid="69ed5bfa-09d3-45cc-828d-1a8539054557"/>
				<textFieldExpression><![CDATA["Worst Behavior GmbH "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="263" y="15" width="240" height="30" uuid="a50f9940-fe12-4e71-af2b-173ca1d1b881"/>
				<textFieldExpression><![CDATA["Kreissparkasse Biberach "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="664" y="15" width="310" height="30" uuid="9e77f31b-5a96-4f47-a3fe-f8af3694fc75"/>
				<textFieldExpression><![CDATA["Fabian Altmann, Janek Feldmann "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="486" y="15" width="280" height="30" uuid="ec39bd3d-1518-4cb0-9772-fb516175e2e8"/>
				<textFieldExpression><![CDATA["Handelsregister: HRB 728233 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="24" y="29" width="200" height="30" uuid="6be1b77a-d233-4c12-b229-d630f456b52c"/>
				<textFieldExpression><![CDATA["Carl-Benz-Straße 17 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="263" y="29" width="290" height="30" uuid="f468cb21-32be-4e5f-adb0-c0960d0c7905"/>
				<textFieldExpression><![CDATA["IBAN: DE19654500700007620287 "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="24" y="43" width="210" height="30" uuid="acd903c3-7d9c-41b3-83f0-946652ae5470"/>
				<textFieldExpression><![CDATA["D-89597 Munderkingen "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="263" y="43" width="170" height="30" uuid="7e52f0f9-d1e1-41ca-8a75-59fe3dcfe095"/>
				<textFieldExpression><![CDATA["BIC: SBCRDE66XXX "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="664" y="43" width="350" height="30" uuid="9d858186-0497-4178-9030-7844f7ee79bd"/>
				<textFieldExpression><![CDATA["E-Mail: support@worst-behavior.com "]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement style="t s1" x="486" y="43" width="220" height="30" uuid="b5db6763-d6d7-4156-9b2c-0bb739f706c6"/>
				<textFieldExpression><![CDATA["Ust-IDNr. DE284749052 "]]></textFieldExpression>
			</textField>
		</band>
	</pageFooter>
	<summary>
		<band height="42" splitType="Stretch"/>
	</summary>
</jasperReport>

    """
# The testing code would look something like this:
print(transform_jasper_report(xml_content))

Für das textField: <textField>
				<reportElement style="t s8" x="290" y="143" width="416" height="77" uuid="a80924d8-085b-4624-a9c1-f65974565537"/>
				<textFieldExpression><![CDATA[$P{Header}]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 3
Für das textField: <textField>
				<reportElement style="t s1" x="24" y="234" width="630" height="30" uuid="324cbcb0-200c-4bae-a152-ba96901db464"/>
				<textFieldExpression><![CDATA["Worst Behavior GmbH - Carl-Benz-Straße 17 - 89597 Munderkingen "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): AdressHeader
Geben Sie einen Namen für den Feld ein: AdressHeader
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer):
Für das textField: <textField>
				<reportElement style="t s0" x="695" y="267" width="60" height="30" uuid="ba6e7f98-70b2-46ae-af16-dbbd2064368b"/>
				<textFieldExpression><![CDATA["64128 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: DeliveryNumValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="24" y="267" width="300" height="30" uuid="62179801-77db-4644-ad39-889c36532c7c"/>
				<textFieldExpression><![CDATA["Zalando OpCo Polska Sp. z o.o "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="554" y="267" width="190" height="30" uuid="3706f7d1-97a6-4b62-bd20-fe4ee25db15d"/>
				<textFieldExpression><![CDATA["Lieferscheinnummer "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: DeliveryNumName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="24" y="284" width="300" height="30" uuid="40db5959-d6ae-4fec-8c59-e8bd648f7749"/>
				<textFieldExpression><![CDATA["Zalando OpCo Polska Sp. z o.o "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerCompany
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="24" y="302" width="180" height="30" uuid="6a53cccf-23d4-413a-82c5-6c73555494b0"/>
				<textFieldExpression><![CDATA["ul. Innowacyina 1 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerStreet
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="554" y="302" width="60" height="30" uuid="70573571-151c-4bd8-bf1d-c364a77267fb"/>
				<textFieldExpression><![CDATA["Datum "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: DateName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="695" y="302" width="110" height="30" uuid="3be76a89-81e1-417d-9ad2-015bf5b73056"/>
				<textFieldExpression><![CDATA["19.10.2023 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: DateValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="24" y="317" width="150" height="30" uuid="64254185-eea4-4e40-81df-339ff887c153"/>
				<textFieldExpression><![CDATA["95-080 Gluchow "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerCity
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="695" y="317" width="60" height="30" uuid="68b054be-5c5d-437b-bf07-c28de66c2b0c"/>
				<textFieldExpression><![CDATA["10006 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerNumValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="554" y="317" width="130" height="30" uuid="58609327-5433-49fc-a80e-97f046dfa208"/>
				<textFieldExpression><![CDATA["Kundennummer "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: CustomerNumName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s6" x="24" y="367" width="335" height="30" uuid="9734306d-bff4-4e39-a2b4-d132c9a7a47d"/>
				<textFieldExpression><![CDATA["Lieferschein "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: ReportFormsName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="554" y="368" width="60" height="30" uuid="f4717dd5-40cc-4a2e-a374-91efe0abb200"/>
				<textFieldExpression><![CDATA["Seite "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: PageName
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="695" y="368" width="60" height="30" uuid="ad967adc-83a2-4dba-9fab-d18032c1aad5"/>
				<textFieldExpression><![CDATA["1 / 1 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 3
Für das textField: <textField>
				<reportElement style="t s7" x="24" y="421" width="110" height="29" uuid="3050ea14-ad53-4d2f-93d1-4cc74afa4544"/>
				<textFieldExpression><![CDATA["Versandart "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: ShippingMethod
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s2" x="73" y="2" width="70" height="30" uuid="8c6cf1fe-5b8f-4cc0-b874-2d7ab02ca255"/>
				<textFieldExpression><![CDATA["Modell "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: HeaderModel
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s2" x="312" y="2" width="60" height="30" uuid="884b6f75-3319-4dfc-a634-bd3e8c6b55bd"/>
				<textFieldExpression><![CDATA["Farbe "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: HeaderColor
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s2" x="30" y="2" width="40" height="30" uuid="ce9d6b00-4d94-4765-a956-ae84ae906ad6"/>
				<textFieldExpression><![CDATA["Pos "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): HeaderPos
Geben Sie einen Namen für den Feld ein: HeaderPos
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s2" x="818" y="2" width="82" height="30" uuid="26d70d97-e29a-4c54-b970-c9db18f405f8"/>
				<textFieldExpression><![CDATA["Stück "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: HeaderCount
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s2" x="439" y="3" width="80" height="30" uuid="0a40f253-f8a4-4f6b-bbcf-254b81b2475e"/>
				<textFieldExpression><![CDATA["Artikel "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1
Geben Sie einen Namen für den Parameter ein: HeaderArticleNum
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="30" y="28" width="370" height="30" uuid="85a6b313-1e62-4e01-93ec-1246d315e1f9"/>
				<textFieldExpression><![CDATA["PO TT 01/23 WOMEN Zalando PO1416415C "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): ShippingMethodValue
Geben Sie einen Namen für den Feld ein: ShippingMethodValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s0" x="313" y="28" width="110" height="30" uuid="753c8bd2-7c16-4fbb-ae47-edaf6c98c033"/>
				<textFieldExpression><![CDATA["Lodz Auftr "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): CustomerCompany
Geben Sie einen Namen für den Feld ein: CustomerCompany
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="607" y="0" width="20" height="30" uuid="e78ea146-bb08-4d9e-a05a-b21487c97e06"/>
				<textFieldExpression><![CDATA["S "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader2
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="677" y="0" width="20" height="30" uuid="6e71152e-3b79-4a42-af26-c0beafdb244a"/>
				<textFieldExpression><![CDATA["L "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): SizeHeader4
Geben Sie einen Namen für den Feld ein: 2
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="766" y="0" width="40" height="30" uuid="25df0ca0-73a8-40a2-8e1e-27219f8428c7"/>
				<textFieldExpression><![CDATA["3XL "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader7
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="704" y="0" width="30" height="30" uuid="771aae79-0af6-4648-87a0-2e5b22d481da"/>
				<textFieldExpression><![CDATA["XL "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader5
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="731" y="0" width="40" height="30" uuid="10a5e26a-7133-43c3-8d07-dd35eddafb00"/>
				<textFieldExpression><![CDATA["XXL "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader6
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="640" y="0" width="20" height="30" uuid="b7db5d44-93d7-4b54-b042-bf5e89c5993f"/>
				<textFieldExpression><![CDATA["M "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader3
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="563" y="0" width="30" height="30" uuid="04c24e5d-e78f-4b3d-aacb-c1a427ac722e"/>
				<textFieldExpression><![CDATA["XS "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader1
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s4" x="521" y="0" width="40" height="30" uuid="d1ca2b90-2b8c-42dd-8197-e0831e58cd42"/>
				<textFieldExpression><![CDATA["XXS "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: SizeHeader0
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s3" x="444" y="24" width="50" height="30" uuid="18edbb6b-f36c-4125-a868-06efd49c728e"/>
				<textFieldExpression><![CDATA["2311 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleNumValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s3" x="312" y="24" width="100" height="30" uuid="6d1d5c44-ac31-4a98-a18f-427953b8a9a8"/>
				<textFieldExpression><![CDATA["TANGERINE "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleColorValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s3" x="191" y="24" width="120" height="30" uuid="2a4a6700-53ea-4410-9846-4feff88e3c6a"/>
				<textFieldExpression><![CDATA["VALO HOODIE "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleModellNameValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s1" x="843" y="26" width="40" height="30" uuid="2711f049-dc36-4a13-9252-77ea1175ff66"/>
				<textFieldExpression><![CDATA["119 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleCountValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="539" y="26" width="20" height="30" uuid="3769b5f3-b1b7-46e4-9a43-e6b90e300886"/>
				<textFieldExpression><![CDATA["1 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleSizeValue0
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="566" y="26" width="30" height="30" uuid="221e4da2-fcf6-4eaa-87d7-f0816db38184"/>
				<textFieldExpression><![CDATA["27 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleSizeValue1
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="601" y="26" width="30" height="30" uuid="c9c4b024-ae04-4735-a053-bde8ea32450c"/>
				<textFieldExpression><![CDATA["47 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleSizeValue2
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="637" y="26" width="30" height="30" uuid="1811b53a-1e9c-4f41-bc41-ef9e55fb0367"/>
				<textFieldExpression><![CDATA["32 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleSizeValue3
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="671" y="26" width="30" height="30" uuid="a558166e-d5d8-402f-8ef4-656ada1e770a"/>
				<textFieldExpression><![CDATA["12 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleSizeValue4
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="73" y="26" width="80" height="30" uuid="e8ac5007-2a06-4842-8695-b706b33e4cfb"/>
				<textFieldExpression><![CDATA["W2023TT "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticleModellCode
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 1
Für das textField: <textField>
				<reportElement style="t s1" x="48" y="30" width="20" height="30" uuid="5dd42759-ad57-4dca-a008-27ff0895622a"/>
				<textFieldExpression><![CDATA["1 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 2
Geben Sie einen Namen für den Feld ein: ArticlePosValue
Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): 2
Für das textField: <textField>
				<reportElement style="t s1" x="842" y="0" width="40" height="30" uuid="b3dfd69b-4b7c-4dce-82e0-bca39b26cb58"/>
				<textFieldExpression><![CDATA["272 "]]></textFieldExpression>
			</textField>
Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): 1

# DataBase Inserts

In [ ]:
import random

def generate_sql_inserts(num_articles=5, max_headers=13):
    # Centralized definitions
    VALUE_COLUMNS = [f"value{i}" for i in range(max_headers)]

    def generate_table_columns():
        return ", ".join([f"{col} VARCHAR(10)" for col in VALUE_COLUMNS])

    # Table cleanup and creation
    init_statements = [
        "DROP TABLE IF EXISTS ArticleDataRows;",
        "DROP TABLE IF EXISTS Articles;",
        "DROP TABLE IF EXISTS Company;",
        "CREATE TABLE Company (id INT PRIMARY KEY, name VARCHAR(255) NOT NULL);",
        "CREATE TABLE Articles (id INT PRIMARY KEY, article_name VARCHAR(255) NOT NULL, article_rows_data_values_sum INT NOT NULL, article_row_count_max INT NOT NULL, article_row_count INT NOT NULL);",
        f"CREATE TABLE ArticleDataRows (id INT PRIMARY KEY, article_id INT, row_num INT, row_name VARCHAR(10), row_data_values_sum INT NOT NULL, data_count INT NOT NULL, {generate_table_columns()}, FOREIGN KEY (article_id) REFERENCES Articles(id));"
    ]

    company_statements = ["INSERT INTO Company (id, name) VALUES (1, 'CompanyName');"]
    article_statements = []
    row_statements = []
    article_data_row_id = 1  # To keep track of the unique id for ArticleDataRows table

    for article_id in range(1, num_articles + 1):
        article_name = f'Artikel {article_id}'
        article_row_count_max = 3
        article_row_count = random.randint(1, article_row_count_max)
        article_rows_data_values_sum = 0

        for row_num in range(1, article_row_count + 1):
            row_name = f'Row {chr(64 + row_num)}:'
            data_count = random.randint(1, max_headers)
            values = [str(random.randint(0, 29)) for _ in range(data_count)] + ['0'] * (max_headers - data_count)
            row_data_values_sum = sum([int(value) for value in values[:data_count]])
            article_rows_data_values_sum += row_data_values_sum

            values_str = "', '".join(values)
            row_statements.append(
                f"INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, {', '.join(VALUE_COLUMNS)}) VALUES ({article_data_row_id}, {article_id}, {row_num}, '{row_name}', {row_data_values_sum}, {data_count}, '{values_str}');"
            )
            article_data_row_id += 1

        article_statements.append(
            f"INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES ({article_id}, '{article_name}', {article_rows_data_values_sum}, {article_row_count_max}, {article_row_count});"
        )

    return '\n'.join(init_statements + company_statements + article_statements + row_statements)

generated_sql = generate_sql_inserts()
print(generated_sql)

DROP TABLE IF EXISTS ArticleDataRows;
DROP TABLE IF EXISTS Articles;
DROP TABLE IF EXISTS Company;
CREATE TABLE Company (id INT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE Articles (id INT PRIMARY KEY, article_name VARCHAR(255) NOT NULL, article_rows_data_values_sum INT NOT NULL, article_row_count_max INT NOT NULL, article_row_count INT NOT NULL);
CREATE TABLE ArticleDataRows (id INT PRIMARY KEY, article_id INT, row_num INT, row_name VARCHAR(10), row_data_values_sum INT NOT NULL, data_count INT NOT NULL, value0 VARCHAR(10), value1 VARCHAR(10), value2 VARCHAR(10), value3 VARCHAR(10), value4 VARCHAR(10), value5 VARCHAR(10), value6 VARCHAR(10), value7 VARCHAR(10), value8 VARCHAR(10), value9 VARCHAR(10), value10 VARCHAR(10), value11 VARCHAR(10), value12 VARCHAR(10), FOREIGN KEY (article_id) REFERENCES Articles(id));
INSERT INTO Company (id, name) VALUES (1, 'CompanyName');
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (1, 'Artikel 1', 181, 3, 1);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (2, 'Artikel 2', 169, 3, 3);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (3, 'Artikel 3', 48, 3, 1);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (4, 'Artikel 4', 435, 3, 3);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (5, 'Artikel 5', 330, 3, 3);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (1, 1, 1, 'Row A:', 181, 13, '28', '27', '4', '2', '2', '5', '8', '24', '24', '26', '27', '1', '3');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (2, 2, 1, 'Row A:', 111, 11, '3', '5', '14', '8', '8', '12', '15', '2', '13', '23', '8', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (3, 2, 2, 'Row B:', 32, 2, '6', '26', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (4, 2, 3, 'Row C:', 26, 1, '26', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (5, 3, 1, 'Row A:', 48, 6, '3', '9', '10', '1', '16', '9', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (6, 4, 1, 'Row A:', 107, 8, '13', '4', '12', '25', '16', '18', '12', '7', '0', '0', '0', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (7, 4, 2, 'Row B:', 177, 13, '21', '11', '10', '24', '1', '8', '12', '14', '28', '7', '11', '22', '8');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (8, 4, 3, 'Row C:', 151, 13, '9', '22', '9', '0', '17', '4', '5', '7', '8', '16', '7', '26', '21');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (9, 5, 1, 'Row A:', 175, 12, '22', '0', '15', '10', '27', '17', '11', '13', '20', '16', '17', '7', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (10, 5, 2, 'Row B:', 107, 7, '2', '21', '19', '18', '12', '26', '9', '0', '0', '0', '0', '0', '0');
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12) VALUES (11, 5, 3, 'Row C:', 48, 2, '28', '20', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');

In [ ]:
import random

def generate_sql_inserts(num_articles=5, max_headers=13):
    # Centralized definitions
    VALUE_COLUMNS = [f"value{i}" for i in range(max_headers)]
    ADDITIONAL_COLUMNS = {
        "SizeHeader0": "VARCHAR(10)",
        "SizeHeader1": "VARCHAR(10)",
        "SizeHeader2": "VARCHAR(10)",
        "SizeHeader3": "VARCHAR(10)",
        "SizeHeader4": "VARCHAR(10)",
        "SizeHeader5": "VARCHAR(10)",
        "SizeHeader6": "VARCHAR(10)",
        "SizeHeader7": "VARCHAR(10)",
        "ArticleNumValue": "INT",
        "ArticleColorValue": "VARCHAR(20)",
        "ArticleModellNameValue": "VARCHAR(50)",
        "ArticleCountValue": "INT",
        "ArticleSizeValue0": "INT",
        "ArticleSizeValue1": "INT",
        "ArticleSizeValue2": "INT",
        "ArticleSizeValue3": "INT",
        "ArticleSizeValue4": "INT",
        "ArticleSizeValue5": "INT",
        "ArticleSizeValue6": "INT",
        "ArticleSizeValue7": "INT",
        "ArticleModellCode": "VARCHAR(50)",
        "ArticlePosValue": "INT"
    }

    def generate_table_columns():
        basic_columns = ", ".join([f"{col} VARCHAR(10)" for col in VALUE_COLUMNS])
        additional_columns = ", ".join([f"{col} {type}" for col, type in ADDITIONAL_COLUMNS.items()])
        return basic_columns + ", " + additional_columns

    # Table cleanup and creation
    init_statements = [
        "DROP TABLE IF EXISTS ArticleDataRows;",
        "DROP TABLE IF EXISTS Articles;",
        "DROP TABLE IF EXISTS Company;",
        "CREATE TABLE Company (id INT PRIMARY KEY, name VARCHAR(255) NOT NULL);",
        "CREATE TABLE Articles (id INT PRIMARY KEY, article_name VARCHAR(255) NOT NULL, article_rows_data_values_sum INT NOT NULL, article_row_count_max INT NOT NULL, article_row_count INT NOT NULL);",
        f"CREATE TABLE ArticleDataRows (id INT PRIMARY KEY, article_id INT, row_num INT, row_name VARCHAR(10), row_data_values_sum INT NOT NULL, data_count INT NOT NULL, {generate_table_columns()}, FOREIGN KEY (article_id) REFERENCES Articles(id));"
    ]

    company_statements = ["INSERT INTO Company (id, name) VALUES (1, 'CompanyName');"]
    article_statements = []
    row_statements = []
    article_data_row_id = 1  # To keep track of the unique id for ArticleDataRows table

    for article_id in range(1, num_articles + 1):
        article_name = f'Artikel {article_id}'
        article_row_count_max = 3
        article_row_count = random.randint(1, article_row_count_max)
        article_rows_data_values_sum = 0

        for row_num in range(1, article_row_count + 1):
            row_name = f'Row {chr(64 + row_num)}:'
            data_count = random.randint(1, max_headers)
            values = [str(random.randint(0, 29)) for _ in range(data_count)] + ['0'] * (max_headers - data_count)
            row_data_values_sum = sum([int(value) for value in values[:data_count]])
            article_rows_data_values_sum += row_data_values_sum

            additional_values = {
                "SizeHeader0": f"'Size{random.randint(1, 9)}'",
                "SizeHeader1": f"'Size{random.randint(1, 9)}'",
                #... and so on for other SizeHeader fields
                "ArticleNumValue": str(random.randint(1000, 9999)),
                "ArticleColorValue": f"'Color{random.randint(1, 5)}'",
                "ArticleModellNameValue": f"'Model{random.randint(1, 5)}'",
                "ArticleCountValue": str(random.randint(1, 10)),
                "ArticleSizeValue0": str(random.randint(28, 38)),
                #... and so on for other ArticleSizeValue fields
                "ArticleModellCode": f"'Code{random.randint(100, 500)}'",
                "ArticlePosValue": str(random.randint(1, 5))
            }

            all_columns = VALUE_COLUMNS + list(additional_values.keys())
            all_values = values + list(additional_values.values())
            values_str = ", ".join(all_values)

            row_statements.append(
                f"INSERT INTO ArticleDataRows ({', '.join(all_columns)}) VALUES ({article_data_row_id}, {article_id}, {row_num}, '{row_name}', {row_data_values_sum}, {data_count}, {values_str});"
            )
            article_data_row_id += 1

        article_statements.append(
            f"INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES ({article_id}, '{article_name}', {article_rows_data_values_sum}, {article_row_count_max}, {article_row_count});"
        )

    return '\n'.join(init_statements + company_statements + article_statements + row_statements)

generated_sql = generate_sql_inserts()
print(generated_sql)

DROP TABLE IF EXISTS ArticleDataRows;
DROP TABLE IF EXISTS Articles;
DROP TABLE IF EXISTS Company;
CREATE TABLE Company (id INT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE Articles (id INT PRIMARY KEY, article_name VARCHAR(255) NOT NULL, article_rows_data_values_sum INT NOT NULL, article_row_count_max INT NOT NULL, article_row_count INT NOT NULL);
CREATE TABLE ArticleDataRows (id INT PRIMARY KEY, article_id INT, row_num INT, row_name VARCHAR(10), row_data_values_sum INT NOT NULL, data_count INT NOT NULL, value0 VARCHAR(10), value1 VARCHAR(10), value2 VARCHAR(10), value3 VARCHAR(10), value4 VARCHAR(10), value5 VARCHAR(10), value6 VARCHAR(10), value7 VARCHAR(10), value8 VARCHAR(10), value9 VARCHAR(10), value10 VARCHAR(10), value11 VARCHAR(10), value12 VARCHAR(10), SizeHeader0 VARCHAR(10), SizeHeader1 VARCHAR(10), SizeHeader2 VARCHAR(10), SizeHeader3 VARCHAR(10), SizeHeader4 VARCHAR(10), SizeHeader5 VARCHAR(10), SizeHeader6 VARCHAR(10), SizeHeader7 VARCHAR(10), ArticleNumValue INT, ArticleColorValue VARCHAR(20), ArticleModellNameValue VARCHAR(50), ArticleCountValue INT, ArticleSizeValue0 INT, ArticleSizeValue1 INT, ArticleSizeValue2 INT, ArticleSizeValue3 INT, ArticleSizeValue4 INT, ArticleSizeValue5 INT, ArticleSizeValue6 INT, ArticleSizeValue7 INT, ArticleModellCode VARCHAR(50), ArticlePosValue INT, FOREIGN KEY (article_id) REFERENCES Articles(id));
INSERT INTO Company (id, name) VALUES (1, 'CompanyName');
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (1, 'Artikel 1', 77, 3, 1);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (2, 'Artikel 2', 256, 3, 2);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (3, 'Artikel 3', 254, 3, 2);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (4, 'Artikel 4', 183, 3, 3);
INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count) VALUES (5, 'Artikel 5', 54, 3, 1);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (1, 1, 1, 'Row A:', 77, 6, 17, 4, 11, 24, 12, 9, 0, 0, 0, 0, 0, 0, 0, 'Size6', 'Size6', 2410, 'Color2', 'Model4', 10, 29, 'Code500', 4);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (2, 2, 1, 'Row A:', 112, 10, 1, 2, 26, 13, 4, 19, 12, 1, 7, 27, 0, 0, 0, 'Size9', 'Size2', 5522, 'Color1', 'Model1', 1, 35, 'Code283', 1);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (3, 2, 2, 'Row B:', 144, 12, 9, 10, 23, 1, 12, 22, 12, 23, 2, 4, 7, 19, 0, 'Size2', 'Size3', 3117, 'Color1', 'Model4', 4, 32, 'Code369', 5);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (4, 3, 1, 'Row A:', 180, 10, 0, 19, 27, 20, 27, 7, 23, 10, 19, 28, 0, 0, 0, 'Size7', 'Size6', 9834, 'Color3', 'Model4', 2, 30, 'Code166', 3);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (5, 3, 2, 'Row B:', 74, 3, 26, 22, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Size4', 'Size4', 6788, 'Color2', 'Model2', 10, 38, 'Code460', 3);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (6, 4, 1, 'Row A:', 85, 8, 2, 0, 29, 6, 5, 19, 3, 21, 0, 0, 0, 0, 0, 'Size1', 'Size5', 7714, 'Color2', 'Model2', 3, 29, 'Code181', 2);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (7, 4, 2, 'Row B:', 50, 4, 7, 3, 18, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Size9', 'Size1', 7611, 'Color4', 'Model5', 3, 30, 'Code144', 2);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (8, 4, 3, 'Row C:', 48, 3, 11, 10, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Size7', 'Size1', 4210, 'Color5', 'Model5', 3, 32, 'Code211', 4);
INSERT INTO ArticleDataRows (value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleModellCode, ArticlePosValue) VALUES (9, 5, 1, 'Row A:', 54, 3, 1, 28, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Size5', 'Size2', 2304, 'Color5', 'Model4', 9, 31, 'Code432', 5);

In [ ]:
import random

def generate_article_data_row_inserts(num_rows=5):
    inserts = []

    for i in range(num_rows):
        # Generate random values for the columns
        id_value = i + 1
        article_id = random.randint(1, 1)  # Assuming we have articles from 1 to 10
        row_num = random.randint(1, 5)  # Assuming maximum 5 rows per article
        row_name = f'Row {chr(64 + row_num)}:'
        data_count = random.randint(1, 13)
        values = [str(random.randint(0, 1234)) for _ in range(data_count)] + ['NULL'] * (13 - data_count)
        row_data_values_sum = sum([int(value) for value in values if value != 'NULL'])

        size_headers = [f"'XL{random.randint(1, 9)}'" for _ in range(8)]
        article_num_value = random.randint(1000, 9999)
        article_color_value = f"'Color{random.randint(1, 5)}'"
        article_model_name_value = f"'Model{random.randint(1, 5)}'"
        article_count_value = random.randint(1, 10)
        article_size_values = [str(random.randint(60, 1234)) for _ in range(8)]
        article_model_code = f"'Code{random.randint(100, 500)}'"
        article_pos_value = i + 1

        # Construct the INSERT statement
        insert_statement = f"INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES ({id_value}, {article_id}, {row_num}, '{row_name}', {row_data_values_sum}, {data_count}, {', '.join(values)}, {', '.join(size_headers)}, {article_num_value}, {article_color_value}, {article_model_name_value}, {article_count_value}, {', '.join(article_size_values)}, {article_model_code}, {article_pos_value});"

        inserts.append(insert_statement)

    return '\n'.join(inserts)

num_of_rows = 50  # You can change this value to the desired number of rows
print(generate_article_data_row_inserts(num_of_rows))

INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (1, 1, 1, 'Row A:', 1275, 3, 417, 445, 413, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL1', 'XL7', 'XL8', 'XL8', 'XL8', 'XL5', 'XL6', 'XL1', 1931, 'Color4', 'Model1', 8, 361, 258, 699, 530, 249, 194, 591, 266, 'Code270', 1);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (2, 1, 4, 'Row D:', 5813, 9, 24, 1150, 186, 971, 468, 395, 748, 778, 1093, NULL, NULL, NULL, NULL, 'XL8', 'XL9', 'XL3', 'XL1', 'XL2', 'XL8', 'XL6', 'XL7', 4925, 'Color5', 'Model3', 10, 353, 127, 354, 927, 250, 688, 1193, 780, 'Code448', 2);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (3, 1, 2, 'Row B:', 3661, 7, 100, 735, 840, 872, 19, 722, 373, NULL, NULL, NULL, NULL, NULL, NULL, 'XL6', 'XL8', 'XL4', 'XL4', 'XL8', 'XL4', 'XL3', 'XL4', 9846, 'Color2', 'Model2', 10, 273, 1031, 899, 66, 164, 661, 481, 219, 'Code363', 3);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (4, 1, 3, 'Row C:', 612, 1, 612, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL5', 'XL1', 'XL5', 'XL4', 'XL2', 'XL9', 'XL3', 'XL8', 8337, 'Color4', 'Model2', 5, 384, 894, 553, 1124, 1095, 714, 384, 595, 'Code224', 4);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (5, 1, 4, 'Row D:', 7258, 13, 325, 603, 933, 756, 902, 184, 227, 261, 1015, 175, 597, 771, 509, 'XL9', 'XL7', 'XL6', 'XL5', 'XL3', 'XL4', 'XL5', 'XL7', 8426, 'Color1', 'Model4', 3, 172, 933, 588, 870, 416, 543, 546, 1044, 'Code240', 5);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (6, 1, 3, 'Row C:', 6175, 11, 352, 1140, 215, 727, 59, 343, 449, 748, 459, 793, 890, NULL, NULL, 'XL6', 'XL3', 'XL9', 'XL8', 'XL6', 'XL9', 'XL7', 'XL9', 6057, 'Color4', 'Model4', 1, 476, 378, 823, 397, 460, 67, 1120, 400, 'Code130', 6);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (7, 1, 1, 'Row A:', 779, 1, 779, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL2', 'XL5', 'XL5', 'XL6', 'XL6', 'XL8', 'XL9', 'XL4', 2996, 'Color5', 'Model2', 10, 885, 842, 657, 1167, 760, 904, 657, 962, 'Code152', 7);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (8, 1, 4, 'Row D:', 10308, 13, 1060, 976, 1182, 666, 1041, 935, 1089, 513, 233, 742, 309, 1026, 536, 'XL5', 'XL6', 'XL7', 'XL6', 'XL6', 'XL4', 'XL9', 'XL5', 4995, 'Color1', 'Model5', 2, 1135, 1138, 433, 946, 477, 738, 523, 883, 'Code226', 8);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (9, 1, 3, 'Row C:', 5012, 7, 322, 653, 1058, 781, 480, 1157, 561, NULL, NULL, NULL, NULL, NULL, NULL, 'XL9', 'XL1', 'XL4', 'XL1', 'XL5', 'XL2', 'XL7', 'XL1', 2613, 'Color1', 'Model3', 3, 889, 144, 172, 782, 1161, 297, 295, 1119, 'Code189', 9);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (10, 1, 1, 'Row A:', 1080, 1, 1080, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL6', 'XL4', 'XL6', 'XL5', 'XL2', 'XL5', 'XL5', 'XL6', 8598, 'Color2', 'Model4', 3, 939, 561, 856, 435, 714, 276, 549, 582, 'Code499', 10);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (11, 1, 5, 'Row E:', 3775, 7, 154, 1233, 727, 207, 235, 954, 265, NULL, NULL, NULL, NULL, NULL, NULL, 'XL3', 'XL6', 'XL6', 'XL3', 'XL1', 'XL6', 'XL2', 'XL3', 5605, 'Color2', 'Model4', 3, 964, 151, 627, 541, 742, 924, 646, 1013, 'Code468', 11);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (12, 1, 1, 'Row A:', 6466, 12, 212, 457, 502, 995, 960, 74, 343, 272, 649, 1163, 685, 154, NULL, 'XL5', 'XL7', 'XL2', 'XL4', 'XL4', 'XL8', 'XL2', 'XL1', 1622, 'Color4', 'Model1', 4, 549, 764, 798, 1116, 827, 1197, 751, 180, 'Code262', 12);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (13, 1, 3, 'Row C:', 601, 2, 81, 520, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL8', 'XL7', 'XL5', 'XL6', 'XL1', 'XL6', 'XL8', 'XL4', 4286, 'Color2', 'Model3', 5, 1211, 1058, 1143, 486, 404, 378, 540, 508, 'Code453', 13);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (14, 1, 3, 'Row C:', 2966, 5, 636, 1190, 305, 160, 675, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL7', 'XL4', 'XL8', 'XL8', 'XL1', 'XL3', 'XL1', 'XL5', 6587, 'Color1', 'Model2', 1, 1175, 787, 198, 970, 962, 234, 1020, 578, 'Code264', 14);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (15, 1, 5, 'Row E:', 393, 1, 393, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL4', 'XL4', 'XL6', 'XL6', 'XL6', 'XL8', 'XL9', 'XL6', 9819, 'Color4', 'Model2', 7, 808, 1211, 841, 1172, 324, 946, 263, 471, 'Code386', 15);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (16, 1, 4, 'Row D:', 1453, 2, 286, 1167, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL5', 'XL7', 'XL4', 'XL4', 'XL8', 'XL3', 'XL5', 'XL6', 2780, 'Color3', 'Model2', 10, 1206, 113, 1212, 99, 394, 368, 233, 306, 'Code132', 16);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (17, 1, 2, 'Row B:', 7481, 11, 173, 993, 1166, 610, 1203, 436, 41, 151, 984, 745, 979, NULL, NULL, 'XL7', 'XL5', 'XL4', 'XL2', 'XL2', 'XL1', 'XL6', 'XL5', 1972, 'Color2', 'Model1', 5, 1121, 1178, 425, 73, 539, 147, 309, 1164, 'Code407', 17);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (18, 1, 4, 'Row D:', 6731, 12, 83, 436, 56, 1102, 1088, 940, 289, 1200, 155, 200, 330, 852, NULL, 'XL2', 'XL7', 'XL9', 'XL7', 'XL2', 'XL5', 'XL5', 'XL9', 2790, 'Color5', 'Model5', 6, 720, 191, 510, 148, 405, 164, 216, 274, 'Code447', 18);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (19, 1, 2, 'Row B:', 3338, 7, 973, 119, 899, 87, 438, 344, 478, NULL, NULL, NULL, NULL, NULL, NULL, 'XL1', 'XL7', 'XL3', 'XL1', 'XL3', 'XL7', 'XL4', 'XL9', 2943, 'Color5', 'Model5', 9, 379, 1115, 172, 1100, 670, 704, 1119, 985, 'Code166', 19);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (20, 1, 5, 'Row E:', 5407, 11, 1132, 678, 90, 209, 369, 273, 62, 526, 511, 404, 1153, NULL, NULL, 'XL4', 'XL2', 'XL8', 'XL4', 'XL9', 'XL4', 'XL3', 'XL5', 4669, 'Color4', 'Model2', 1, 899, 337, 473, 70, 755, 721, 1031, 203, 'Code352', 20);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (21, 1, 3, 'Row C:', 4627, 7, 321, 511, 496, 744, 945, 750, 860, NULL, NULL, NULL, NULL, NULL, NULL, 'XL6', 'XL9', 'XL1', 'XL4', 'XL2', 'XL7', 'XL8', 'XL8', 4642, 'Color3', 'Model3', 7, 787, 754, 1126, 91, 1007, 392, 369, 345, 'Code304', 21);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (22, 1, 5, 'Row E:', 6198, 11, 427, 1046, 423, 830, 850, 803, 47, 909, 356, 462, 45, NULL, NULL, 'XL9', 'XL6', 'XL2', 'XL8', 'XL3', 'XL4', 'XL2', 'XL8', 2315, 'Color5', 'Model3', 4, 616, 120, 482, 590, 690, 964, 958, 1142, 'Code145', 22);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (23, 1, 4, 'Row D:', 2591, 4, 776, 235, 472, 1108, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XL4', 'XL2', 'XL2', 'XL7', 'XL3', 'XL9', 'XL3', 'XL4', 6758, 'Color2', 'Model3', 3, 1162, 357, 969, 935, 463, 886, 1087, 973, 'Code287', 23);
INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, SizeHeader0, SizeHeader1, SizeHeader2, SizeHeader3, SizeHeader4, SizeHeader5, SizeHeader6, SizeHeader7, ArticleNumValue, ArticleColorValue, ArticleModellNameValue, ArticleCountValue, ArticleSizeValue0, ArticleSizeValue1, ArticleSizeValue2, ArticleSizeValue3, ArticleSizeValue4, ArticleSizeValue5, ArticleSizeValue6, ArticleSizeValue7, ArticleModellCode, ArticlePosValue) VALUES (24, 1, 2, 'Row B:', 5317, 11, 564, 385, 280, 839, 771, 242, 88, 139, 734, 539, 736, NULL, NULL, 'XL3', 'XL8', 'XL7', 'XL1', 'XL5', 'XL9', 'XL8', 'XL1', 6131, 'Color4', 'Model4', 3, 526, 199, 623, 490, 1102, 467, 1208, 862, 'Code153', 24);

# Task
Restructure the provided Jupyter notebook according to the following plan:
- Add a short introductory text at the beginning.
- Structure the notebook with the following sections using markdown headings:
    - README
    - 1. Konstanten eintragen: HTML-Seitengröße und JasperReport-Größe
    - 2. HTML-Code übergeben und speichern
    - 3. Code-Sektionen
    - 4–x. Diverse Aufrufe und Ausgaben
- Ensure all existing code and markdown content is placed under the appropriate new headings.
- Preserve all existing Python functions and their functionality.

## Modify markdown cells

### Subtask:
Add introductory text and update existing markdown cells to reflect the new structure.

**Reasoning**:
The subtask requires adding new markdown cells and modifying existing ones to structure the notebook. I will use `code_block` to generate the necessary markdown content for the new cells and update the existing markdown cells as specified in the instructions. This will address steps 1-14.

In [1]:
%%markdown
This notebook provides a set of Python functions and examples for converting HTML content, specifically designed for representing page layouts from PDFs, into JasperReports XML format. It includes steps for handling positional data, styling, and structuring the output to be compatible with JasperReports.

This notebook provides a set of Python functions and examples for converting HTML content, specifically designed for representing page layouts from PDFs, into JasperReports XML format. It includes steps for handling positional data, styling, and structuring the output to be compatible with JasperReports.

**Reasoning**:
I have added the introductory text. Now I need to add the markdown cells for the new headings and modify the existing markdown cells as per the instructions. This will complete steps 3-14.

In [2]:
%%markdown
# README

This notebook outlines the process of converting HTML output (typically from PDF-to-HTML conversion) into JasperReports XML format. The goal is to preserve the layout and content as accurately as possible, enabling the generation of printable reports.

The steps include:
1. Defining the dimensions of the original HTML page and the target JasperReport.
2. Providing the HTML code to be converted.
3. Utilizing Python functions to process the HTML, extract relevant information (like text content, positions, and styles), and generate JasperReports elements.
4. Demonstrating the usage of the functions with examples and displaying the generated XML snippets.
5. Including examples of generating SQL insert statements for populating a database with data that can be used as the data source for the JasperReport.

To use this notebook:
- Follow the sections sequentially.
- Replace the example HTML content and dimensions with your own data.
- Run the code cells to perform the conversion and see the output.
- Adapt the functions as needed for specific HTML structures or JasperReports requirements.

# README

This notebook outlines the process of converting HTML output (typically from PDF-to-HTML conversion) into JasperReports XML format. The goal is to preserve the layout and content as accurately as possible, enabling the generation of printable reports.

The steps include:
1. Defining the dimensions of the original HTML page and the target JasperReport.
2. Providing the HTML code to be converted.
3. Utilizing Python functions to process the HTML, extract relevant information (like text content, positions, and styles), and generate JasperReports elements.
4. Demonstrating the usage of the functions with examples and displaying the generated XML snippets.
5. Including examples of generating SQL insert statements for populating a database with data that can be used as the data source for the JasperReport.

To use this notebook:
- Follow the sections sequentially.
- Replace the example HTML content and dimensions with your own data.
- Run the code cells to perform the conversion and see the output.
- Adapt the functions as needed for specific HTML structures or JasperReports requirements.

**Reasoning**:
I have added the introductory text and the README section. Now I will add the markdown cells for section 1 and 2, update the existing markdown cells to section 3, and add a markdown cell for section 4. This will complete the restructuring of the markdown cells as requested in the subtask.

In [3]:
%%markdown
# 1. Konstanten eintragen: HTML-Seitengröße und JasperReport-Größe

Hier werden die Abmessungen der ursprünglichen HTML-Seite (abgeleitet von der PDF-Seite) und die Zielabmessungen für den JasperReport definiert. Diese Konstanten sind entscheidend für die korrekte Umrechnung der Positionen der Elemente.

# 1. Konstanten eintragen: HTML-Seitengröße und JasperReport-Größe

Hier werden die Abmessungen der ursprünglichen HTML-Seite (abgeleitet von der PDF-Seite) und die Zielabmessungen für den JasperReport definiert. Diese Konstanten sind entscheidend für die korrekte Umrechnung der Positionen der Elemente.

**Reasoning**:
I have added the introductory text and the first two section headings. Now I will add the markdown cell for section 2 and update the existing markdown cells to section 3.

In [4]:
%%markdown
# 2. HTML-Code übergeben und speichern

In diesem Abschnitt wird der rohe HTML-Code der Seite bereitgestellt, der in JasperReports XML umgewandelt werden soll. Dieser Code wird in einer Variable gespeichert, um von den nachfolgenden Funktionen verarbeitet zu werden.

# 2. HTML-Code übergeben und speichern

In diesem Abschnitt wird der rohe HTML-Code der Seite bereitgestellt, der in JasperReports XML umgewandelt werden soll. Dieser Code wird in einer Variable gespeichert, um von den nachfolgenden Funktionen verarbeitet zu werden.

**Reasoning**:
I have added the introductory text and the first two section headings. Now I need to update the existing markdown cells to section 3 and add the markdown cell for section 4.

In [5]:
%%markdown
# 3. Code-Sektionen

Dieser Abschnitt enthält die Python-Funktionen, die für die Umwandlung des HTML-Codes in JasperReports XML verwendet werden. Jede Funktion übernimmt eine spezifische Aufgabe im Konvertierungsprozess.

# 3. Code-Sektionen

Dieser Abschnitt enthält die Python-Funktionen, die für die Umwandlung des HTML-Codes in JasperReports XML verwendet werden. Jede Funktion übernimmt eine spezifische Aufgabe im Konvertierungsprozess.

**Reasoning**:
I have added the introductory text and the first three section headings. Now I will add the markdown cell for section 4 to complete the required markdown structure as per the instructions.

In [6]:
%%markdown
# 4–x. Diverse Aufrufe und Ausgaben

In den folgenden Zellen werden die zuvor definierten Funktionen auf den bereitgestellten HTML-Code angewendet. Die Ergebnisse der einzelnen Schritte des Konvertierungsprozesses sowie die generierten JasperReports XML-Snippets werden angezeigt.

# 4–x. Diverse Aufrufe und Ausgaben

In den folgenden Zellen werden die zuvor definierten Funktionen auf den bereitgestellten HTML-Code angewendet. Die Ergebnisse der einzelnen Schritte des Konvertierungsprozesses sowie die generierten JasperReports XML-Snippets werden angezeigt.

## Modify code cells

### Subtask:
Adjust existing code cells to fit the new structure, ensuring functions and variables are still accessible.

**Reasoning**:
Define the constants for HTML and JasperReport dimensions.

In [7]:
# 1. Konstanten eintragen: HTML-Seitengröße und JasperReport-Größe

# HTML page dimensions (from PDF conversion)
html_width = 1210
html_height = 825

# Target JasperReport dimensions (e.g., A4 Landscape)
# A4 Landscape dimensions in pixels (at 72 dpi)
jasper_width = 842
jasper_height = 595

# Scaling factors for position and font size adjustments
x_scale_factor = jasper_width / html_width
y_scale_factor = jasper_height / html_height
font_scale_factor = jasper_width / html_width # You might want to adjust this based on desired font scaling

# Offsets for fine-tuning positions after scaling
x_offset = -16 # Example offset
y_offset = -44 # Example offset

**Reasoning**:
Provide the HTML content to be converted and store it in a variable.

In [8]:
# 2. HTML-Code übergeben und speichern

html_content_bottom_pos = """<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta charset="utf-8" />
</head>

<body style="margin: 0;">

<div id="p1" style="overflow: hidden; position: relative; background-color: white; width: 1210px; height: 825px;">

    <!-- Begin shared CSS values -->
    <style class="shared-css" type="text/css" >
        .t {
            transform-origin: bottom left;
            z-index: 2;
            position: absolute;
            white-space: pre;
            overflow: visible;
            line-height: 1.5;
        }
        .text-container {
            white-space: pre;
        }
        @supports (-webkit-touch-callout: none) {
            .text-container {
                white-space: normal;
            }
        }
    </style>
    <!-- End shared CSS values -->


    <!-- Begin inline CSS -->
    <style type="text/css" >

        #t1_1{left:18px;bottom:804px;letter-spacing:0.14px;}
        #t2_1{left:128px;bottom:804px;}
        #t3_1{left:165px;bottom:804px;letter-spacing:0.15px;}
        #t4_1{left:266px;bottom:804px;letter-spacing:0.15px;}
        #t5_1{left:394px;bottom:804px;letter-spacing:0.17px;}
        #t6_1{left:18px;bottom:804px;letter-spacing:0.14px;}
        #t7_1{left:128px;bottom:804px;}
        #t8_1{left:165px;bottom:804px;letter-spacing:0.15px;}
        #t9_1{left:266px;bottom:804px;letter-spacing:0.15px;}
        #ta_1{left:394px;bottom:804px;letter-spacing:0.16px;}
        #tb_1{left:110px;bottom:804px;}
        #tc_1{left:156px;bottom:804px;}
        #td_1{left:101px;bottom:777px;}
        #te_1{left:697px;bottom:777px;letter-spacing:0.17px;}
        #tf_1{left:18px;bottom:777px;letter-spacing:0.17px;}
        #tg_1{left:119px;bottom:777px;letter-spacing:0.17px;}
        #th_1{left:770px;bottom:777px;letter-spacing:0.17px;}
        #ti_1{left:770px;bottom:777px;letter-spacing:0.17px;}
        #tj_1{left:862px;bottom:777px;}
        #tk_1{left:862px;bottom:777px;letter-spacing:9.39px;word-spacing:-9.17px;}
        #tl_1{left:889px;bottom:777px;}
        #tm_1{left:953px;bottom:777px;letter-spacing:0.17px;}
        #tn_1{left:953px;bottom:777px;letter-spacing:0.17px;}
        #to_1{left:990px;bottom:777px;letter-spacing:0.17px;}
        #tp_1{left:770px;bottom:763px;letter-spacing:0.16px;}
        #tq_1{left:953px;bottom:763px;letter-spacing:0.11px;}
        #tr_1{left:990px;bottom:763px;letter-spacing:0.17px;}
        #ts_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tt_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tu_1{left:266px;bottom:749px;letter-spacing:0.17px;}
        #tv_1{left:358px;bottom:749px;letter-spacing:0.17px;}
        #tw_1{left:358px;bottom:749px;letter-spacing:0.17px;}
        #tx_1{left:431px;bottom:749px;letter-spacing:0.17px;}
        #ty_1{left:431px;bottom:749px;letter-spacing:3.26px;word-spacing:-3.06px;}
        #tz_1{left:468px;bottom:749px;letter-spacing:0.17px;}
        #t10_1{left:477px;bottom:749px;}
        #t11_1{left:422px;bottom:749px;}
        #t12_1{left:422px;bottom:749px;}
        #t13_1{left:422px;bottom:749px;}
        #t14_1{left:788px;bottom:708px;letter-spacing:0.17px;}
        #t15_1{left:18px;bottom:694px;letter-spacing:0.15px;}
        #t16_1{left:413px;bottom:694px;letter-spacing:0.17px;}
        #t17_1{left:165px;bottom:694px;letter-spacing:0.17px;}
        #t18_1{left:165px;bottom:694px;letter-spacing:0.15px;}
        #t19_1{left:413px;bottom:681px;letter-spacing:0.17px;}
        #t1a_1{left:18px;bottom:681px;letter-spacing:0.17px;}
        #t1b_1{left:541px;bottom:681px;letter-spacing:0.17px;}
        #t1c_1{left:413px;bottom:667px;letter-spacing:0.14px;}
        #t1d_1{left:523px;bottom:667px;}
        #t1e_1{left:18px;bottom:667px;}
        #t1f_1{left:541px;bottom:667px;letter-spacing:0.17px;}
        #t1g_1{left:413px;bottom:653px;letter-spacing:0.14px;}
        #t1h_1{left:523px;bottom:653px;}
        #t1i_1{left:18px;bottom:653px;letter-spacing:0.17px;}
        #t1j_1{left:541px;bottom:653px;letter-spacing:0.17px;}
        #t1k_1{left:413px;bottom:639px;letter-spacing:0.15px;}
        #t1l_1{left:523px;bottom:639px;}
        #t1m_1{left:413px;bottom:626px;letter-spacing:0.17px;}
        #t1n_1{left:18px;bottom:626px;letter-spacing:0.17px;}
        #t1o_1{left:18px;bottom:626px;letter-spacing:0.16px;}
        #t1p_1{left:541px;bottom:626px;letter-spacing:0.17px;}
        #t1q_1{left:18px;bottom:612px;letter-spacing:0.17px;}
        #t1r_1{left:165px;bottom:612px;letter-spacing:0.14px;}
        #t1s_1{left:18px;bottom:598px;letter-spacing:0.17px;}
        #t1t_1{left:110px;bottom:598px;letter-spacing:0.17px;}
        #t1u_1{left:147px;bottom:598px;letter-spacing:0.17px;}
        #t1v_1{left:202px;bottom:598px;letter-spacing:0.16px;}
        #t1w_1{left:633px;bottom:584px;letter-spacing:0.17px;}
        #t1x_1{left:18px;bottom:584px;letter-spacing:0.17px;}
        #t1y_1{left:770px;bottom:584px;letter-spacing:0.17px;}
        #t1z_1{left:770px;bottom:584px;letter-spacing:0.17px;}
        #t20_1{left:18px;bottom:571px;letter-spacing:0.15px;}
        #t21_1{left:633px;bottom:571px;letter-spacing:0.17px;}
        #t22_1{left:147px;bottom:571px;letter-spacing:0.17px;}
        #t23_1{left:147px;bottom:571px;letter-spacing:0.17px;}
        #t24_1{left:770px;bottom:571px;letter-spacing:0.17px;}
        #t25_1{left:18px;bottom:557px;letter-spacing:0.15px;}
        #t26_1{left:128px;bottom:557px;}
        #t27_1{left:633px;bottom:557px;letter-spacing:0.17px;}
        #t28_1{left:147px;bottom:557px;letter-spacing:0.17px;}
        #t29_1{left:770px;bottom:557px;letter-spacing:0.17px;}
        #t2a_1{left:18px;bottom:543px;letter-spacing:0.15px;}
        #t2b_1{left:633px;bottom:543px;letter-spacing:0.17px;}
        #t2c_1{left:193px;bottom:543px;letter-spacing:0.17px;}
        #t2d_1{left:770px;bottom:543px;letter-spacing:0.17px;}
        #t2e_1{left:9px;bottom:502px;letter-spacing:0.17px;}
        #t2f_1{left:9px;bottom:502px;letter-spacing:0.17px;}
        #t2g_1{left:9px;bottom:488px;}
        #t2h_1{left:183px;bottom:488px;letter-spacing:1.93px;word-spacing:-1.74px;}
        #t2i_1{left:9px;bottom:474px;}
        #t2j_1{left:183px;bottom:474px;letter-spacing:1.72px;word-spacing:-1.53px;}
        #t2k_1{left:9px;bottom:461px;letter-spacing:0.17px;}
        #t2l_1{left:9px;bottom:461px;letter-spacing:0.17px;}
        #t2m_1{left:9px;bottom:419px;letter-spacing:0.17px;}
        #t2n_1{left:275px;bottom:419px;}
        #t2o_1{left:339px;bottom:419px;}
        #t2p_1{left:403px;bottom:419px;}
        #t2q_1{left:468px;bottom:419px;}
        #t2r_1{left:532px;bottom:419px;}
        #t2s_1{left:596px;bottom:419px;}
        #t2t_1{left:660px;bottom:419px;}
        #t2u_1{left:724px;bottom:419px;}
        #t2v_1{left:788px;bottom:419px;}
        #t2w_1{left:853px;bottom:419px;}
        #t2x_1{left:917px;bottom:419px;}
        #t2y_1{left:981px;bottom:419px;}
        #t2z_1{left:1045px;bottom:419px;}
        #t30_1{left:1109px;bottom:419px;}
        #t31_1{left:1173px;bottom:419px;}
        #t32_1{left:28px;bottom:406px;letter-spacing:0.17px;}
        #t33_1{left:238px;bottom:406px;letter-spacing:0.17px;}
        #t34_1{left:9px;bottom:392px;letter-spacing:0.17px;}
        #t35_1{left:211px;bottom:392px;}
        #t36_1{left:275px;bottom:392px;}
        #t37_1{left:339px;bottom:392px;}
        #t38_1{left:403px;bottom:392px;}
        #t39_1{left:28px;bottom:378px;letter-spacing:0.17px;}
        #t3a_1{left:174px;bottom:378px;letter-spacing:0.17px;}
        #t3b_1{left:816px;bottom:364px;letter-spacing:0.17px;}
        #t3c_1{left:1027px;bottom:364px;letter-spacing:0.17px;}
        #t3d_1{left:1027px;bottom:364px;letter-spacing:0.19px;word-spacing:9.17px;}

        .s0{font-size:15px;font-family:Courier;color:#000;}
    </style>
    <!-- End inline CSS -->

    <!-- Begin page background -->
    <div id="pg1Overlay" style="width:100%; height:100%; position:absolute; z-index:1; background-color:rgba(0,0,0,0); -webkit-user-select: none;"></div>
    <div id="pg1" style="-webkit-user-select: none;"><object width="1210" height="825" data="1/1.svg" type="image/svg+xml" id="pdf1" style="width:1210px; height:825px; -moz-transform:scale(1); z-index: 0;"></object></div>
    <!-- End page background -->


    <!-- Begin text definitions (Positioned/styled in CSS) -->
    <div class="text-container"><span id="t1_1" class="t s0">Seite: </span><span id="t2_1" class="t s0">( </span><span id="t3_1" class="t s0">) *Kopie* </span><span id="t4_1" class="t s0">LIEFERSCHEIN </span><span id="t5_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="t6_1" class="t s0">Seite: </span><span id="t7_1" class="t s0">( </span><span id="t8_1" class="t s0">) *Kopie* </span><span id="t9_1" class="t s0">LIEFERSCHEIN </span><span id="ta_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="tb_1" class="t s0">1 </span><span id="tc_1" class="t s0">1 </span>
        <span id="td_1" class="t s0">/ </span><span id="te_1" class="t s0">Nummer: </span><span id="tf_1" class="t s0">28.09.23 </span><span id="tg_1" class="t s0">15:22 </span><span id="th_1" class="t s0">3034948 </span><span id="ti_1" class="t s0">3034948 </span><span id="tj_1" class="t s0">1 </span><span id="tk_1" class="t s0">1 1 </span><span id="tl_1" class="t s0">1 </span><span id="tm_1" class="t s0">120 </span><span id="tn_1" class="t s0">120 31 </span><span id="to_1" class="t s0">31 </span>
        <span id="tp_1" class="t s0">Auftrag Ind SF </span><span id="tq_1" class="t s0">LO </span><span id="tr_1" class="t s0">Bt </span>
        <span id="ts_1" class="t s0">Liefernr. </span><span id="tt_1" class="t s0">_________ </span><span id="tu_1" class="t s0">Liefernr. 3034948 </span><span id="tv_1" class="t s0">_______ </span><span id="tw_1" class="t s0">3034948 001 </span><span id="tx_1" class="t s0">___ </span><span id="ty_1" class="t s0">001 1 </span><span id="tz_1" class="t s0">__ </span><span id="t10_1" class="t s0">1 </span><span id="t11_1" class="t s0">/ </span><span id="t12_1" class="t s0">_ </span><span id="t13_1" class="t s0">/ </span>
        <span id="t14_1" class="t s0">30349480010112031 </span>
        <span id="t15_1" class="t s0">Kundennummer: </span><span id="t16_1" class="t s0">Streutermin : </span><span id="t17_1" class="t s0">28260001 </span><span id="t18_1" class="t s0">28260001 </span>
        <span id="t19_1" class="t s0">Auftragsdat.: </span><span id="t1a_1" class="t s0">Young Fashion Behrendt </span><span id="t1b_1" class="t s0">28.09.23 </span>
        <span id="t1c_1" class="t s0">Marke </span><span id="t1d_1" class="t s0">: </span><span id="t1e_1" class="t s0">. </span><span id="t1f_1" class="t s0">50 ***Mc Percy </span>
        <span id="t1g_1" class="t s0">Thema </span><span id="t1h_1" class="t s0">: </span><span id="t1i_1" class="t s0">Holmpassage, Holm 39 </span><span id="t1j_1" class="t s0">KATAGABRUF Katag Abrufe </span>
        <span id="t1k_1" class="t s0">Prospekt </span><span id="t1l_1" class="t s0">: </span>
        <span id="t1m_1" class="t s0">Auftragstyp : </span><span id="t1n_1" class="t s0">D-24937 Flensburg </span><span id="t1o_1" class="t s0">D-24937 Flensburg </span><span id="t1p_1" class="t s0">291 Katag Lagerauftrag Anschlusshaus </span>
        <span id="t1q_1" class="t s0">Verdichtung...: VERSA </span><span id="t1r_1" class="t s0">VERSA </span>
        <span id="t1s_1" class="t s0">Versandart</span><span id="t1t_1" class="t s0">....</span><span id="t1u_1" class="t s0">: 200 Hängend: DKS / Liegend: DPD-unfr. </span><span id="t1v_1" class="t s0">Hängend: DKS / Liegend: DPD-unfr. </span>
        <span id="t1w_1" class="t s0">Kundentermin : </span><span id="t1x_1" class="t s0">Denim Jeans </span><span id="t1y_1" class="t s0">28.09.23 </span><span id="t1z_1" class="t s0">28.09.23 </span>
        <span id="t20_1{left:18px;bottom:571px;letter-spacing:0.15px;}">Modellnummer: </span><span id="t21_1{left:633px;bottom:571px;letter-spacing:0.17px;}">Kundenauftrag: </span><span id="t22_1{left:147px;bottom:571px;letter-spacing:0.17px;}">210000943 </span><span id="t23_1{left:147px;bottom:571px;letter-spacing:0.17px;}">210000943 </span><span id="t24_1{left:770px;bottom:571px;letter-spacing:0.17px;}">3034948 </span>
        <span id="t25_1{left:18px;bottom:557px;letter-spacing:0.15px;}">Lagerplatz </span><span id="t26_1{left:128px;bottom:557px;}">: </span><span id="t27_1{left:633px;bottom:557px;letter-spacing:0.17px;}">Art.Nr. Lief.: </span><span id="t28_1{left:147px;bottom:557px;letter-spacing:0.17px;}">P10 </span><span id="t29_1{left:770px;bottom:557px;letter-spacing:0.17px;}">700 NOS </span>
        <span id="t2a_1{left:18px;bottom:543px;letter-spacing:0.15px;}">Bereich: </span><span id="t2b_1{left:633px;bottom:543px;letter-spacing:0.17px;}">Art.Bez.Lief.: </span><span id="t2c_1{left:193px;bottom:543px;letter-spacing:0.17px;}">2100 Katag, HAKA I / Hosen </span><span id="t2d_1{left:770px;bottom:543px;letter-spacing:0.17px;}">605 5 P. Regular </span>
        <span id="t2e_1{left:9px;bottom:502px;letter-spacing:0.17px;}">================================================================================================================================== </span><span id="t2f_1{left:9px;bottom:502px;letter-spacing:0.17px;}">================================================================================================================================== </span>
        <span id="t2g_1{left:9px;bottom:488px;}">A </span><span id="t2h_1{left:183px;bottom:488px;letter-spacing:1.93px;word-spacing:-1.74px;}">31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 </span>
        <span id="t2i_1{left:9px;bottom:474px;}">B </span><span id="t2j_1{left:183px;bottom:474px;letter-spacing:1.72px;word-spacing:-1.53px;}">33/34 34/34 36/34 38/34 40/34 </span>
        <span id="t2k_1{left:9px;bottom:461px;letter-spacing:0.17px;}">================================================================================================================================== </span><span id="t2l_1{left:9px;bottom:461px;letter-spacing:0.17px;}">================================================================================================================================== </span>
        <span id="t2m_1{left:9px;bottom:419px;letter-spacing:0.17px;}">A BLUE STONE </span><span id="t2n_1{left:275px;bottom:419px;}">1 </span><span id="t2o_1{left:339px;bottom:419px;}">1 </span><span id="t2p_1{left:403px;bottom:419px;}">1 </span><span id="t2q_1{left:468px;bottom:419px;}">1 </span><span id="t2r_1{left:532px;bottom:419px;}">1 </span><span id="t2s_1{left:596px;bottom:419px;}">1 </span><span id="t2t_1{left:660px;bottom:419px;}">1 </span><span id="t2u_1{left:724px;bottom:419px;}">1 </span><span id="t2v_1{left:788px;bottom:419px;}">1 </span><span id="t2w_1{left:853px;bottom:419px;}">1 </span><span id="t2x_1{left:917px;bottom:419px;}">1 </span><span id="t2y_1{left:981px;bottom:419px;}">1 </span><span id="t2z_1{left:1045px;bottom:419px;}">1 </span><span id="t30_1{left:1109px;bottom:419px;}">1 </span><span id="t31_1{left:1173px;bottom:419px;}">1 </span>
        <span id="t32_1{left:28px;bottom:406px;letter-spacing:0.17px;}">600 </span><span id="t33_1{left:238px;bottom:406px;letter-spacing:0.17px;}">______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ </span>
        <span id="t34_1{left:9px;bottom:392px;letter-spacing:0.17px;}">B BLUE STONE </span><span id="t35_1{left:211px;bottom:392px;}">1 </span><span id="t36_1{left:275px;bottom:392px;}">1 </span><span id="t37_1{left:339px;bottom:392px;}">1 </span><span id="t38_1{left:403px;bottom:392px;}">1 </span>
        <span id="t39_1{left:28px;bottom:378px;letter-spacing:0.17px;}">600 </span><span id="t3a_1{left:174px;bottom:378px;letter-spacing:0.17px;}">______ ______ ______ ______ </span>
        <span id="t3b_1{left:816px;bottom:364px;letter-spacing:0.17px;}">Stück gesamt : </span><span id="t3c_1{left:1027px;bottom:364px;letter-spacing:0.17px;}">19 </span><span id="t3d_1{left:1027px;bottom:364px;letter-spacing:0.19px;word-spacing:9.17px;}">19 STK </span></div>
    <!-- End text definitions -->


</div>
</body>
</html>
"""

html_styles_input = """.s0{font-size:15px;font-family:Courier;color:#000;}
"""

**Reasoning**:
Define all the necessary Python functions for the HTML to JasperReport conversion and data generation.

In [9]:
# 3. Code-Sektionen

import re
from bs4 import BeautifulSoup
import xml.etree.ElementTree as ET
import random

def convert_bottom_to_top(width: int, height: int, convertedtext: str) -> str:
    # Use regex to find all 'bottom' properties and their values
    def replace_bottom_to_top(match):
        bottom_value = float(match.group(1))
        top_value = height - bottom_value
        return f"top:{str(round(top_value))}px"

    # Replace 'bottom' with the calculated 'top' value
    updated_text = re.sub(r'bottom:(\d+\.?\d*)px', replace_bottom_to_top, convertedtext)
    return updated_text

def generate_jasper_textfields_from_html_multi_style(converthtml: str) -> str:
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(converthtml, 'html.parser')

    # Extract all styles from all style tags
    styles = {}
    for style_content in soup.select('style'):
        if style_content.string:  # Check if style content is not None
            for style_definition in style_content.string.split('}'):
                if '{' in style_definition:
                    parts = style_definition.split('{')
                    if len(parts) == 2:
                        selector, properties = parts
                        selector = selector.strip()
                        properties = properties.strip()
                        styles[selector] = properties

    # Process each span to extract the text and associated styles
    jasper_textfields = ""
    for span in soup.select('span.t'):
        span_id = span.attrs.get('id', '')
        span_text = span.string
        span_class = " ".join(span.attrs.get('class', []))

        # Extract style associated with this span using its id
        style_definition = styles.get(f"#{span_id}", '')
        x_match = re.search(r'left:(\d+)px', style_definition)
        y_match = re.search(r'top:(\d+)px', style_definition)
        x_pos = x_match.group(1) if x_match else '0' # Default to '0' if not found
        y_pos = y_match.group(1) if y_match else '0' # Default to '0' if not found


        # Generate the JasperReport XML for this text span
        jasper_textfields += f"""
            <textField>
                <reportElement style="{span_class}" x="{x_pos}" y="{y_pos}" width="{10 * len(str(span_text))}" height="30" />
                <textFieldExpression><![CDATA["{span_text}"]]></textFieldExpression>
            </textField>
        """

    return jasper_textfields

def extract_jasper_styles_from_html_styles(html_styles: str) -> str:
    # Regular expression patterns for extracting font family and font size
    font_family_pattern = re.compile(r'font-family:([^;]+)')
    font_size_pattern = re.compile(r'font-size:(\d+)px')

    jasper_styles = ""

    # Split the styles by "}" to get individual style definitions
    for style_definition in html_styles.split('}'):
        # Check if style definition is not empty
        if style_definition.strip():
            # Extract class name (e.g., s0, s1, etc.)
            class_name = style_definition.split('{')[0].strip().replace('.', '')

            # Extract font family and font size
            font_family = font_family_pattern.search(style_definition)
            font_size = font_size_pattern.search(style_definition)

            if font_family and font_size:
                jasper_styles += f'<style name="t {class_name}" fontName="{font_family.group(1).strip()}" fontSize="{font_size.group(1)}"/>\n'

    return jasper_styles

# Re-defining the improved function
def sort_textfields_by_y_etree_v3(xml_content: str) -> str:
    # Placeholder for CDATA
    placeholder = "PLACEHOLDER_FOR_CDATA"

    # Convert CDATA sections to placeholder
    xml_content = xml_content.replace("<![CDATA[", placeholder + "[")
    xml_content = xml_content.replace("]]>", "]" + placeholder)

    # Define namespace
    ns = {'jr': 'http://jasperreports.sourceforge.net/jasperreports'}
    ET.register_namespace('', ns['jr'])

    # Parse the XML content with the namespace
    root = ET.fromstring(xml_content)

    # For each parent in the XML
    for parent in root.findall(".//*"):
        # Extract textField elements and their y coordinates
        textfields = []
        for elem in parent.findall("jr:textField", ns):
             report_element = elem.find(".//jr:reportElement", ns)
             if report_element is not None and 'y' in report_element.attrib:
                 textfields.append((elem, int(report_element.attrib['y'])))


        # If there are no textFields, continue to the next parent
        if not textfields:
            continue

        # Sort the textFields based on y coordinate
        textfields.sort(key=lambda x: x[1])

        # Remove the original textFields from parent
        for tf, _ in textfields:
            parent.remove(tf)

        # Add sorted textField elements back to parent
        for tf, _ in textfields:
            parent.append(tf)

    # Convert the root element back to string and restore CDATA sections
    output = ET.tostring(root, encoding='unicode')
    output = output.replace(placeholder + "[", "<![CDATA[")
    output = output.replace("]" + placeholder, "]]>")

    return output

def adjust_jasperreport_positions_regex(xml_content: str, x_offset=0, y_offset=0) -> str:

    # Define a function to update x and y values using regex
    def repl(match):
        if match.group(1) == "x":
            return 'x="{}"'.format(int(match.group(2)) + x_offset)
        if match.group(1) == "y":
            return 'y="{}"'.format(int(match.group(2)) + y_offset)
        return match.group(0)

    # Apply the regex replacement
    adjusted_xml = re.sub(r'(\b[x|y])="(\d+)"', repl, xml_content)
    return adjusted_xml

def adjust_jasperreport_positions_corrected(xml_content: str, x_scale_factor=1.0, y_scale_factor=1.0, font_scale_factor=1.0, height_scale_factor=1.0, width_scale_factor=1.0) -> str:

    def repl(match):
        attribute = match.group(1)
        value = match.group(2)

        # Scale the value if necessary
        if attribute == "x":
            value = str(round(float(value) * x_scale_factor))
        elif attribute == "y":
            value = str(round(float(value) * y_scale_factor))
        elif attribute == "fontSize":
            value = str(round(float(value) * font_scale_factor))
        elif attribute == "height":
            value = str(round(float(value) * height_scale_factor))
        elif attribute == "width":
            value = str(round(float(value) * width_scale_factor))

        return attribute + '="' + value + '"'

    # Correcting the regex pattern to capture decimal values as well
    adjusted_xml = re.sub(r'(\bx|y|fontSize|height|width)="([\d.]+)"', repl, xml_content)
    return adjusted_xml

def adjust_jasperreport_positions_regex_selective(xml_content: str, x_scale_factor=1.0, y_scale_factor=1.0, font_scale_factor=1.0, height_scale_factor=1.0, width_scale_factor=1.0, isTextFieldScaling=True, scaleAll=False) -> str:

    def repl(match):
        # Check if the current match is inside a <textField> element
        preceding_text = xml_content[:match.start(0)]
        is_inside_textfield = "<textField>" in preceding_text.split("</textField>")[-1]

        attribute = match.group(1)
        value = match.group(2)


        # Determine if the current match should be scaled
        if scaleAll:
            should_scale = True
        else:
            should_scale = (is_inside_textfield and isTextFieldScaling) or (not is_inside_textfield and not isTextFieldScaling)

        # Scale the value if necessary
        if should_scale:
            if attribute == "x":
                value = str(round(int(value) * x_scale_factor))
            elif attribute == "y":
                value = str(round(int(value) * y_scale_factor))
            elif attribute == "fontSize":
                value = str(round(int(value) * font_scale_factor))
            elif attribute == "height":
                value = str(round(int(value) * height_scale_factor))
            elif attribute == "width":
                value = str(round(int(value) * width_scale_factor))

        return attribute + '="' + value + '"'

    adjusted_xml = re.sub(r'(\bx|y|fontSize|height|width)="(\d+)"', repl, xml_content)
    return adjusted_xml

def transform_jasper_report(xml_content: str) -> str:
    added_parameters = []
    added_fields = []

    skip_all = False  # global variable to check if the user has chosen the "Skip All" option

    # Diese Funktion ersetzt das textField anhand der Auswahl des Benutzers
    def replace_text_field(match):
        nonlocal skip_all
        # Wenn skip_all True ist, geben Sie das textField so zurück, wie es ist
        if skip_all:
            return match.group(0)

        # textField-Inhalt extrahieren
        text_field_content = match.group(0)

        # Fragen Sie den Benutzer nach einer Wahl
        print("Für das textField:", text_field_content)
        choice = input("Wählen Sie eine Aktion (1: Parameter [default], 2: Feld, 3: Überspringen, 4: Alles überspringen): ")

        # Wenn keine Auswahl getroffen wird, wird "Parameter" als Standardwert festgelegt
        if choice.strip() == '':
            choice = '1'

        # Wenn der Benutzer "Alles überspringen" wählt
        if choice == '4':
            skip_all = True
            return text_field_content

        # Wenn der Benutzer überspringt
        if choice == '3':
            return text_field_content

        # Extrahieren Sie den String aus textFieldExpression
        expression_match = re.search(r'<textFieldExpression><!\[CDATA\[(.*?)\]\]></textFieldExpression>', text_field_content, re.DOTALL)
        if not expression_match:
            return text_field_content
        extracted_string = expression_match.group(1).strip() # strip whitespace

        # Fragen Sie nach dem Namen
        name = input(f"Geben Sie einen Namen für den {'Parameter' if choice == '1' else 'Feld'} ein: ")

        # Fragen Sie nach dem Datentyp
        data_type = input(f"Wählen Sie den Datentyp (1: java.lang.String [default], 2: java.lang.Integer): ")
        if data_type.strip() == '' or data_type == '1':
            data_type = 'java.lang.String'
        else:
            data_type = 'java.lang.Integer'

        # Erstellen Sie Parameter oder Feld basierend auf der Wahl des Benutzers
        if choice == '1':
            param_str = (
                f'<parameter name="{name}" class="{data_type}">\n'
                f'\t<defaultValueExpression><![CDATA[{extracted_string}]]></defaultValueExpression>\n'
                f'</parameter>'
            )
            added_parameters.append(param_str)
        else:
            field_str = f'<field name="{name}" class="{data_type}">\n\t<defaultValueExpression><![CDATA[{extracted_string}]]></defaultValueExpression>\n</field>'
            added_fields.append(field_str)

        # Erstellen Sie den Ersatzstring
        prefix = 'P' if choice == '1' else 'F'
        replacement = f'<textFieldExpression><![CDATA[${prefix}{{{name}}}]]></textFieldExpression>'

        # Ersetzen Sie den Inhalt mit re.sub()
        new_text_field_content = re.sub(r'<textFieldExpression><!\[CDATA\[(.*?)\]\]></textFieldExpression>', replacement, text_field_content, re.DOTALL)

        return new_text_field_content

    # Replace all textFields in the XML content
    modified_xml = re.sub(r'(<textField>.*?</textField>)', replace_text_field, xml_content, flags=re.DOTALL)

    # Find the insertion point for parameters (before the first <queryString> or at the end of styles)
    params_insertion_point_match = re.search(r'<queryString', modified_xml)
    if params_insertion_point_match:
         params_insertion_point = params_insertion_point_match.start()
         modified_xml = modified_xml[:params_insertion_point] + "\n\n<!-- Added Parameter Definitions -->\n" + "\n".join(added_parameters) + "\n" + modified_xml[params_insertion_point:]
    else:
        # If no queryString, find the end of styles
        styles_end_match = re.search(r'</style>', modified_xml)
        if styles_end_match:
            styles_end_point = styles_end_match.end()
            modified_xml = modified_xml[:styles_end_point] + "\n\n<!-- Added Parameter Definitions -->\n" + "\n".join(added_parameters) + "\n" + modified_xml[styles_end_point:]
        else:
             # If no styles or query string, add at the end of the report tag
             report_end_match = re.search(r'</jasperReport>', modified_xml)
             if report_end_match:
                report_end_point = report_end_match.start()
                modified_xml = modified_xml[:report_end_point] + "\n\n<!-- Added Parameter Definitions -->\n" + "\n".join(added_parameters) + "\n" + modified_xml[report_end_point:]
             else:
                modified_xml += "\n\n<!-- Added Parameter Definitions -->\n"
                modified_xml += "\n".join(added_parameters)


    # Find the insertion point for fields (after the </queryString>)
    fields_insertion_point_match = re.search(r'</queryString>', modified_xml)
    if fields_insertion_point_match:
        fields_insertion_point = fields_insertion_point_match.end()
        modified_xml = modified_xml[:fields_insertion_point] + "\n\n<!-- Added Field Definitions -->\n" + "\n".join(added_fields) + "\n" + modified_xml[fields_insertion_point:]
    else:
        # If no queryString, add after the parameters
        modified_xml += "\n\n<!-- Added Field Definitions -->\n"
        modified_xml += "\n".join(added_fields)


    return modified_xml


def generate_sql_inserts_articles(num_articles=5, max_headers=13):
    # Centralized definitions
    VALUE_COLUMNS = [f"value{i}" for i in range(max_headers)]
    ADDITIONAL_ARTICLE_COLUMNS = {
        "ArticleNumValue": "INT",
        "ArticleColorValue": "VARCHAR(20)",
        "ArticleModellNameValue": "VARCHAR(50)",
        "ArticleCountValue": "INT",
        "ArticleModellCode": "VARCHAR(50)",
    }

    def generate_article_table_columns():
        return ", ".join([f"{col} {type}" for col, type in ADDITIONAL_ARTICLE_COLUMNS.items()])


    # Table cleanup and creation
    init_statements = [
        "DROP TABLE IF EXISTS ArticleDataRows;",
        "DROP TABLE IF EXISTS Articles;",
        "DROP TABLE IF EXISTS Company;",
        "CREATE TABLE Company (id INT PRIMARY KEY, name VARCHAR(255) NOT NULL);",
        f"CREATE TABLE Articles (id INT PRIMARY KEY, article_name VARCHAR(255) NOT NULL, article_rows_data_values_sum INT NOT NULL, article_row_count_max INT NOT NULL, article_row_count INT NOT NULL, {generate_article_table_columns()});",
        f"CREATE TABLE ArticleDataRows (id INT PRIMARY KEY, article_id INT, row_num INT, row_name VARCHAR(10), row_data_values_sum INT NOT NULL, data_count INT NOT NULL, {', '.join([f'{col} VARCHAR(10)' for col in VALUE_COLUMNS])}, FOREIGN KEY (article_id) REFERENCES Articles(id));"
    ]


    company_statements = ["INSERT INTO Company (id, name) VALUES (1, 'CompanyName');"]
    article_statements = []
    row_statements = []
    article_data_row_id = 1  # To keep track of the unique id for ArticleDataRows table

    for article_id in range(1, num_articles + 1):
        article_name = f'Artikel {article_id}'
        article_row_count_max = 3
        article_row_count = random.randint(1, article_row_count_max)
        article_rows_data_values_sum = 0

        # Generate additional article values
        additional_article_values = {
             "ArticleNumValue": str(random.randint(1000, 9999)),
             "ArticleColorValue": f"'Color{random.randint(1, 5)}'",
             "ArticleModellNameValue": f"'Model{random.randint(1, 5)}'",
             "ArticleCountValue": str(random.randint(1, 10)),
             "ArticleModellCode": f"'Code{random.randint(100, 500)}'",
         }
        article_columns_str = ", ".join(list(ADDITIONAL_ARTICLE_COLUMNS.keys()))
        article_values_str = ", ".join(list(additional_article_values.values()))

        for row_num in range(1, article_row_count + 1):
            row_name = f'Row {chr(64 + row_num)}:'
            data_count = random.randint(1, max_headers)
            values = [str(random.randint(0, 29)) for _ in range(data_count)] + ['NULL'] * (max_headers - data_count)
            row_data_values_sum = sum([int(value) for value in values if value != 'NULL'])
            article_rows_data_values_sum += row_data_values_sum


            values_str = ", ".join(values)

            row_statements.append(
                f"INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, {', '.join(VALUE_COLUMNS)}) VALUES ({article_data_row_id}, {article_id}, {row_num}, '{row_name}', {row_data_values_sum}, {data_count}, {values_str});"
            )
            article_data_row_id += 1

        article_statements.append(
            f"INSERT INTO Articles (id, article_name, article_rows_data_values_sum, article_row_count_max, article_row_count, {article_columns_str}) VALUES ({article_id}, '{article_name}', {article_rows_data_values_sum}, {article_row_count_max}, {article_row_count}, {article_values_str});"
        )


    return '\n'.join(init_statements + company_statements + article_statements + row_statements)

def generate_sql_inserts_article_data_rows(num_rows=50):
    inserts = []

    # Centralized definitions
    VALUE_COLUMNS = [f"value{i}" for i in range(13)]
    ADDITIONAL_COLUMNS = {
        "SizeHeader0": "VARCHAR(10)",
        "SizeHeader1": "VARCHAR(10)",
        "SizeHeader2": "VARCHAR(10)",
        "SizeHeader3": "VARCHAR(10)",
        "SizeHeader4": "VARCHAR(10)",
        "SizeHeader5": "VARCHAR(10)",
        "SizeHeader6": "VARCHAR(10)",
        "SizeHeader7": "VARCHAR(10)",
        "ArticleNumValue": "INT",
        "ArticleColorValue": "VARCHAR(20)",
        "ArticleModellNameValue": "VARCHAR(50)",
        "ArticleCountValue": "INT",
        "ArticleSizeValue0": "INT",
        "ArticleSizeValue1": "INT",
        "ArticleSizeValue2": "INT",
        "ArticleSizeValue3": "INT",
        "ArticleSizeValue4": "INT",
        "ArticleSizeValue5": "INT",
        "ArticleSizeValue6": "INT",
        "ArticleSizeValue7": "INT",
        "ArticleModellCode": "VARCHAR(50)",
        "ArticlePosValue": "INT"
    }


    for i in range(num_rows):
        # Generate random values for the columns
        id_value = i + 1
        article_id = random.randint(1, 1)  # Assuming we have articles from 1 to 1
        row_num = random.randint(1, 5)  # Assuming maximum 5 rows per article
        row_name = f'Row {chr(64 + row_num)}:'
        data_count = random.randint(1, 13)
        values = [str(random.randint(0, 1234)) for _ in range(data_count)] + ['NULL'] * (13 - data_count)
        row_data_values_sum = sum([int(value) for value in values if value != 'NULL'])

        size_headers = [f"'XL{random.randint(1, 9)}'" for _ in range(8)]
        article_num_value = random.randint(1000, 9999)
        article_color_value = f"'Color{random.randint(1, 5)}'"
        article_model_name_value = f"'Model{random.randint(1, 5)}'"
        article_count_value = random.randint(1, 10)
        article_size_values = [str(random.randint(60, 1234)) for _ in range(8)]
        article_model_code = f"'Code{random.randint(100, 500)}'"
        article_pos_value = i + 1

        # Construct the INSERT statement
        insert_statement = f"INSERT INTO ArticleDataRows (id, article_id, row_num, row_name, row_data_values_sum, data_count, {', '.join(VALUE_COLUMNS)}, {', '.join(ADDITIONAL_COLUMNS.keys())}) VALUES ({id_value}, {article_id}, {row_num}, '{row_name}', {row_data_values_sum}, {data_count}, {', '.join(values)}, {', '.join(size_headers)}, {article_num_value}, {article_color_value}, {article_model_name_value}, {article_count_value}, {', '.join(article_size_values)}, {article_model_code}, {article_pos_value});"

        inserts.append(insert_statement)

    return '\n'.join(inserts)

**Reasoning**:
Apply the defined functions in sequence to convert the HTML to JasperReport XML and generate SQL inserts, then print the results.

In [10]:
# 4–x. Diverse Aufrufe und Ausgaben

# Convert bottom positions to top positions
html_content_top_pos = convert_bottom_to_top(html_width, html_height, html_content_bottom_pos)
print("--- HTML with Top Positions ---")
print(html_content_top_pos)

# Extract JasperReport text fields from HTML with top positions
jasper_textfields_xml = generate_jasper_textfields_from_html_multi_style(html_content_top_pos)
print("\n--- Generated JasperReport TextFields ---")
print(jasper_textfields_xml)

# Extract JasperReport styles from HTML styles
jasper_styles_xml = extract_jasper_styles_from_html_styles(html_styles_input)
print("\n--- Generated JasperReport Styles ---")
print(jasper_styles_xml)

# Construct a sample JasperReport XML structure to test sorting and adjusting
# This is a minimal structure to contain the generated textfields and styles
sample_jasper_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
              name="ConvertedReport" pageWidth="{jasper_width}" pageHeight="{jasper_height}" orientation="Portrait" columnWidth="{jasper_width - 40}"
              leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20">
    {jasper_styles_xml}
    <queryString>
        <![CDATA[]]>
    </queryString>
    <detail>
        <band height="{jasper_height - 40}">
            {jasper_textfields_xml}
        </band>
    </detail>
</jasperReport>
"""
print("\n--- Sample JasperReport XML before Sorting ---")
print(sample_jasper_xml)

# Sort the textfields by Y coordinate
sorted_jasper_xml = sort_textfields_by_y_etree_v3(sample_jasper_xml)
print("\n--- JasperReport XML after Sorting by Y ---")
print(sorted_jasper_xml)


# Adjust positions and scale based on defined factors and offsets
# Applying scaling first, then offset
scaled_and_offset_xml = adjust_jasperreport_positions_corrected(sorted_jasper_xml, x_scale_factor, y_scale_factor, font_scale_factor, 1.0, 1.0) # Scale positions and font
final_adjusted_xml = adjust_jasperreport_positions_regex(scaled_and_offset_xml, x_offset, y_offset) # Apply offset

print("\n--- Final Adjusted JasperReport XML ---")
print(final_adjusted_xml)

# Generate SQL inserts for Articles
generated_sql_articles = generate_sql_inserts_articles(num_articles=5)
print("\n--- Generated SQL Inserts for Articles ---")
print(generated_sql_articles)

# Generate SQL inserts for ArticleDataRows
generated_sql_article_data_rows = generate_sql_inserts_article_data_rows(num_rows=50)
print("\n--- Generated SQL Inserts for ArticleDataRows ---")
print(generated_sql_article_data_rows)

--- HTML with Top Positions ---
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta charset="utf-8" />
</head>

<body style="margin: 0;">

<div id="p1" style="overflow: hidden; position: relative; background-color: white; width: 1210px; height: 825px;">

    <!-- Begin shared CSS values -->
    <style class="shared-css" type="text/css" >
        .t {
            transform-origin: bottom left;
            z-index: 2;
            position: absolute;
            white-space: pre;
            overflow: visible;
            line-height: 1.5;
        }
        .text-container {
            white-space: pre;
        }
        @supports (-webkit-touch-callout: none) {
            .text-container {
                white-space: normal;
            }
        }
    </style>
    <!-- End shared CSS values -->


    <!-- Begin inline CSS -->
    <style type="text/css" >

        #t1_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t2_1{left:128px;top:21px;}
        #t3_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t4_1{left:266px;top:21px;letter-spacing:0.15px;}
        #t5_1{left:394px;top:21px;letter-spacing:0.17px;}
        #t6_1{left:18px;top:21px;letter-spacing:0.14px;}
        #t7_1{left:128px;top:21px;}
        #t8_1{left:165px;top:21px;letter-spacing:0.15px;}
        #t9_1{left:266px;top:21px;letter-spacing:0.15px;}
        #ta_1{left:394px;top:21px;letter-spacing:0.16px;}
        #tb_1{left:110px;top:21px;}
        #tc_1{left:156px;top:21px;}
        #td_1{left:101px;top:48px;}
        #te_1{left:697px;top:48px;letter-spacing:0.17px;}
        #tf_1{left:18px;top:48px;letter-spacing:0.17px;}
        #tg_1{left:119px;top:48px;letter-spacing:0.17px;}
        #th_1{left:770px;top:48px;letter-spacing:0.17px;}
        #ti_1{left:770px;top:48px;letter-spacing:0.17px;}
        #tj_1{left:862px;top:48px;}
        #tk_1{left:862px;top:48px;letter-spacing:9.39px;word-spacing:-9.17px;}
        #tl_1{left:889px;top:48px;}
        #tm_1{left:953px;top:48px;letter-spacing:0.17px;}
        #tn_1{left:953px;top:48px;letter-spacing:0.17px;}
        #to_1{left:990px;top:48px;letter-spacing:0.17px;}
        #tp_1{left:770px;top:62px;letter-spacing:0.16px;}
        #tq_1{left:953px;top:62px;letter-spacing:0.11px;}
        #tr_1{left:990px;top:62px;letter-spacing:0.17px;}
        #ts_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tt_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tu_1{left:266px;top:76px;letter-spacing:0.17px;}
        #tv_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tw_1{left:358px;top:76px;letter-spacing:0.17px;}
        #tx_1{left:431px;top:76px;letter-spacing:0.17px;}
        #ty_1{left:431px;top:76px;letter-spacing:3.26px;word-spacing:-3.06px;}
        #tz_1{left:468px;top:76px;letter-spacing:0.17px;}
        #t10_1{left:477px;top:76px;}
        #t11_1{left:422px;top:76px;}
        #t12_1{left:422px;top:76px;}
        #t13_1{left:422px;top:76px;}
        #t14_1{left:788px;top:117px;letter-spacing:0.17px;}
        #t15_1{left:18px;top:131px;letter-spacing:0.15px;}
        #t16_1{left:413px;top:131px;letter-spacing:0.17px;}
        #t17_1{left:165px;top:131px;letter-spacing:0.17px;}
        #t18_1{left:165px;top:131px;letter-spacing:0.15px;}
        #t19_1{left:413px;top:144px;letter-spacing:0.17px;}
        #t1a_1{left:18px;top:144px;letter-spacing:0.17px;}
        #t1b_1{left:541px;top:144px;letter-spacing:0.17px;}
        #t1c_1{left:413px;top:158px;letter-spacing:0.14px;}
        #t1d_1{left:523px;top:158px;}
        #t1e_1{left:18px;top:158px;}
        #t1f_1{left:541px;top:158px;letter-spacing:0.17px;}
        #t1g_1{left:413px;top:172px;letter-spacing:0.14px;}
        #t1h_1{left:523px;top:172px;}
        #t1i_1{left:18px;top:172px;letter-spacing:0.17px;}
        #t1j_1{left:541px;top:172px;letter-spacing:0.17px;}
        #t1k_1{left:413px;top:186px;letter-spacing:0.15px;}
        #t1l_1{left:523px;top:186px;}
        #t1m_1{left:413px;top:199px;letter-spacing:0.17px;}
        #t1n_1{left:18px;top:199px;letter-spacing:0.17px;}
        #t1o_1{left:18px;top:199px;letter-spacing:0.16px;}
        #t1p_1{left:541px;top:199px;letter-spacing:0.17px;}
        #t1q_1{left:18px;top:213px;letter-spacing:0.17px;}
        #t1r_1{left:165px;top:213px;letter-spacing:0.14px;}
        #t1s_1{left:18px;top:227px;letter-spacing:0.17px;}
        #t1t_1{left:110px;top:227px;letter-spacing:0.17px;}
        #t1u_1{left:147px;top:227px;letter-spacing:0.17px;}
        #t1v_1{left:202px;top:227px;letter-spacing:0.16px;}
        #t1w_1{left:633px;top:241px;letter-spacing:0.17px;}
        #t1x_1{left:18px;top:241px;letter-spacing:0.17px;}
        #t1y_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t1z_1{left:770px;top:241px;letter-spacing:0.17px;}
        #t20_1{left:18px;top:254px;letter-spacing:0.15px;}
        #t21_1{left:633px;top:254px;letter-spacing:0.17px;}
        #t22_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t23_1{left:147px;top:254px;letter-spacing:0.17px;}
        #t24_1{left:770px;top:254px;letter-spacing:0.17px;}
        #t25_1{left:18px;top:268px;letter-spacing:0.15px;}
        #t26_1{left:128px;top:268px;}
        #t27_1{left:633px;top:268px;letter-spacing:0.17px;}
        #t28_1{left:147px;top:268px;letter-spacing:0.17px;}
        #t29_1{left:770px;top:268px;letter-spacing:0.17px;}
        #t2a_1{left:18px;top:282px;letter-spacing:0.15px;}
        #t2b_1{left:633px;top:282px;letter-spacing:0.17px;}
        #t2c_1{left:193px;top:282px;letter-spacing:0.17px;}
        #t2d_1{left:770px;top:282px;letter-spacing:0.17px;}
        #t2e_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2f_1{left:9px;top:323px;letter-spacing:0.17px;}
        #t2g_1{left:9px;top:337px;}
        #t2h_1{left:183px;top:337px;letter-spacing:1.93px;word-spacing:-1.74px;}
        #t2i_1{left:9px;top:351px;}
        #t2j_1{left:183px;top:351px;letter-spacing:1.72px;word-spacing:-1.53px;}
        #t2k_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2l_1{left:9px;top:364px;letter-spacing:0.17px;}
        #t2m_1{left:9px;top:406px;letter-spacing:0.17px;}
        #t2n_1{left:275px;top:406px;}
        #t2o_1{left:339px;top:406px;}
        #t2p_1{left:403px;top:406px;}
        #t2q_1{left:468px;top:406px;}
        #t2r_1{left:532px;top:406px;}
        #t2s_1{left:596px;top:406px;}
        #t2t_1{left:660px;top:406px;}
        #t2u_1{left:724px;top:406px;}
        #t2v_1{left:788px;top:406px;}
        #t2w_1{left:853px;top:406px;}
        #t2x_1{left:917px;top:406px;}
        #t2y_1{left:981px;top:406px;}
        #t2z_1{left:1045px;top:406px;}
        #t30_1{left:1109px;top:406px;}
        #t31_1{left:1173px;top:406px;}
        #t32_1{left:28px;top:419px;letter-spacing:0.17px;}
        #t33_1{left:238px;top:419px;letter-spacing:0.17px;}
        #t34_1{left:9px;top:433px;letter-spacing:0.17px;}
        #t35_1{left:211px;top:433px;}
        #t36_1{left:275px;top:433px;}
        #t37_1{left:339px;top:433px;}
        #t38_1{left:403px;top:433px;}
        #t39_1{left:28px;top:447px;letter-spacing:0.17px;}
        #t3a_1{left:174px;top:447px;letter-spacing:0.17px;}
        #t3b_1{left:816px;top:461px;letter-spacing:0.17px;}
        #t3c_1{left:1027px;top:461px;letter-spacing:0.17px;}
        #t3d_1{left:1027px;top:461px;letter-spacing:0.19px;word-spacing:9.17px;}

        .s0{font-size:15px;font-family:Courier;color:#000;}
    </style>
    <!-- End inline CSS -->

    <!-- Begin page background -->
    <div id="pg1Overlay" style="width:100%; height:100%; position:absolute; z-index:1; background-color:rgba(0,0,0,0); -webkit-user-select: none;"></div>
    <div id="pg1" style="-webkit-user-select: none;"><object width="1210" height="825" data="1/1.svg" type="image/svg+xml" id="pdf1" style="width:1210px; height:825px; -moz-transform:scale(1); z-index: 0;"></object></div>
    <!-- End page background -->


    <!-- Begin text definitions (Positioned/styled in CSS) -->
    <div class="text-container"><span id="t1_1" class="t s0">Seite: </span><span id="t2_1" class="t s0">( </span><span id="t3_1" class="t s0">) *Kopie* </span><span id="t4_1" class="t s0">LIEFERSCHEIN </span><span id="t5_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="t6_1" class="t s0">Seite: </span><span id="t7_1" class="t s0">( </span><span id="t8_1" class="t s0">) *Kopie* </span><span id="t9_1" class="t s0">LIEFERSCHEIN </span><span id="ta_1" class="t s0">Katag AG - Stralsunder Str.5 - 33605 Bielefeld </span><span id="tb_1" class="t s0">1 </span><span id="tc_1" class="t s0">1 </span>
        <span id="td_1" class="t s0">/ </span><span id="te_1" class="t s0">Nummer: </span><span id="tf_1" class="t s0">28.09.23 </span><span id="tg_1" class="t s0">15:22 </span><span id="th_1" class="t s0">3034948 </span><span id="ti_1" class="t s0">3034948 </span><span id="tj_1" class="t s0">1 </span><span id="tk_1" class="t s0">1 1 </span><span id="tl_1" class="t s0">1 </span><span id="tm_1" class="t s0">120 </span><span id="tn_1" class="t s0">120 31 </span><span id="to_1" class="t s0">31 </span>
        <span id="tp_1" class="t s0">Auftrag Ind SF </span><span id="tq_1" class="t s0">LO </span><span id="tr_1" class="t s0">Bt </span>
        <span id="ts_1" class="t s0">Liefernr. </span><span id="tt_1" class="t s0">_________ </span><span id="tu_1" class="t s0">Liefernr. 3034948 </span><span id="tv_1" class="t s0">_______ </span><span id="tw_1" class="t s0">3034948 001 </span><span id="tx_1" class="t s0">___ </span><span id="ty_1" class="t s0">001 1 </span><span id="tz_1" class="t s0">__ </span><span id="t10_1" class="t s0">1 </span><span id="t11_1" class="t s0">/ </span><span id="t12_1" class="t s0">_ </span><span id="t13_1" class="t s0">/ </span>
        <span id="t14_1" class="t s0">30349480010112031 </span>
        <span id="t15_1" class="t s0">Kundennummer: </span><span id="t16_1" class="t s0">Streutermin : </span><span id="t17_1" class="t s0">28260001 </span><span id="t18_1" class="t s0">28260001 </span>
        <span id="t19_1" class="t s0">Auftragsdat.: </span><span id="t1a_1" class="t s0">Young Fashion Behrendt </span><span id="t1b_1" class="t s0">28.09.23 </span>
        <span id="t1c_1" class="t s0">Marke </span><span id="t1d_1" class="t s0">: </span><span id="t1e_1" class="t s0">. </span><span id="t1f_1" class="t s0">50 ***Mc Percy </span>
        <span id="t1g_1" class="t s0">Thema </span><span id="t1h_1" class="t s0">: </span><span id="t1i_1" class="t s0">Holmpassage, Holm 39 </span><span id="t1j_1" class="t s0">KATAGABRUF Katag Abrufe </span>
        <span id="t1k_1" class="t s0">Prospekt </span><span id="t1l_1" class="t s0">: </span>
        <span id="t1m_1" class="t s0">Auftragstyp : </span><span id="t1n_1" class="t s0">D-24937 Flensburg </span><span id="t1o_1" class="t s0">D-24937 Flensburg </span><span id="t1p_1" class="t s0">291 Katag Lagerauftrag Anschlusshaus </span>
        <span id="t1q_1" class="t s0">Verdichtung...: VERSA </span><span id="t1r_1" class="t s0">VERSA </span>
        <span id="t1s_1" class="t s0">Versandart</span><span id="t1t_1" class="t s0">....</span><span id="t1u_1" class="t s0">: 200 Hängend: DKS / Liegend: DPD-unfr. </span><span id="t1v_1" class="t s0">Hängend: DKS / Liegend: DPD-unfr. </span>
        <span id="t1w_1" class="t s0">Kundentermin : </span><span id="t1x_1" class="t s0">Denim Jeans </span><span id="t1y_1" class="t s0">28.09.23 </span><span id="t1z_1" class="t s0">28.09.23 </span>
        <span id="t20_1{left:18px;top:254px;letter-spacing:0.15px;}">Modellnummer: </span><span id="t21_1{left:633px;top:254px;letter-spacing:0.17px;}">Kundenauftrag: </span><span id="t22_1{left:147px;top:254px;letter-spacing:0.17px;}">210000943 </span><span id="t23_1{left:147px;top:254px;letter-spacing:0.17px;}">210000943 </span><span id="t24_1{left:770px;top:254px;letter-spacing:0.17px;}">3034948 </span>
        <span id="t25_1{left:18px;top:268px;letter-spacing:0.15px;}">Lagerplatz </span><span id="t26_1{left:128px;top:268px;}">: </span><span id="t27_1{left:633px;top:268px;letter-spacing:0.17px;}">Art.Nr. Lief.: </span><span id="t28_1{left:147px;top:268px;letter-spacing:0.17px;}">P10 </span><span id="t29_1{left:770px;top:268px;letter-spacing:0.17px;}">700 NOS </span>
        <span id="t2a_1{left:18px;top:282px;letter-spacing:0.15px;}">Bereich: </span><span id="t2b_1{left:633px;top:282px;letter-spacing:0.17px;}">Art.Bez.Lief.: </span><span id="t2c_1{left:193px;top:282px;letter-spacing:0.17px;}">2100 Katag, HAKA I / Hosen </span><span id="t2d_1{left:770px;top:282px;letter-spacing:0.17px;}">605 5 P. Regular </span>
        <span id="t2e_1{left:9px;top:323px;letter-spacing:0.17px;}">================================================================================================================================== </span><span id="t2f_1{left:9px;top:323px;letter-spacing:0.17px;}">================================================================================================================================== </span>
        <span id="t2g_1{left:9px;top:337px;}">A </span><span id="t2h_1{left:183px;top:337px;letter-spacing:1.93px;word-spacing:-1.74px;}">31/30 32/30 33/30 34/30 36/30 38/30 40/30 31/32 32/32 33/32 34/32 36/32 38/32 40/32 31/34 32/34 </span>
        <span id="t2i_1{left:9px;top:351px;}">B </span><span id="t2j_1{left:183px;top:351px;letter-spacing:1.72px;word-spacing:-1.53px;}">33/34 34/34 36/34 38/34 40/34 </span>
        <span id="t2k_1{left:9px;top:364px;letter-spacing:0.17px;}">================================================================================================================================== </span><span id="t2l_1{left:9px;top:364px;letter-spacing:0.17px;}">================================================================================================================================== </span>
        <span id="t2m_1{left:9px;top:406px;letter-spacing:0.17px;}">A BLUE STONE </span><span id="t2n_1{left:275px;top:406px;}">1 </span><span id="t2o_1{left:339px;top:406px;}">1 </span><span id="t2p_1{left:403px;top:406px;}">1 </span><span id="t2q_1{left:468px;top:406px;}">1 </span><span id="t2r_1{left:532px;top:406px;}">1 </span><span id="t2s_1{left:596px;top:406px;}">1 </span><span id="t2t_1{left:660px;top:406px;}">1 </span><span id="t2u_1{left:724px;top:406px;}">1 </span><span id="t2v_1{left:788px;top:406px;}">1 </span><span id="t2w_1{left:853px;top:406px;}">1 </span><span id="t2x_1{left:917px;top:406px;}">1 </span><span id="t2y_1{left:981px;top:406px;}">1 </span><span id="t2z_1{left:1045px;top:406px;}">1 </span><span id="t30_1{left:1109px;top:406px;}">1 </span><span id="t31_1{left:1173px;top:406px;}">1 </span>
        <span id="t32_1{left:28px;top:419px;letter-spacing:0.17px;}">600 </span><span id="t33_1{left:238px;top:419px;letter-spacing:0.17px;}">______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ </span>
        <span id="t34_1{left:9px;top:433px;letter-spacing:0.17px;}">B BLUE STONE </span><span id="t35_1{left:211px;top:433px;}">1 </span><span id="t36_1{left:275px;top:433px;}">1 </span><span id="t37_1{left:339px;top:433px;}">1 </span><span id="t38_1{left:403px;top:433px;}">1 </span>
        <span id="t39_1{left:28px;top:447px;letter-spacing:0.17px;}">600 </span><span id="t3a_1{left:174px;top:447px;letter-spacing:0.17px;}">______ ______ ______ ______ </span>
        <span id="t3b_1{left:816px;top:461px;letter-spacing:0.17px;}">Stück gesamt : </span><span id="t3c_1{left:1027px;top:461px;letter-spacing:0.17px;}">19 </span><span id="t3d_1{left:1027px;top:461px;letter-spacing:0.19px;word-spacing:9.17px;}">19 STK </span></div>
    <!-- End text definitions -->


</div>
</body>
</html>


--- Generated JasperReport TextFields ---

            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="21" width="70" height="30" />
                <textFieldExpression><![CDATA["Seite: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="128" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["( "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="165" y="21" width="100" height="30" />
                <textFieldExpression><![CDATA[") *Kopie* "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="266" y="21" width="130" height="30" />
                <textFieldExpression><![CDATA["LIEFERSCHEIN "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="394" y="21" width="470" height="30" />
                <textFieldExpression><![CDATA["Katag AG - Stralsunder Str.5 - 33605 Bielefeld "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="110" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="156" y="21" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="101" y="48" width="20" height="30" />
                <textFieldExpression><![CDATA["/ "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="697" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["Nummer: "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="18" y="48" width="90" height="30" />
                <textFieldExpression><![CDATA["28.09.23 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="119" y="48" width="60" height="30" />
                <textFieldExpression><![CDATA["15:22 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="770" y="48" width="80" height="30" />
                <textFieldExpression><![CDATA["3034948 "]]></textFieldExpression>
            </textField>

            <textField>
                <reportElement style="t s0" x="862" y="48" width="20" height="30" />
                <textFieldExpression><![CDATA["1 "]]></textFieldExpression>
            </textField>

            <textField>

## Generate new cells

### Subtask:
Generate any new markdown or code cells needed for the restructured notebook.

## Summary:

### Data Analysis Key Findings

*   The notebook was successfully restructured with the requested markdown headings: README, 1. Konstanten eintragen: HTML-Seitengröße und JasperReport-Größe, 2. HTML-Code übergeben und speichern, 3. Code-Sektionen, and 4–x. Diverse Aufrufe und Ausgaben.
*   Introductory text was added at the beginning of the notebook.
*   Python code cells were organized to align with the new markdown structure, placing constant definitions, HTML content, function definitions, and execution calls under their respective headings.
*   The Python functions for converting HTML positions, generating JasperReports XML elements (text fields and styles), sorting text fields, adjusting positions and scaling, and generating SQL insert statements were preserved and function correctly within the new structure.
*   The process of converting HTML 'bottom' positions to 'top' positions was successfully implemented and demonstrated.
*   The extraction of text content, positions, and styles from HTML and their conversion into JasperReports XML format was validated.
*   The sorting of JasperReports text fields based on their y-coordinate was successfully applied.
*   The scaling and offsetting of JasperReports element positions based on defined factors were correctly implemented.
*   SQL insert statements for sample article and article data row data were generated as intended.

### Insights or Next Steps

*   The current text field width calculation (`10 * len(str(span_text))`) is a simple approximation. A more accurate calculation based on font metrics and actual text width would improve the visual fidelity of the generated JasperReport.
*   The process currently handles only text elements. Extending the functionality to include other HTML elements like images, tables, and lines would make the conversion process more comprehensive.